Cardinal-Cryptography/aleph-node

finality-aleph/Cargo.toml, finality-aleph/src/environment.rs, finality-aleph/src/messages.rs, finality-aleph/src/party.rs, run_nodes.sh
Note: this requires the changes in rush in order to compile.
=> Added support for wrong control hashes.

finality-aleph/Cargo.toml, finality-aleph/src/hash.rs, finality-aleph/src/lib.rs, finality-aleph/src/party.rs
Make aleph node compatible with rush after https://github.com/Cardinal-Cryptography/rush/pull/55
=> Refactor KeyBox  and Signatures

bin/node/Cargo.toml, bin/node/src/service.rs, bin/runtime/src/lib.rs, finality-aleph/src/import.rs, finality-aleph/src/lib.rs, pallet/Cargo.toml, pallet/src/lib.rs, pallet/src/mock.rs, pallet/src/tests.rs, primitives/src/lib.rs
* Forward all justifications from BlockImport to JustificationNotification sender
* Remove WillChange storage from pallet
* Add AlephSessionApi
* Implement AlephSessionApi trait for runtime
=> Add committee change handling to block import and pallet

bin/node/src/service.rs, finality-aleph/Cargo.toml, finality-aleph/src/lib.rs, finality-aleph/src/network.rs, finality-aleph/src/network/tests.rs, finality-aleph/src/party.rs, primitives/src/lib.rs
Mostly changes related to the new network trait.
=> Bump AlephBFT version

finality-aleph/src/network.rs, finality-aleph/src/network/tests.rs
Now it actually works more than just based on luck.
=> Improve network authentication

bin/node/src/chain_spec.rs
I am now pretty convinced that we should be using json chain specs...
=> Add token names for dev and test networks

.github/workflows/deploy.yml, docker/Dockerfile
part of devnet ticket - changes push repository to a public one + updated Docker image
=> changing push reporitory to ECR public repo

finality-aleph/src/lib.rs, finality-aleph/src/party.rs
`party::run_session_as_authority` awaits its components to finish gracefully.
=> Graceful exit

.github/workflows/deploy.yml, .github/workflows/integration_tests.yml, .github/workflows/unit_tests.yml, README.md
- fixes for the failing deployment workflows (failed when downloading artifacts created in a different workflow).
- moved quick tasks from the unit-testing workflow (linter, formatter) to start before long running ones - checks and unit tests
=> A0-236 : fix artifact dl step

.github/workflows/integration_tests.yml, docker/.env, docker/Dockerfile, docker/docker-compose.yml, docker/docker_entrypoint.sh
Improves dockerfile usage experience.
- Expose ports used in command
- Use Entrypoint default params in `docker-compose`
- Specify ubuntu version of docker for extension
- Add .env file for environment variables
From now docker-compose should be run as `docker-compose --env-file ./docker/.env -f docker/docker-compose.yml up`
=> A0-304: create common docker file

Cargo.lock, finality-aleph/Cargo.toml, finality-aleph/src/lib.rs, finality-aleph/src/network.rs, finality-aleph/src/party.rs
changed API of network and member
=> update aleph node to use newest alephbft version

finality-aleph/src/network.rs, run_nodes.sh
Added useful logging in network.
=> Network logs

.github/workflows/deploy-main-devnet.yml, .github/workflows/deploy.yml, .github/workflows/e2e-tests-main-devnet.yml, .github/workflows/e2e_tests.yml
As settled, name of pipeline files has changed from integration.. to e2e..
=> Change pipeline names: integration.. -> e2e..

.github/workflows/deploy-testnet.yml
Pipeline for deployment on prerelease, onto K8S testnet environment added as in A0-400 task.
=> Pipeline for Testnet deployment added

.github/workflows/post-dod-checklist.yml
I checked and it worked, including checkboxes. At least in my repo?
=> A0-409: Add DoD reminder

Cargo.lock, finality-aleph/Cargo.toml, finality-aleph/src/new_network/connection_manager/addresses.rs, finality-aleph/src/new_network/connection_manager/mod.rs, finality-aleph/src/new_network/connection_manager/session.rs, finality-aleph/src/new_network/mod.rs
This one has proper tests. They even caught one major bug I left in when developing, so yeah, quality coding. <_<
Still dead code.
=> Az-107: Add per-session connection manager

bin/node/src/chain_spec.rs, bin/node/src/commands.rs, run_nodes.sh
I was not able to reproduce the problem with network in `run_nodes.sh` you described, but I hope this fixes it :)
=> Refactor argument handling in ChainParams and fix run_nodes.sh

finality-aleph/src/new_network/component.rs, finality-aleph/src/new_network/manager/mod.rs, finality-aleph/src/new_network/manager/service.rs, finality-aleph/src/new_network/mod.rs, finality-aleph/src/new_network/service.rs, finality-aleph/src/new_network/session.rs, finality-aleph/src/new_network/split.rs
=> AZ-107: Split networks

.github/scripts/test_update.sh, .github/workflows/e2e-tests-main-devnet.yml, local-tests/test_update.py
=> AZ-408: Basic runtime update check

.github/workflows/e2e-tests-main-devnet.yml, docker-runtime-hook/entrypoint.sh, local-tests/README.md, local-tests/test_update.ipynb, local-tests/test_update.py
This is needed so that an automatic pipeline can detect that something went wrong with the update test
=> AZ-408: test_update.py returns non-zero when update failed

local-tests/test_update.ipynb, local-tests/test_update.py
More robust version is needed here so that substrate++ pipeline can go through
=> Better RPC error handling in test_update

finality-aleph/src/data_io.rs, finality-aleph/src/network/mod.rs, finality-aleph/src/party/data_store.rs, finality-aleph/src/party/mod.rs
This is a small refactor simplifying `select!` in `DataStore::run`.
=> AZ-455 use ComponentNetwork in data_io

finality-aleph/src/metrics.rs
Please refer to JIRA's comment for bug reproduction logs.
=> AZ-464 A safe check for Instant::now() to prevent monotonic clock bug

finality-aleph/src/data_io.rs, finality-aleph/src/lib.rs, finality-aleph/src/metrics.rs, finality-aleph/src/network/manager/discovery.rs, finality-aleph/src/network/manager/service.rs, finality-aleph/src/network/manager/session.rs, finality-aleph/src/network/service.rs, finality-aleph/src/party/data_store.rs
Also remove some ancient print debugging that somehow slipped by
reviewers. <_<"
=> Make the validator peerset more restrictive

bin/node/src/chain_spec.rs, bin/node/src/commands.rs, pallets/elections/src/lib.rs
Testing done:
* build,
* UI tests (eras progressing, events emitted `StakersElected`, `EraPaid`).
=> Az 541 Modified chainspec generation for pallet staking 

bin/runtime/src/lib.rs
Testing done:
* build,
* UI test with 4 validators
=> AZ-578 Fix rewards to include era length instead of hardcoded to a daily length

.github/scripts/run_consensus.sh, e2e-tests/Cargo.lock, e2e-tests/Cargo.toml, e2e-tests/src/lib.rs, e2e-tests/src/main.rs, e2e-tests/src/test/mod.rs, e2e-tests/src/test/staking.rs, e2e-tests/src/test/transfer.rs, e2e-tests/src/test/treasury.rs, e2e-tests/src/test/validators_change.rs, e2e-tests/src/transfer.rs, run_nodes.sh
Testing done:
* build,
* tests e2e passes locally
=> Az 540 fix e2e tests

.github/workflows/deploy-feature-envs.yaml, aleph-client/Cargo.lock, aleph-client/Cargo.toml, aleph-client/src/lib.rs, benches/payout-stakers/Cargo.lock, benches/payout-stakers/Cargo.toml, benches/payout-stakers/src/main.rs, bin/cliain/Cargo.lock, docker/docker_entrypoint.sh, local-tests/chainrunner/chain.py, local-tests/chainrunner/node.py, local-tests/run_nodes.py, primitives/src/lib.rs
This PR introduce new workflow for the whole feature branch deployment mechanism.
=> Add workflow for the fe deployment mechanism

aleph-client/src/staking.rs, bin/cliain/Cargo.lock, bin/cliain/src/main.rs, bin/cliain/src/staking.rs, scripts/setup_staking.sh
=> A0-828 Added support for maxNominatorsCount to cliain and setup_staking.sh

aleph-client/src/staking.rs, bin/cliain/src/main.rs, bin/cliain/src/staking.rs, scripts/setup_staking.sh
=> A0-858 Add support for maxValidatorsCount for cliain and setup_staking.sh

bin/node/src/cli.rs
The goal is to change the node's name displayed in the wallet:
to Aleph Node
=> Fix node's identity crisis

Cargo.lock, bin/node/src/chain_spec.rs, bin/runtime/src/lib.rs, pallets/elections/Cargo.toml, pallets/elections/src/lib.rs, pallets/elections/src/mock.rs
Reverts Cardinal-Cryptography/aleph-node#369
=> Revert "Everybody wins"

.github/workflows/deploy-testnet.yml
This PR adding environment usage for the workflow.
=> Add environment usage to the testnet workflow

.github/workflows/e2e-tests-main-devnet.yml
Cherry-picked commit from main introducing changes in the e2e workflow.
=> Add changed workflow file for e2e tests

.github/workflows/deploy-testnet.yml
Adding environment to the workflow.
=> Add environment usage to the testnet workflow (#401)

finality-aleph/src/network/manager/service.rs, finality-aleph/src/network/manager/session.rs
=> add to reserved only if we are in validators

scripts/update_substrate_git_branch.sh
The script `update_substrate_git_branch.sh` was outdated and bugged. This PR fixes it.
The problems were:
- only some part of crates was taken into account: now we check all crates in repository
- the former version of the scripts removed any dependency configuration (like `features` or `default-features`) if it was specified after git branch: now we preserve that
=> Fix `update_substrate_git_branch.sh`

aleph-client/Cargo.lock, aleph-client/Cargo.toml, aleph-client/src/account.rs, aleph-client/src/lib.rs, aleph-client/src/rpc.rs, aleph-client/src/staking.rs, benches/payout-stakers/Cargo.lock, benches/payout-stakers/src/main.rs, bin/cliain/Cargo.lock, e2e-tests/Cargo.lock, e2e-tests/src/test/staking.rs, flooder/Cargo.lock, flooder/src/main.rs, flooder/src/ws_rpc_client.rs
This PR introduces some minor code changes that were a subject of `cargo clippy` complaining.
=> Calm `clippy` down

.github/actions/README.md, .github/actions/run-e2e-test/action.yml, .github/workflows/e2e-tests-main-devnet.yml
=> A0-932 Added follow-up finalization check to some e2e tests

fork-off/Cargo.lock, fork-off/Cargo.toml, fork-off/src/chainspec_combining.rs, fork-off/src/config.rs, fork-off/src/fetching.rs, fork-off/src/fsio.rs, fork-off/src/main.rs
Just small reorganization of `fork-off` tool.
=> Refactor fork-off

bin/runtime/src/lib.rs, pallets/elections/src/impls.rs, pallets/elections/src/lib.rs, pallets/elections/src/mock.rs, pallets/elections/src/traits.rs
=> Remove staking&session from impl details of the pallet elections

aleph-client/Cargo.lock, aleph-client/src/staking.rs, bin/cliain/Cargo.lock, bin/cliain/Cargo.toml, bin/cliain/src/lib.rs, bin/cliain/src/main.rs, bin/cliain/src/staking.rs, e2e-tests/src/test/staking.rs, scripts/run_nodes.sh, scripts/setup_staking.sh
=> A0-930 Add support for nominate to cliain

scripts/run_e2e.sh
=> fix script cmd

Cargo.lock, bin/runtime/Cargo.toml, bin/runtime/src/lib.rs
=> Identity pallet

.github/actions/destroy-feature-environment/action.yml, .github/workflows/deploy-feature-envs.yaml
This changes introduce posibility of deploying feature environment from mainnet.
=> Add deployment of hotnet to the fe-deployment workflow

bin/runtime/src/lib.rs, pallets/elections/src/impls.rs, pallets/elections/src/lib.rs
=> fix change_validators call (#515)

.github/workflows/e2e-tests-main-devnet.yml, aleph-client/Cargo.lock, aleph-client/Cargo.toml, aleph-client/src/lib.rs, aleph-client/src/session.rs, bin/cliain/Cargo.lock, bin/cliain/Cargo.toml, bin/cliain/src/validators.rs, bin/runtime/src/lib.rs, e2e-tests/Cargo.lock, e2e-tests/Cargo.toml, e2e-tests/src/cases.rs, e2e-tests/src/test/electing_validators.rs, e2e-tests/src/test/era_validators.rs, e2e-tests/src/test/mod.rs, e2e-tests/src/test/staking.rs, e2e-tests/src/test/validators_change.rs, e2e-tests/src/test/validators_rotate.rs, pallets/elections/src/impls.rs, pallets/elections/src/lib.rs, pallets/elections/src/migrations/mod.rs, pallets/elections/src/migrations/v1_to_v2.rs, pallets/elections/src/migrations/v2_to_v3.rs, pallets/elections/src/mock.rs, pallets/elections/src/tests.rs, pallets/elections/src/traits.rs
=> Rotating reserved nodes | Electing staking validators

bin/runtime/src/lib.rs
Test to ensure that the `state_version` was not changed by 'accident'.
- new test (pls someone add an option for just tests :D )
- I have added test (actually the only thing that I did)
=> Add test to enforce state version

.github/workflows/e2e-tests-contracts.yml, .gitignore, contracts/README.md, contracts/env/dev, contracts/scripts/deploy.sh, contracts/scripts/test.sh, docker/smartnet-compose.yml
- Split deployment script from testing script
- write deployed contract addresses to a file
- allow for setting arguments for use with different environments 
=> split deployment script

Cargo.lock, finality-aleph/Cargo.toml, finality-aleph/src/data_io/data_interpreter.rs, finality-aleph/src/data_io/data_provider.rs, finality-aleph/src/data_io/data_store.rs, finality-aleph/src/data_io/mod.rs, finality-aleph/src/party/manager/mod.rs, finality-aleph/src/testing/mocks/proposal.rs
Change implementation of `DataProvider` to return `Option`.
- Refactor
- I have updated tests
=> Bump alephbft version to 0.18.1

finality-aleph/src/party/mod.rs
=> Remove leftover println

finality-aleph/src/data_io/data_provider.rs
Replace async mutexes with sync ones.
=> Change async mutexes to sync ones in `get_data`.

finality-aleph/README.md
=> Simple readme

Cargo.lock, aleph-client/Cargo.lock, benches/payout-stakers/Cargo.lock, bin/cliain/Cargo.lock, bin/runtime/src/lib.rs, flooder/Cargo.lock, pallets/aleph/Cargo.toml, pallets/aleph/src/lib.rs, pallets/aleph/src/migrations/v0_to_v1.rs, pallets/aleph/src/migrations/v1_to_v2.rs, pallets/aleph/src/tests.rs
We adjust storage migrations for pallet aleph to the new interface (analogous to pallet elections).
=> A0-1222: Refined aleph storage migration

.github/workflows/nightly-pipeline.yaml
There is a small mistake in one of the steps in the nightly pipeline workflow.
=> Fix a mistake in a step in nightly pipeline workflow

finality-aleph/src/data_io/data_interpreter.rs, finality-aleph/src/data_io/proposal.rs, finality-aleph/src/data_io/status_provider.rs
Create justifications for all blocks. This not only fixes the linked bug (at least for validators), but also finally implements an ADR.
=> Create justifications for all blocks

.github/actions/destroy-feature-environment/action.yml
Change getting branch name in destroy-feature-environment workflow to be consistent and use get-branch action.
=> A0-1250: Use get-branch action in destroy-feature-environment action

aleph-client/Cargo.lock, aleph-client/Cargo.toml, aleph-client/src/lib.rs, aleph-client/src/session.rs, benches/payout-stakers/Cargo.lock, bin/cliain/Cargo.lock, bin/cliain/Cargo.toml, bin/cliain/src/commands.rs, bin/cliain/src/keys.rs, bin/cliain/src/lib.rs, bin/cliain/src/main.rs, e2e-tests/Cargo.lock, flooder/Cargo.lock
Adding new cliain command to enable easy "NextKeys" queries.
=> A0-1361: cliain: Add possibility to query NextKeys for a specified AccountId

bin/cliain/Dockerfile
Add Dockerfile to cliain so we might use it as a tool outside aleph-node repo.
=> Add Dockerfile for cliain

finality-aleph/src/aggregation/aggregator.rs, finality-aleph/src/aggregation/multicast.rs, finality-aleph/src/justification/handler.rs, finality-aleph/src/justification/requester.rs, finality-aleph/src/lib.rs, finality-aleph/src/network/manager/service.rs, finality-aleph/src/network/manager/session.rs, finality-aleph/src/network/mock.rs, finality-aleph/src/network/mod.rs, finality-aleph/src/network/service.rs, finality-aleph/src/party/manager/aggregator.rs, finality-aleph/src/status.rs, finality-aleph/src/substrate_network.rs
This PR adds new logs for finality-aleph components. Specificaly to:
**Network status report**
Example report for 2 connected authorities plus 2 connected archivists:
```
2022-09-12 16:02:59 Network status report: validator connected peers - 2 [12D3KooWCmz8XwEief5Z9Dt42MqzSJcjzD48wEoNGXxBmnodAv5S, 12D3KooWQ49SdyE3fM3vw8VupK5GvzGfvVkJMoM9UeaUQD5FvTAX]; generic connected peers - 4;
```
**Connection Manager Service status report** 
Example report for 1 missing undetected authority:
```
2022-09-12 16:02:59 Connection Manager Service status report: authenticated authorities: authenticated authorities: 1: 3/4 {2: 12D3KooWQ49SdyE3fM3vw8VupK5GvzGfvVkJMoM9UeaUQD5FvTAX, 3: 12D3KooWCmz8XwEief5Z9Dt42MqzSJcjzD48wEoNGXxBmnodAv5S}, 0: 3/4 {3: 12D3KooWCmz8XwEief5Z9Dt42MqzSJcjzD48wEoNGXxBmnodAv5S, 2: …
```
=> A0-1340: add info level logs to finality-aleph components

Cargo.lock, Cargo.toml, aggregator/Cargo.toml, aggregator/src/aggregator.rs, aggregator/src/lib.rs, aggregator/src/multicast.rs, finality-aleph/Cargo.toml, finality-aleph/src/aggregation/mod.rs, finality-aleph/src/party/manager/aggregator.rs
Changes required to also have different versions of aggregator (based on aleph-bft version)
=> MC: extract aggregator to crate

finality-aleph/src/validator_network/handshake.rs
Implementing proper handshake for validator network.
=> A0-1409 Validator Network handshake

finality-aleph/src/validator_network/heartbeat.rs, finality-aleph/src/validator_network/manager.rs, finality-aleph/src/validator_network/mod.rs, finality-aleph/src/validator_network/outgoing.rs, finality-aleph/src/validator_network/protocols.rs, finality-aleph/src/validator_network/service.rs
PR 4/5 in the validator network. Connection manager and service that has to be run to have the network actually do net work.
=> A0-1408: Connection manager and service

finality-aleph/src/lib.rs, finality-aleph/src/tcp_network.rs, finality-aleph/src/testing/mocks/validator_network.rs
PR 5/5 for the validator network. This one adds the actual implementation of the network using TCP.
=> A0-1408: Add a TCP network

bin/runtime/src/lib.rs, pallets/snarcos/src/lib.rs
Companion to https://github.com/Cardinal-Cryptography/HouseSnark/pull/3.
=> Support another proving system (GM17)

contracts/env/fe-benjamin
=> Increase fe lifetime

finality-aleph/src/compatibility.rs, finality-aleph/src/justification/compatibility.rs, finality-aleph/src/lib.rs, finality-aleph/src/network/manager/compatibility.rs, finality-aleph/src/network/manager/mod.rs, finality-aleph/src/network/mock.rs, finality-aleph/src/network/service.rs
Cleanup of the version usage. 
Add wrapper for tuple (data, session) to ensure how it is encoded.
- I have made corresponding changes to the existing documentat
=> cleanup version and data with session

finality-aleph/src/party/manager/mod.rs
Actually fallback to the legacy version!
=> fix running default version

.github/workflows/deploy-testnet.yml
Image used in `FROM` is invalid
=> Fix invalid source docker image used for building docker hub image

Cargo.lock, aleph-client/Cargo.lock, aleph-client/Cargo.toml, benches/payout-stakers/Cargo.toml, bin/cliain/Cargo.lock, bin/cliain/Cargo.toml, bin/node/Cargo.toml, bin/runtime/Cargo.toml, bin/runtime/src/chain_extension/snarcos-extension/Cargo.lock, bin/runtime/src/chain_extension/snarcos-extension/Cargo.toml, contracts/snarcos-contract/Cargo.lock, contracts/snarcos-contract/Cargo.toml, e2e-tests/Cargo.toml, finality-aleph/Cargo.toml, flooder/Cargo.toml, fork-off/Cargo.toml, pallets/aleph/Cargo.toml, pallets/elections/Cargo.toml, pallets/snarcos/Cargo.toml, pallets/support/Cargo.toml, primitives/Cargo.toml
We go for a dedicated branch in our Substrate fork.
=> Update substrate dependency

contracts/env/fe-benjamin
Missed the export for this variable, which makes deployments crash.
=> Add missing export

aleph-client/Cargo.lock, aleph-client/src/contract/mod.rs, e2e-tests/Cargo.lock, e2e-tests/src/test/mod.rs
=> commit fixes

.github/workflows/unit_tests.yml, pallets/snarcos/Cargo.toml, pallets/snarcos/src/benchmarking/import.rs, pallets/snarcos/src/benchmarking/suite.rs, pallets/snarcos/src/tests/mod.rs, pallets/snarcos/src/tests/setup.rs
=> A0-1546: Include benchmarks in unit test suite

contracts/blender/Cargo.toml, contracts/blender/src/contract.rs, contracts/blender/src/error.rs, contracts/blender/src/lib.rs
Use `Openbrush::Ownable` instead of manual control
=> Blender: ownable

contracts/blender/Cargo.lock, contracts/blender/Cargo.toml, contracts/blender/src/contract.rs, contracts/blender/src/crypto.rs, contracts/blender/src/lib.rs, contracts/setup_blending.sh
Use tangling procedure instead of old dummy kinder blending. Also, increase number of leaves in the local dev script.
=> Harness tangling

contracts/setup_blending.sh
Improve setting up the local environment:
- two token contracts
- two blender users
=> Blender setup++

contracts/blender/Cargo.lock, contracts/blender/Cargo.toml, contracts/blender/src/contract.rs, contracts/blender/src/lib.rs
For 90% a correct public input serialization. To be merged after we test it with relation keys
=> Blender: public input serialization

finality-aleph/src/validator_network/manager/mod.rs
Small fix for status report. Prevoiusly diplayed incorrect values.
=> fix validator network outgoing peers status report

Cargo.lock, bin/node/Cargo.toml
As preparation for Testnet hotifx 8.3 release
=> Preparation for Testnet hotfix release 8.3

finality-aleph/src/sync/substrate/mod.rs
Just quickly adding an implementation which will be useful later to unblock some tasks.
=> Add justification implementation

Cargo.lock, bin/node/Cargo.toml, bin/runtime/Cargo.toml
In preparation for testnet release.
=> Bump to 9.0

finality-aleph/src/justification/requester.rs
Now reset justification request status after each finalized block.
=> fix justification request status report not resetting

relations/src/lib.rs, relations/src/shielder/deposit.rs, relations/src/shielder/deposit_and_merge.rs, relations/src/shielder/mod.rs, relations/src/shielder/withdraw.rs
Adds deposit-and-merge relation
=> Adds DepositAndMergeRelation

.github/workflows/unit_tests.yml
=> Exclude finality-aleph unit tests

Cargo.lock, Cargo.toml
=> Exclude excluded

bin/runtime/src/lib.rs, bin/runtime/src/migrations/mod.rs, bin/runtime/src/migrations/scheduler.rs, bin/runtime/src/migrations/staking.rs
[try-runtime.log](https://github.com/Cardinal-Cryptography/aleph-node/files/10673905/try-runtime.log)
=> Scheduler migration

.github/workflows/check-excluded-packages.yml
Ensure that some crates are `no-std`-compatible.
`poseidon` will be checked as well, as soon as it becomes `no-std` friendly (soon).
=> Use cargo nono

bin/cliain/Cargo.lock, relations/Cargo.lock, relations/Cargo.toml, relations/src/linear.rs, relations/src/proc_macro/Cargo.lock, relations/src/proc_macro/Cargo.toml, relations/src/proc_macro/LICENSE, relations/src/shielder/deposit.rs, relations/src/shielder/deposit_and_merge.rs, relations/src/shielder/withdraw.rs, relations/src/xor.rs
This PR prepares macro package to be relased to crates.io. Once it is approved, I will manually publish it. Automated publishing with pipelines will be done later, once we have poseidons and relations migrated.
=> Publish macro

bin/runtime/src/chain_extension/baby-liminal-extension/Cargo.lock, bin/runtime/src/chain_extension/baby-liminal-extension/Cargo.toml, bin/runtime/src/chain_extension/baby-liminal-extension/lib.rs
Bumps ink version to stable releas of ink4.
=> Update ink deps in baby liminal chain extension.

contracts/poseidon_host_bench/.gitignore, contracts/poseidon_host_bench/Cargo.toml, contracts/poseidon_host_bench/lib.rs
Simple contract to see gas consumption.
=> Contract bench

relations/src/lib.rs, relations/src/shielder/merge.rs, relations/src/shielder/mod.rs
Introduces the _merge_ relation for the pooling of two notes.
=> A0-1921: Add merge relation

.github/dependabot.yml
Create dependabot configuration to enable it
=> A0-2007: Add dependabot.yml

finality-aleph/src/sync/forest/mod.rs, finality-aleph/src/sync/handler.rs, finality-aleph/src/sync/mock/backend.rs, finality-aleph/src/sync/mock/mod.rs, finality-aleph/src/sync/mock/status_notifier.rs, finality-aleph/src/sync/mod.rs, finality-aleph/src/sync/service.rs, finality-aleph/src/sync/substrate/status_notifier.rs
The rest of the block sync logic.
=> A0-1797: Block sync service

Cargo.lock, baby-liminal-extension/Cargo.toml, baby-liminal-extension/tests/utils/environment.rs
Ran cargo update, to pacify dependabot. On the way discovered a warning resulting from us requiring a feature that no longer exists, so also cleaned that up.
Cleanup.
=> Cargo update and remove unnecessary feature

.github/workflows/deploy-mainnet.yml
A bugfix to syntax
```
marcin@marcin-Latitude-3520 ~/g/aleph-node-2 (fix-maninnet-workflow)> docker run --rm --name tmp-validatr -v ~/git/aleph-node-2/.github:/gh public.ecr.aws/p6e8q1z1/github-workflows-validator:0.2.0 validate -p /gh | grep '^E' | grep 'deploy-mainnet'
marcin@marcin-Latitude-3520 ~/g/aleph-node-2 (fix-maninnet-workflow) [1]>   
```
=> Fix to mainnet workflow

.github/workflows/deploy-mainnet.yml
Mainnet workflow bug we have propagated to so many release branches.
=> Fix invalid variable in deploy-mainnet workflow

Cargo.lock, bin/node/Cargo.toml, finality-aleph/src/abft/common.rs, finality-aleph/src/abft/current.rs, finality-aleph/src/abft/legacy.rs
Increasing the maximum number of rounds from 5000 to 7000.
=> Fixed max-rounds in alephbft.

finality-aleph/src/abft/common.rs, finality-aleph/src/abft/current.rs, finality-aleph/src/abft/legacy.rs
This is a cherry-pick  of commit https://github.com/Cardinal-Cryptography/aleph-node/commit/1c24e9e8
=> Cherry-pick Mainnet hotfix release 9.1 to 10.0

Cargo.lock, bin/cliain/Cargo.lock, pallets/baby-liminal/Cargo.toml, primitives/Cargo.toml, relations/Cargo.lock, relations/Cargo.toml
Use poseidon from https://crates.io/crates/liminal-ark-poseidon. Allow for publishing `relations`. Pipelines for automatic publishing will be done soon.
=> Use poseidon from crates.io

.github/workflows/deploy-mainnet.yml
cherry-pick of https://github.com/Cardinal-Cryptography/aleph-node/commit/7daa6f9b52974804aae3b283ce3b9d4b0fd5d69b
=> Fix to mainnet workflow (#1033)

scripts/run_nodes.sh
Add an option to rerun the chain without bootstrap & purge the chain
=> allow restarting chain without bootstrap

.github/workflows/_check-excluded-packages.yml
=> A0-0000: speed-up-pipelines

contracts/button/lib.rs, contracts/marketplace/lib.rs, contracts/scripts/deploy.sh
- Rewards in pico units are not sexy, we make sure to always return at least 1 full unit.
- gas optimization when calculating linear
- introduce extra event for indexer to listen to. It will include ThePressiah rewards in the scoreboard
=> A0-2350: rewards in full units

contracts/button/lib.rs, contracts/env/dev, contracts/env/devnet, contracts/marketplace/lib.rs, contracts/scripts/deploy.sh, e2e-tests/src/test/button_game/mod.rs
=> A0-2418: fix scores regression

bin/cliain/Cargo.lock, bin/cliain/src/keys.rs
Using `cliain` to change the keys of a validator was annoying, because of the format of the result of a `rotate_keys` call. I made it simpler.
=> A0-2397: Improve key rotation UX in cliain

contracts/button/lib.rs, contracts/env/dev, contracts/env/devnet, contracts/scripts/deploy.sh
Use output from simulations to try and guide some tokenomic decisions.
- Jupyter Notebook with the simulations: https://github.com/Cardinal-Cryptography/the-button-tokenomic
=> A0-1519: Settle tokenomics v1

contracts/button/lib.rs
=> A0-0000: add total_rewards query

bin/runtime/src/lib.rs
[try-runtime.log](https://github.com/Cardinal-Cryptography/aleph-node/files/11485838/try-runtime.log)
=> A0-1845: add migrations

.github/workflows/_check-excluded-packages.yml
Follow-up to #1189 - we are running unit tests for the baby-liminal pallet.
=> A0-2513: Run tests for baby-liminal pallet

Cargo.lock, baby-liminal-extension/Cargo.lock, pallets/baby-liminal/Cargo.lock
Run `cargo update -p jf-plonk` 
=> A0-2581: Fix main build

relations/ark/src/shielder/deposit_and_merge.rs, relations/jf/src/deposit_and_merge.rs, relations/jf/src/lib.rs, relations/jf/src/merge.rs
=> A0-2499: Plonk deposit and merge

finality-aleph/src/import.rs
Remove a leftover change cherrypicked from a release candidate that did not end up working properly.
=> Do not treat these blocks like that

finality-aleph/src/sync/forest/mod.rs, finality-aleph/src/sync/handler.rs, finality-aleph/src/sync/service.rs
Puts the incoming blocks into Substrate import queue.
=> A0-2406: Handle incoming blocks

finality-aleph/src/data_io/data_store.rs, finality-aleph/src/nodes.rs, finality-aleph/src/party/manager/data_store.rs, finality-aleph/src/party/manager/mod.rs, finality-aleph/src/sync/compatibility.rs, finality-aleph/src/sync/mod.rs, finality-aleph/src/sync/service.rs, finality-aleph/src/testing/data_store.rs
=> A0-2409: Handle incoming blocks in compatible way

.github/workflows/_check-vars-and-secrets.yml, .github/workflows/on-pull-request-commit.yml
This PR fixes bug introduced in https://github.com/Cardinal-Cryptography/aleph-node/pull/1266/files#diff-16614fa322f784957f3df3faa19aa4cf37fe5cba517c065cd77ec93f1144cd8d that broke dev GH fork flow.
=> A0-2728: Fix PR commit workflow for dev fork flow

finality-aleph/src/metrics.rs, finality-aleph/src/nodes.rs, finality-aleph/src/sync/service.rs
Adding sync-related Prometheus metrics.
=> A0-2797: Add sync metrics

finality-aleph/src/aggregation/mod.rs, finality-aleph/src/metrics.rs, finality-aleph/src/network/gossip/service.rs, finality-aleph/src/nodes.rs, finality-aleph/src/testing/network.rs
Measure the time sending over the substrate network takes and make it show up in prometheus.
=> Measure time it takes to send messages in gossip network

Cargo.lock, bin/node/Cargo.toml, bin/runtime/Cargo.toml
Bumping version on release branch for testnet release 11.3
=> A0-000: Release 11.3 version bump in our crates

finality-aleph/src/sync/service.rs
Ports the cooldown reduction from the release-11 branch.
=> A0-2815: Increase block sync broadcast cooldowns

Makefile, bin/node/src/chain_spec.rs, bin/runtime/src/lib.rs
this is the fix, see [request](https://github.com/Cardinal-Cryptography/parity-bridges-common/blob/obrok/aleph-v0.9.41/relays/lib-substrate-relay/src/finality/engine.rs#L146) and [hardcoded constant](https://github.com/Cardinal-Cryptography/parity-bridges-common/blob/obrok/aleph-v0.9.41/primitives/chain-westend/src/lib.rs#L98)
=> this is it

finality-aleph/src/session.rs, finality-aleph/src/sync/forest/mod.rs, finality-aleph/src/sync/forest/vertex.rs, finality-aleph/src/sync/handler/mod.rs, finality-aleph/src/sync/mock/backend.rs, finality-aleph/src/sync/mock/mod.rs
Fixing a handle response bug. Further improving `Handler` testing code.
=> A0-2770: Handler unit tests part 2

BUILD.md
Cherry pick from release-11
- Documentation update
=> A0-000: Update BUILD.md nix intructions

.github/workflows/_check-code-formatting.yml, .github/workflows/_check-vars-and-secrets.yml, .github/workflows/on-pull-request-commit.yml, README.md
This PR removes some of the previous logic related to checking variables on forks. Since forks do not support vars (and secrets), see https://github.com/orgs/community/discussions/44322, we can't check them there.
=> A0-2998: Fix PRs on fork

Cargo.lock, bin/node/src/service.rs, clique/Cargo.toml, clique/src/incoming.rs, clique/src/manager/direction.rs, clique/src/manager/mod.rs, clique/src/metrics.rs, clique/src/outgoing.rs, clique/src/protocols/mod.rs, clique/src/protocols/v1/mod.rs, clique/src/service.rs, clique/src/testing/clique_network.rs, finality-aleph/src/lib.rs, finality-aleph/src/metrics.rs, finality-aleph/src/nodes.rs
First part of the metrics cleanup, for now in the clique network.
=> A0-3058: Factor out clique metrics

finality-aleph/src/sync/service.rs, finality-aleph/src/sync/ticker.rs
These are changes that are needed to use ticker with the periodic requests for chain extensions which we will be implementing soon. In particular this _should not_ change any current behaviour of the node, thus it's just a refactor.
Comments on whether this interface is clear or not are very welcome.
=> A0-3083: Refactor ticker for chain extensions

aleph-client/src/contract/event.rs, aleph-client/src/utility.rs
- Exposing function needed in bridge guardian
- don't flood default logs
=> A0-3191: update aleph-client

aleph-client/src/connections.rs
Making some fields in the client public, needed by the guardian
=> A0-3191: make some fields public

Cargo.lock, aleph-client/Cargo.lock, bin/runtime/Cargo.toml, bin/runtime/src/lib.rs
See https://github.com/paritytech/substrate/pull/13250 for motivation.
=> A0-3128: Change to pub struct Runtime

.github/workflows/_check-vars-and-secrets.yml, .github/workflows/create-featurenet.yml, .github/workflows/delete-featurenet.yml, .github/workflows/nightly-short-session-e2e-tests.yml, .github/workflows/updatenet-create.yml, .github/workflows/updatenet-delete.yml, .github/workflows/updatenet-update.yml
This branch changes featurenet actions from v1 to v2 which introduces compatibility feature, which allows featurenet versioning.
=> A0-3223: Change featurenet actions to v2

finality-aleph/src/sync/data.rs
This message mostly confuses people and we never saw it bringing any joy, so lets hide it away a bit.
=> Lower loglevel for old sync messages

finality-aleph/src/sync/data.rs, finality-aleph/src/sync/forest/mod.rs, finality-aleph/src/sync/forest/vertex.rs, finality-aleph/src/sync/handler/mod.rs, finality-aleph/src/sync/handler/request_handler.rs, finality-aleph/src/sync/metrics.rs, finality-aleph/src/sync/mock/backend.rs, finality-aleph/src/sync/mock/mod.rs, finality-aleph/src/sync/mod.rs, finality-aleph/src/sync/service.rs, finality-aleph/src/sync/substrate/chain_status.rs, finality-aleph/src/sync/substrate/justification.rs, finality-aleph/src/sync/tasks.rs
Add periodic chain extension request to sync.
=> A0-3085: Add periodic extension request

finality-aleph/src/data_io/data_store.rs, finality-aleph/src/finalization.rs, finality-aleph/src/lib.rs, finality-aleph/src/network/mod.rs, finality-aleph/src/network/substrate.rs, finality-aleph/src/party/manager/data_store.rs, finality-aleph/src/party/manager/mod.rs, finality-aleph/src/sync/compatibility.rs, finality-aleph/src/sync/data.rs, finality-aleph/src/sync/forest/mod.rs, finality-aleph/src/sync/forest/vertex.rs, finality-aleph/src/sync/handler/mod.rs, finality-aleph/src/sync/handler/request_handler.rs, finality-aleph/src/sync/mock/backend.rs, finality-aleph/src/sync/mock/mod.rs, finality-aleph/src/sync/mod.rs, finality-aleph/src/sync/service.rs, finality-aleph/src/sync/substrate/chain_status.rs, finality-aleph/src/sync/substrate/mod.rs, finality-aleph/src/sync/tasks.rs, finality-aleph/src/testing/data_store.rs, finality-aleph/src/testing/mocks/block_finalizer.rs, finality-aleph/src/testing/mocks/mod.rs
Trait `BlockIdentifier` is removed, struct `BlockId` is used.
- Refactor
=> A0-3134: Remove BlockIdentifier

README.md
This small fix to not confuse community users in our main README.md 
=> A0-3290: Fix readme 

pallets/aleph/src/lib.rs, primitives/src/lib.rs
Removal of the committee change digest.
=> A0-3340: Remove committee change digest

pallets/aleph/src/lib.rs, primitives/src/lib.rs
Removal of the committee change digest.
=> A0-3340: Remove committee change digest (main)

finality-aleph/src/abft/current/mod.rs, finality-aleph/src/abft/current/network.rs, finality-aleph/src/abft/current/traits.rs, finality-aleph/src/block/mock/backend.rs, finality-aleph/src/block/mod.rs, finality-aleph/src/block/substrate/verification/cache.rs, finality-aleph/src/block/substrate/verification/mod.rs, finality-aleph/src/data_io/data_interpreter.rs, finality-aleph/src/data_io/data_provider.rs, finality-aleph/src/data_io/data_store.rs, finality-aleph/src/data_io/legacy/data_provider.rs, finality-aleph/src/data_io/legacy/mod.rs, finality-aleph/src/data_io/legacy/status_provider.rs, finality-aleph/src/data_io/mod.rs, finality-aleph/src/data_io/proposal.rs, finality-aleph/src/data_io/status_provider.rs, finality-aleph/src/lib.rs, finality-aleph/src/nodes.rs, finality-aleph/src/party/manager/mod.rs, finality-aleph/src/runtime_api.rs, finality-aleph/src/session_map.rs, finality-aleph/src/sync/handler/mod.rs, finality-aleph/src/sync/service.rs, finality-aleph/src/testing/data_store.rs, finality-aleph/src/testing/mocks/mod.rs, finality-aleph/src/testing/mocks/proposal.rs
Proposals now include headers.
=> A0-3390: Proposals with headers

finality-aleph/src/network/gossip/service.rs, finality-aleph/src/sync/service.rs
Logs!
Logs!
- logs
- logs
- l0g5
- Iogs
- lololgs
- lo~~gs
=> A0-3562: Slightly better logging in sync and gossip network

.github/workflows/featurenet-update.yml
Removes unncessary no-longer-required inputs from Featurenet Update workflow.
- I have run tests
=> A0-3221: Remove validators etc. inputs from FE update

pallets/vk-storage/src/lib.rs
When a user wants to store bytes in the `vk-storage` pallet, they are charged with two fees:
- operational one (computed based on benchmarks): `T::WeightInfo::store_key(key_len as u32)`
- (pallet) spam protection - additional artificial fee that is purely economical: `T::StorageCharge::get().charge_for(key_len)`
Previously, I specified the total fee within `#[pallet::weight(..)]` macro. As a consequence, the latter fee was included into the block space occupation. Since the charges are pretty high, we were exhausting block limit, effectively disabling the extrinsic.
The correct way to do this is to use `PostDispatchResultWithInfo`, where we can specify additional ('acutal') charge for an extrinsic. Such fee will be dynamically adjusted, and won't be statically included in the block weight …
=> A0-3855: Fix charging for vk storage

Cargo.lock
=> A0-3868: Dependabot

.github/workflows/weekly-sync-from-snapshot-testnet-pruned.yml, .github/workflows/weekly-sync-from-snapshot-testnet.yml
Adds almost empty workflows that should never run, but apparently will let me test the ones that I actually want to write.
Workaround
=> A0-2699: Add bogus workflows for testing

bin/runtime/src/lib.rs
It's a cherry pick on the release branch of an already merged PR.
=> A0-3970: Configure Call Filter for Call Runtime (cherry pick on release-13)

baby-liminal-extension/Cargo.lock, baby-liminal-extension/src/backend/weights.rs
Compilation error introduced in #1600. I forgot to add liminal-CI label there.
=> A0-3858: Fix liminal build

bin/runtime/src/lib.rs
This is a cherry-pick from main only. Increases the maximum size of contracts.
=> A0-3861:  Increase MaxCodeLen for contracts. (cherry-pick #1570)

aleph-client/src/aleph_zero.rs, aleph-client/src/aleph_zero_liminal.rs, pallets/feature-control/src/tests.rs
#1609 introduced a tiny bug that was revealed during nightly liminal integration test: https://github.com/Cardinal-Cryptography/aleph-node/commit/37daadd412e9b1a7336d993ce5338ef60f9d20bc/checks
https://github.com/Cardinal-Cryptography/aleph-node/actions/runs/7870008207
https://github.com/Cardinal-Cryptography/aleph-node/actions/runs/7870012597
=> A0-4035: Fix test compilation

Cargo.lock, bin/node/src/chain_spec.rs, bin/runtime/src/lib.rs, pallets/feature-control/Cargo.toml, pallets/feature-control/src/lib.rs
Fresh chain will have on-chain verifier enabled by default.
=> A0-4043: Add genesis config to the feature-control pallet

.github/workflows/nightly-integration-tests.yml, baby-liminal-extension/src/backend/tests.rs
Testing chain extension requires dedicated toolchain - copied steps from the PR flow.
https://github.com/Cardinal-Cryptography/aleph-node/actions/runs/7970662104
=> A0-4036: Fix nightly tests

finality-aleph/src/block/substrate/verification/cache.rs
In rare situations a block created in the same slot but different session was falsely marked as an equivocation, this PR fixes the problem. Cherry-picked from release-13.
=> A0-4100: [HOTFIX] Equivocations have to happen in the same session (cherrypick from release-13)

Cargo.lock
Update cargo.lock to include latest fixes from fork.
=> A0-4107: Update lock

scripts/accounts-invariants/pallet-balances-maintenance.py
Script for reading `consumers` underflow accounts
=> A0-4020: Script for reading underflow accounts

Cargo.lock, Cargo.toml, aleph-client/Cargo.lock, aleph-client/Cargo.toml, aleph-client/src/aleph_zero.rs, bin/runtime/Cargo.toml, bin/runtime/src/lib.rs, pallets/operations/Cargo.toml, pallets/operations/LICENSE, pallets/operations/README.md, pallets/operations/src/impls.rs, pallets/operations/src/lib.rs, pallets/operations/src/tests/mod.rs, pallets/operations/src/tests/setup.rs, pallets/operations/src/tests/suite.rs, pallets/operations/src/traits.rs, scripts/run_nodes.sh
This PR contains cps of below commits
The last one was done manually instead of cp/
=> A0-4020: Cherry-picks from 13 release

scripts/accounts-invariants/common.py, scripts/accounts-invariants/pallet-balances-maintenance.py
* added command to fix `consumers` overflow
* fixed logic which queries `consumers` underflow
https://github.com/Cardinal-Cryptography/aleph-node/pull/1643
=> A0-4020: Consider stash != controller in python script

bin/runtime/Cargo.toml, e2e-tests/src/test/fee.rs
* Fix for e2e test after adjustment of adaptive fee mechanism from 25% to 50%.
* fix for liminal integration tests build
Test passed: https://github.com/Cardinal-Cryptography/aleph-node/actions/runs/8341568094/job/22828318727
=> Fix fee calculation e2e test

Cargo.lock, aleph-client/Cargo.lock, bin/runtime/Cargo.toml, bin/runtime/src/lib.rs, e2e-tests/src/test/fee.rs, pallets/operations/Cargo.toml, pallets/operations/src/impls.rs, pallets/operations/src/lib.rs, pallets/operations/src/tests/setup.rs, pallets/operations/src/tests/suite.rs, pallets/operations/src/traits.rs
This PR cps below commits:
https://github.com/Cardinal-Cryptography/aleph-node/commit/2664b3bf23f8a3e83955c06d5ebf649ae48ce4aa
https://github.com/Cardinal-Cryptography/aleph-node/commit/f43fd9041c5e7006522335bb976cecacbd4c35bb
https://github.com/Cardinal-Cryptography/aleph-node/commit/3b21ef4d5dc2e4aab6030da7844b24d96d326d05
E2e pass: https://github.com/Cardinal-Cryptography/aleph-node/actions/runs/8356221052
=> A0-4020: Cherry-pick Testnet 13.2 hotfixes to main

Cargo.lock, Cargo.toml, finality-aleph/Cargo.toml, finality-aleph/src/base_protocol/config.rs, finality-aleph/src/base_protocol/mod.rs
Config creation for the base protocol, mostly dummy values, but this is what we want in our case. Not yet used, will have to be used in tandem with the network building.
=> A0-4295: Base protocol config creation

finality-aleph/src/sync/handler/mod.rs
Wide fork scenario test. It is described pretty in detail in the comments.
- Unit test
=> A0-2980: Wide fork scenario test

bin/node/src/service.rs, finality-aleph/src/lib.rs, finality-aleph/src/network/build/mod.rs, finality-aleph/src/network/mod.rs, finality-aleph/src/network/substrate.rs, finality-aleph/src/nodes.rs
=> A0-3576: Remove substrate sync

finality-aleph/src/network/base_protocol/service.rs
In particular this should make transaction dissemination work again.
=> L1-222: Send peer (dis)connect events from base protocol

.github/workflows/sync-from-snapshot-testnet-partidb.yml
Regression introduced in https://github.com/Cardinal-Cryptography/aleph-node/commit/7bce60a4b6ef9e2dfe984d37bf44acd6d61566e5
=> A0-4265: Fixed leftover workflow trigger condition

aggregator/src/aggregator.rs, clique/src/lib.rs, clique/src/service.rs, clique/src/testing/clique_network.rs, finality-aleph/src/abft/current/mod.rs, finality-aleph/src/abft/legacy/mod.rs, finality-aleph/src/abft/traits.rs, finality-aleph/src/network/data/component.rs, finality-aleph/src/network/data/split.rs, finality-aleph/src/network/substrate.rs, finality-aleph/src/party/manager/mod.rs, finality-aleph/src/party/manager/task.rs, finality-aleph/src/party/mod.rs, finality-aleph/src/sync/service.rs
Few small improvements around async/select-loops.
=> A0-2963: select-loop imprv

finality-aleph/src/network/base_protocol/config.rs
This should actually fix the problem with other protocols not connecting completely.
=> L1-222: Establish notification streams again

scripts/accounts-invariants/account_invariants.py, scripts/accounts-invariants/chain_operations.py, scripts/accounts-invariants/consumers_counter.py, scripts/accounts-invariants/contracts.py, scripts/accounts-invariants/pallet-balances-maintenance.py, scripts/accounts-invariants/utils.py
This PR is a companion for https://github.com/Cardinal-Cryptography/aleph-node/pull/1758 that contains the same logic changes for a pallet balances maintenance script. The script was refactored to a final form where it's composed into small or middle-size modules.
=> L1-66: Script changes for fixing consumers counter

aleph-client/src/aleph_zero.rs
Update metadata after change https://github.com/Cardinal-Cryptography/aleph-node/commit/f3db879e2a0c0e8df94521238fcf45790ecf9f35
[Nightly pipeline logic e2e tests](https://github.com/Cardinal-Cryptography/aleph-node/actions/runs/9542636060) - PASSED
=> L1-66: Update metadata

e2e-tests/src/test/fee.rs
The logging should now make it easier to see what went wrong – it not only adds logs about the received fees, but also distinguishes two previously identical failure messages.
=> L1-265: Better logging in the fee calculation test

aleph-client/src/aleph_zero.rs, aleph-client/src/pallets/treasury.rs, bin/runtime/src/lib.rs, e2e-tests/src/test/era_payout.rs, e2e-tests/src/test/treasury.rs, pallets/aleph/src/lib.rs, pallets/operations/src/tests/setup.rs, primitives/src/lib.rs
Introducing exponential inflation.
=> L1-282: Exponential inflation

.github/actions/run-e2e-test/action.yml, aleph-client/src/aleph_zero.rs, aleph-client/src/pallets/treasury.rs, bin/runtime/src/lib.rs, e2e-tests/src/test/era_payout.rs, e2e-tests/src/test/treasury.rs, pallets/aleph/src/lib.rs, pallets/operations/src/tests/setup.rs, primitives/src/lib.rs
Cherry-picking the new exponential inflation code from main. 
=> A0-0000: (L1-291) Exponential inflation

finality-aleph/src/sync/data.rs
Reverts Cardinal-Cryptography/aleph-node#1842 since we did it too early.
=> Revert "L1-9: Rm V3"

.github/workflows/sync-from-snapshot-mainnet-paritydb-pruned.yml, .github/workflows/sync-from-snapshot-mainnet-paritydb.yml, .github/workflows/sync-from-snapshot-mainnet.yml, .github/workflows/sync-from-snapshot-testnet-paritydb-pruned.yml, .github/workflows/sync-from-snapshot-testnet-paritydb.yml, .github/workflows/sync-from-snapshot-testnet.yml
=> Run snapshots test once per week

.github/workflows/sync-from-snapshot-mainnet-paritydb-pruned.yml, .github/workflows/sync-from-snapshot-mainnet-paritydb.yml, .github/workflows/sync-from-snapshot-mainnet.yml, .github/workflows/sync-from-snapshot-testnet-paritydb-pruned.yml, .github/workflows/sync-from-snapshot-testnet-paritydb.yml, .github/workflows/sync-from-snapshot-testnet.yml
=> Run snapshots tests only on weekends

.github/workflows/_check-vars-and-secrets.yml, .github/workflows/_update-node-image-infra.yml, .github/workflows/on-pull-request-commit.yml
Added signing commit mechanism to node image update workflow
- Workflow fix (non-breaking change which fixes an issue)
- I have made neccessary updates to the workflows
=> INFRA-92: add signing commits to workflow

finality-aleph/src/party/backup.rs
Cleanup after the update from ABFT 0.33.
cleanup
=> A0-4355: Remove obsolete non-async implementations

aleph-client/src/aleph_zero.rs, bin/runtime/src/lib.rs, e2e-tests/Cargo.lock, e2e-tests/src/elections.rs, pallets/aleph/src/impls.rs, pallets/committee-management/src/impls.rs, pallets/committee-management/src/lib.rs, pallets/committee-management/src/manager.rs, primitives/src/lib.rs
Calculate a performance stat for every finalizer at the end of a session and emit an event that a validator is underperforming when a threshold is met. In future, implement banning such validator.
=> A0-4577: Implement era abft performance calculation

finality-aleph/src/network/base_protocol/config.rs
Cherry pick of https://github.com/Cardinal-Cryptography/aleph-node/commit/24d2673118a32d1bcc10379443418118c12060a9
=> A0-0000: Fix for sync config (#1886)

finality-aleph/src/data_io/data_store.rs
We couldn't do that before, as substrate sync reacted poorly to many requests. Should help with the desync problems between versions 13 and 14 during updates.
=> A0-0000: Request missing blocks much more aggressively

finality-aleph/src/sync/service.rs
Strongly suggests older nodes to actually download our blocks.
=> A0-0000: Workaround for updating from version 13

finality-aleph/src/data_io/data_store.rs
Cherry pick of https://github.com/Cardinal-Cryptography/aleph-node/commit/ea1e23b6cd4d8ebec09184a46e39504c26a64235
=> A0-0000: Request missing blocks much more aggressively (#1890)

Cargo.lock, finality-aleph/Cargo.toml
Bump the version of ABFT to the one we want to use and fix the legacy aggregator dep as a bonus.
Version bump
=> A0-1672: Tidy up versions

finality-aleph/src/sync/data.rs
Remove unnecessary V3 sync messages. In good news, this should cut the network usage in 2 (kinda, not really).
Cleanup.
=> A0-4357: Rm V3 (#1842)

pallets/elections/src/impls.rs
=> A0-0000: Use parent hash as seed

bin/node/src/service.rs
This failed on the real chain, incl snapshots. Now it should never submit in practice.
=> A0-0000: Don't assume we have a score submission period

bin/runtime/src/lib.rs
On Mainnet and Testnet it is 18
=> Revert transaction_version to 18

clique/src/lib.rs, clique/src/manager/mod.rs, clique/src/protocols/mod.rs, clique/src/protocols/v1/mod.rs, clique/src/service.rs
Attempts at fixing the memory consumption in clique network. Current approach:
Limit number of messages to send in clique network
- Bug fix (non-breaking change which fixes an issue
=> A0-4817: Improve memory consumption in clique network

.github/workflows/_build-aleph-e2e-client.yml, .github/workflows/_build-and-push-cliain.yml, Cargo.lock, bin/node/Cargo.toml, clique/src/lib.rs, clique/src/manager/mod.rs, clique/src/protocols/mod.rs, clique/src/protocols/v1/mod.rs, clique/src/service.rs
Attempts at fixing the memory consumption in clique network. Current approach:
Limit number of messages to send in clique network
- Bug fix (non-breaking change which fixes an issue
=> A0-4817: Improve memory consumption in clique network (#1953)

.github/workflows/sync-from-snapshot-mainnet-paritydb-pruned.yml, .github/workflows/sync-from-snapshot-mainnet-rocksdb-pruned.yml, .github/workflows/sync-from-snapshot-mainnet.yml
This is how it should have always worked, since mainnet will be updated to the testnet version.
=> A0-4547: Run mainnet sync tests with testnet version

.github/workflows/featurenet-create.yml, .github/workflows/nightly-update-test-testnet-main.yml
=> A0-4612: Fix update net test from Testnet to main
