bin/node/src/cli.rs, bin/node/src/command.rs
For testnet keys were generated in chains/testnet1 directory instead of chains/a0tnet1. This is fixed now.
=> fixes chain id for which keys are generated

.github/workflows/deploy.yml, docker/Dockerfile
This fixes a bug which causes images to crash due to lack of execution permissions inside the docker container
=> fix permissions of the executable

bin/node/src/chain_spec.rs, bin/node/src/cli.rs, bin/node/src/command.rs, bin/runtime/src/lib.rs, pallet/src/lib.rs, primitives/src/lib.rs, run_nodes.sh
The parameters `SessionPeriod` (formerly `Period`) and `MillisecsPerBlock` no longer have to be known at compile time. Instead, you specify them if environment variables `SESSION_PERIOD` and `MILLISECS_PER_BLOCK`, respectively. If a variable is not set, a default value is used (5 for `SessionPeriod` and 4000 for `MilliSecsPerBlock`).
This PR also fixes the bug with incorrect generation of local keys. The bug was cause by the fact that when keys were supposed to be generated (and saved in the `/tmp/authorities_keys` file), an instance of `ChainSpec` is created. However, constructing a `ChainSpec` involves reading keys from `/tmp/authorities_keys`, and panics if that file does not exist. The bug is fixed by returning an empty list of keys instead of panicking in the described case. This …
=> Make constants `Period` and `MillisecsPerBlock` specified by environment variables

finality-aleph/src/justification.rs, finality-aleph/src/lib.rs, finality-aleph/src/party.rs
Now, when a node is catching up, it will not need to initialize consensus-related processes, just skip through the session right away.
=> Added early session-skip to finality-aleph.

run_nodes.sh
Fix the script to work with chain/node bootstrapping
Added an extra argument, which specifies the number of non validator nodes to run. These nodes will not be included in the list of validators in the chainspec, but will be helpful in testing committee changes.
=> A0-406: Fix script to work with bootstrapping and add non-validator nodes

.github/scripts/run_consensus.sh, .github/workflows/e2e-tests-main-devnet.yml
Check started failing after merging to main. This is because of #e1b0397 that wasn't part of the branch when merging.  
- session period is set to 5 (previous default) to fit the 2 sessions change within the 5 min limit on the tests run. 
- changed branch protection rules - branch needs to be up-to date (rebased on top of main) before it can be merged to avoid similar problems in the future
- had to remove ignored paths from e2e workflow because of a dumb GH requirement that a status check needs to be specified to activate this rule:
This means workflows will run after every change including changes to e.g README, but that is better than not being able to merge any changes to these paths or breaking main.
=> defaults are too long and CI times out

.github/workflows/push-foundation-repo.yml
I tested it here:
* workflow - https://github.com/Cardinal-Cryptography/aleph-node/runs/4187960088?check_suite_focus=true
* commit - https://github.com/Cardinal-Cryptography/aleph-node/commit/bba0b589d47c2786167ab00366065832accd1bd4
* foundation branch - https://github.com/aleph-zero-foundation/aleph-node/tree/AZ-62-add-sync-with-foundation-repo
=> AZ-62: Add synchronization workflow with foundation repository

benchmark/Dockerfile_prometheus, benchmark/README.md, benchmark/docker-compose.yml, benchmark/prometheus.yml, benchmark/provisioning/dashboards/AlephZero_Metrics.json, benchmark/provisioning/datasources/datasource.yml
- new grafana metrics: block creation time vs #txs
- support for node_exporter for collecting node's performance metrics
- support for multiple instances of docker-compose with grafana
=> updated grafana for benchmarks

finality-aleph/src/lib.rs, finality-aleph/src/new_network/mod.rs, finality-aleph/src/new_network/service.rs, finality-aleph/src/new_network/substrate.rs
This only rewrites some interfaces and implements them for the Substrate
network objects. The plan is to add more changes PR by PR, and the last
one will move new_network to network, and network to old_network. Both
will be initially supported in parallel, we will remove old_network
before the testnet update following the one when this goes live.
This is currently dead code, sorry. :/
It's also untested, since testing it would require mocking `Network`, and that would require creating much more abstraction (especially the `message_sender` method, that by itself is 3 layers). The next PR in this series will have lotsa tests tho, I promise!
=> AZ-107: New network first parts of implementation

finality-aleph/src/finalization.rs, finality-aleph/src/justification.rs, finality-aleph/src/party.rs
As suggested by @kostekIV, the previous `BlockSimplifier` trait was probably too rigorous and tendentious. This PR simplifies it, simultaneously making mocking easier.
=> Simplify BlockFinalizer trait

flooder/rust-toolchain.toml, flooder/src/config.rs, flooder/src/main.rs
- allows to skip accounts initialization
- allows to provide first index for the set of integer derived accounts, i.e. accounts derived from range x.. instead of the default 0.. range
- general refactor
=> AZ-383 fast accounts initialization for flooder

.github/workflows/e2e-tests-main-devnet.yml
An example of check failure: https://github.com/pmikolajczyk41/aleph-node/actions/runs/1612197667 (I have compiled the runtime with different compilers)
=> AZ-403: Verify deterministic runtime build

.github/workflows/build-node-and-runtime.yml
According to: https://docs.github.com/en/actions/learn-github-actions/reusing-workflows
It will be useful for AZ-408 (we will have to build things twice). Can be also used in unit-tests workflow.
=> Reusable build job

.github/workflows/deploy-mainnet.yml
The deployment job is placed within github mainnet environment, that requires pipeline to be accept before launch. It's an additional fuse in order to make sure that the deployment is indeed what the user wants to do.
=> Pipeline for mainnet deployment on release added

finality-aleph/src/data_io.rs, finality-aleph/src/lib.rs, finality-aleph/src/network.rs, finality-aleph/src/party/aggregator.rs, finality-aleph/src/party/authority.rs, finality-aleph/src/party/data_store.rs, finality-aleph/src/party/forwarder.rs, finality-aleph/src/party/member.rs, finality-aleph/src/party/mod.rs, finality-aleph/src/party/refresher.rs, finality-aleph/src/party/task.rs, finality-aleph/src/testing/network.rs
Also splits up party.rs a tad to make it more readable.
Main change is needed for a strange fail case of the new network, which shouldn't happen with proper usage when the committee actually changes, but right now would break everything. It is also actually useful in general, we want to restart if something breaks this way anyway.
=> AZ-107: Restart authority tasks if they fail

.github/workflows/e2e-tests-main-devnet.yml, bin/runtime/src/lib.rs
Exposes a function `hours_as_block_num :: u64 -> BlockNumber` that calculates the time period as the corresponding number of blocks, taking into account the `millis_per_block` parameter supplied when creating the chain.
=> AZ-579: refactor time constants to use the actual value of the `millis_per_block` param

docker/docker_entrypoint.sh, finality-aleph/src/aggregator.rs, finality-aleph/src/data_io/data_interpreter.rs, finality-aleph/src/data_io/data_provider.rs, finality-aleph/src/data_io/data_store.rs, finality-aleph/src/finalization.rs, finality-aleph/src/import.rs, finality-aleph/src/metrics.rs, finality-aleph/src/party/mod.rs, run_nodes.sh
Create new logging targets `aleph-data-store`, `aleph-finality`, and
`aleph-metrics`. Remove logging target `afa`.
Replace uses of logging targets:
* (18) `afa` -> `aleph-party`
* (11) `afa` -> `aleph-data-store`
* (10) `afa` -> `aleph-justification`
* (8) `afa` -> `aleph-finality`
* (2) `afa` -> `aleph-metrics`
=> AZ-569: Replace the afa logging target

finality-aleph/src/data_io/chain_info.rs, finality-aleph/src/data_io/data_store.rs, finality-aleph/src/data_io/status_provider.rs
Get rid of keeping track of highest imported block in the cached chain info provider. The information we get from client apparently is not enough to track this block correctly which resulted in a bug.
=> Highest caching bug

fork-off/Cargo.lock, fork-off/Cargo.toml, fork-off/README.md, fork-off/src/main.rs
Changes to the fork off tool:
-- One block is used as a reference point to download the state
-- The whole state is downloaded and only certain prefixes are replaced from the provided spec
-- The downloaded state is dumped to a file
-- There are workers that allow to parallelize downloading values.
=> Whole state is downloaded and the new spec is applied on top of it.

aleph-client/Cargo.lock, aleph-client/Cargo.toml, aleph-client/src/lib.rs, benches/payout-stakers/Cargo.lock, benches/payout-stakers/src/main.rs, bin/cliain/Cargo.lock, bin/cliain/src/lib.rs, bin/cliain/src/main.rs, e2e-tests/Cargo.lock, e2e-tests/src/config.rs, e2e-tests/src/test/finalization.rs, e2e-tests/src/test/staking.rs, e2e-tests/src/test/treasury.rs, e2e-tests/src/test/validators_change.rs, e2e-tests/src/transfer.rs, flooder/Cargo.lock, flooder/src/config.rs, flooder/src/main.rs, local-tests/send-runtime/Cargo.lock, local-tests/send-runtime/src/main.rs
After some suggestions, we make passing protocol (either `ws` or `wss`) implicit. This means that if you want to connect without ssl, you can either pass a bare address like `127.0.0.1:9943` or `ws://127.0.0.1:9943`. In order to use ssl, pass `wss://127.0.0.1:9943`.
=> Make protocol implicit

.github/actions/restore-cache/action.yml, .github/workflows/unit_tests.yml
Fixing `Unable to reserve cache with key X, another job may be creating this cache.`
Use one, versioned cache. This will hopefully fix any potential race conditions between different jobs and makes it easy to invalidate cache.
- [X ] Bug fix (non-breaking change which fixes an issue)
=> fix caching for unit tests workflow

docker-runtime-hook/entrypoint.sh
This PR prepares endpoint.sh script of the postsync hook for the feature environments. It let you set WS and RPC endpoint dynamically from the docker env block in the manifest.
=> Add parameter expansion to the hook endpoint

.github/workflows/deploy-to-devnet.yml
Fixes finalization stalled on devnet. Bootstrap command generates new keys (aura/aleph) if no keystore is present. These keys did not match the ones stored on S3, but were written to the chainspec and subsequently present in the fork genesis block.
In this fix we sync the keystore from S3, rename validator paths to the ones that `bootstrap` command expects and only then generate chainspec skeleton, preserving the validator keys.
=> make sure validator keys in chainspec match S3 keystore

aleph-client/Cargo.lock, aleph-client/Cargo.toml, aleph-client/src/lib.rs, benches/payout-stakers/Cargo.lock, benches/payout-stakers/Cargo.toml, benches/payout-stakers/src/main.rs, bin/cliain/Cargo.lock, docker/docker_entrypoint.sh, primitives/src/lib.rs
This change makes it convenient of using `payout_stakers` with `Aleph-Testnet` (ie, during AWS tests). One can pass now validators seeds, sudo seed, node address from AWS nodes into the `payout_stakers` bench like below, without recompiling binary:
```
RUST_LOG=aleph_e2e_client=info,aleph_client=info,payout_stakers=info,aleph-client=info cargo run --release -- --address 18.197.227.4:9944 --root-seed-file ../../../Aleph-Testnet/accounts/sudo_sk --validators-seed-file ../../../Aleph-Testnet/validator_phrases
```
The other commit in this PR increase `--db-cache` to 1024 (MB), now it is default value which is 128 (MB). There are several reasons to do it:
* 128 MB is small already, nowadays machines have much more RAM available,
* polkadot uses 1024 MB as default in newer substrate versions …
=> A0 824 db cache changes and make convinient using payout stakers bench in AWS tests

local-tests/chainrunner/chain.py, local-tests/chainrunner/node.py, local-tests/run_nodes.py
Small tweaks in Python chainrunner:
- make raw chainspec an option when boostraping the chain
- allow passing lists of values in set_flags
- improve on-the-fly log verbosity changing
- add address method to node
- make run_nodes.py use the same config flags as run_nodes.sh
=> Chainrunner tweaks

bin/runtime/src/lib.rs, e2e-tests/src/test/treasury.rs
For initial phase we don't want users to make proposals to the treasury and become exposed to slashing funds. Thus we increase the deposit value to an unachievable level.
=> Disable treasury proposals

.github/workflows/deploy-to-devnet.yml
We need a higher timeout just in case the devnet was down and the machines need to be spin up back again.
=> Increase timeout of devnet deployment.

.github/workflows/deploy-to-devnet.yml, bin/node/src/chain_spec.rs, bin/node/src/commands.rs, e2e-tests/Cargo.lock, fork-off/src/main.rs
This introduces a setup in which we have separate stash and controller accounts for local runs. The final effect is that _validator_, _stash_ and _controller_ are distinct accounts. The _e2e_ test setup remains unchanged with an implicit assumption that _validator_ == _stash_ == _controller_.
=> A0-596: Proper staking accounts setup for local runs

pallets/tendermint-light-client/src/mock.rs, pallets/tendermint-light-client/src/types.rs, pallets/tendermint-light-client/src/utils.rs
`AppHash` is upper hex-encoded string. We need to deserialize it as such.
=> Fix how we deserialize the `AppHash` type.

.github/workflows/e2e-tests-main-devnet.yml
Currently, all e2e tests have to be explicitly marked as required in the repository settings. This adds an empty job which depends on all the e2e tests for easier setup of required checks.
=> A0-913: One required task for e2e tests

.github/workflows/deploy-to-devnet.yml
Github actions has preinstalled jq. No need to install it here
=> Remove unneeded jq installer.

aleph-client/Cargo.lock, aleph-client/Cargo.toml, aleph-client/src/lib.rs, aleph-client/src/vesting.rs, benches/payout-stakers/Cargo.lock, bin/cliain/Cargo.lock, bin/cliain/src/lib.rs, bin/cliain/src/main.rs, bin/cliain/src/vesting.rs, e2e-tests/Cargo.lock, flooder/Cargo.lock
This PR introduces the vesting module to the aleph-client lib crate. It enables vesting (for self or on behalf), making vested transfers and managing vesting schedules. This is needed for implementing corresponding scenarios.
=> A0-873: Vesting module for `aleph-client`

finality-aleph/src/data_io/data_provider.rs
The test `proposal_changes_with_finalization` fails from time to time. This is probably due to changes in dev dependencies that make some of the testing code slower, and since it relies on some delays being not to small, it fails on slow machines. I increased the delay as a short-term solution. In the future we probably want to make `DataProvider` more asynchronous to not rely on refresh intervals etc.
Bug fix (non-breaking change which fixes an issue)
=> A0-925 Increase delay for better consistency in data_provider tests.

.github/workflows/deploy-to-devnet.yml, fork-off/Cargo.lock, fork-off/Cargo.toml, fork-off/README.md, fork-off/src/main.rs
Here we extend the configuration of `fork-off` tool, allowing to keep a part of some pallet storage from the initial chainspec.
=> A0-941: Allow keeping part of pallet storage from initial chainspec

finality-aleph/src/data_io/data_store.rs, finality-aleph/src/testing/data_store.rs
In case that after restart of many validator nodes, some of them did not have the most recent justification they would get stuck on proposals because of their parents being not finalized. This is fixed by requesting justifications in such a case. I also reduced some delays to make this kick in faster. 
=> A0-888: Request justification for blocks that must have been finalized

aleph-client/Cargo.lock, aleph-client/Cargo.toml, aleph-client/src/lib.rs, aleph-client/src/multisig.rs, aleph-client/src/vesting.rs, benches/payout-stakers/Cargo.lock, bin/cliain/Cargo.lock, e2e-tests/Cargo.lock, flooder/Cargo.lock
We introduce three minor changes to `aleph-client` library:
- `vesting::get_schedules` is fixed and its behavior is improved (unambiguous result)
- `AnyConnection` trait is also `Send`
- `SignedConnection::from_any_connection` takes a reference to `AnyConnection` instead of ownership - in `traffic-maker` every single usage required preserving original source connection and this 'proves' that the newer API is more useful
I would like to merge it soon and include these changes in a PR to `traffic-maker` for A0-1000.
=> Minor changes to `aleph-client` 

finality-aleph/src/data_io/data_interpreter.rs, finality-aleph/src/data_io/data_store.rs, finality-aleph/src/data_io/proposal.rs
Adds descriptive errors to proposal validation.
Closes https://cardinal-cryptography.atlassian.net/browse/A0-788
- Refactoring (non-breaking change)
=> A0-788: Add descriptive errors to proposal validation

local-tests/chainrunner/node.py, local-tests/test_update.ipynb, local-tests/test_update.py
- Removes `--pruning archive` flag from export state command in Python chainrunner (it started crashing if the chain was run without)
- Tries to speed up the finalization when stopping/starting chain
=> Fix runtime update test

docker/docker_entrypoint.sh, local-tests/run_nodes.py, local-tests/test_catch_up.py, local-tests/test_update.ipynb, local-tests/test_update.py, scripts/run_nodes.sh
After substrate update, pruning is no longer dependent on `--validator` flag (https://github.com/paritytech/substrate/commit/43d8c8787ded25dab5db55af5ab65f5d5882a51b#diff-a0791f65f4128fe45b6409b3ab1684d88ee9caaa916838d6c6786508b6c1d228R42) so we need to explicitly disable it by `--pruning archive`
=> Add pruning flag after substrate update

bin/runtime/src/lib.rs
Turns out 0 is the vaue we've been using
=> Change state version to 0

finality-aleph/src/network/manager/discovery.rs
Switched logging number of discovered authorities in network to info. Crucial for diagnostics in production.
=> A0-1092 logging number of discovered authorities at info

aleph-client/Cargo.lock, aleph-client/Cargo.toml, aleph-client/src/balances.rs, aleph-client/src/lib.rs, aleph-client/src/treasury.rs, benches/payout-stakers/Cargo.lock, bin/cliain/Cargo.lock, e2e-tests/Cargo.lock, e2e-tests/src/test/treasury.rs, flooder/Cargo.lock
Moved some functionalities from e2e to aleph-client. Local refactors.
Next steps (another PRs):
- [unify reading storage/constants in aleph-client](https://cardinal-cryptography.atlassian.net/browse/A0-1096)
- [extend cliain with treasury commands](https://cardinal-cryptography.atlassian.net/browse/A0-1098)
=> A0-1041: Treasury code cleanup

.github/workflows/build-node-and-runtime.yml, bin/node/Cargo.toml, bin/runtime/Cargo.toml, bin/runtime/src/lib.rs, e2e-tests/src/test/treasury.rs, scripts/run_local_e2e_pipeline.sh, scripts/run_nodes.sh
We introduce new feature flag to `aleph-node` and `aleph-runtime`: `treasury_proposals`:
- when it is **on** making proposal to the treasury has a constant price of 100 tokens
- when it is **off** making proposal to the treasury has a constant price of 10<sup>11</sup> tokens (which effectively disables proposals)
By default the feature is **off**. However, for local development and tests we switch it on. Hence, we could restore old e2e test verifying that `sudo` can maintain proposals (reject/approve).
- I have …
=> A0-1099: Conditionally enable treasury proposals

e2e-tests/src/test/rewards.rs
Tiny fix adding a `validators_change` call in the `force_new_era` e2e test for rewards.
=> Add validator change to force new era e2e test for rewards

scripts/set_code_substitute.py
Tool for extending chainspec with code-substitute.
I decided not to add it to `cliain` since it is very short and shouldn't require compiling whole tool, which is rather for interacting with chain.
=> A0-1146: Code substitute script

aleph-client/Cargo.lock, aleph-client/Cargo.toml, aleph-client/src/lib.rs, aleph-client/src/session.rs, bin/cliain/Cargo.lock, bin/cliain/Cargo.toml, bin/cliain/src/validators.rs, bin/runtime/src/lib.rs, e2e-tests/Cargo.lock, e2e-tests/src/rewards.rs, e2e-tests/src/test/era_validators.rs, e2e-tests/src/test/rewards.rs, e2e-tests/src/test/staking.rs, e2e-tests/src/test/validators_change.rs, e2e-tests/src/test/validators_rotate.rs, pallets/elections/src/impls.rs, pallets/elections/src/lib.rs, pallets/elections/src/migrations/mod.rs, pallets/elections/src/migrations/v1_to_v2.rs, pallets/elections/src/migrations/v2_to_v3.rs
Added support for rotating reserved nodes.
Migrations tested on local node with latest main and on testnet with try-runtime.
=> Rotating reserved nodes

.github/actions/slack-notification/action.yml, .github/workflows/deploy-mainnet.yml, .github/workflows/deploy-testnet.yml, .github/workflows/deploy-to-devnet.yml, .github/workflows/e2e-tests-contracts.yml, .github/workflows/e2e-tests-main-devnet.yml
1. Added new custom action for sending Slack notifications (`.github/actions/slack-notification`)
2. Triggered action mentioned above in these workflows:
- `.github/workflows/deploy-mainnet.yml` - always
- `.github/workflows/deploy-testnet.yml` - only on failure
- `.github/workflows/deploy-to-devnet.yml` - only on failure
- `.github/workflows/e2e-tests-contracts.yml` - only on failure
- `.github/workflows/e2e-tests-main-devnet.yml` - only on failure
=> A0-823: Slack notifications about workflow status

pallets/aleph/Cargo.toml, pallets/elections/Cargo.toml
We don't need both `license-file` and `license` in one toml file. 
=> Remove not needed license-files entries

bin/node/src/main.rs
Quick and a bit dirty fix for the fact that we don't support pruning. The value of the corresponding flag is forcefully set at the beginning of `main()`.
=> [A0-1141] Enforce disabled pruning

Cargo.lock, aleph-client/Cargo.lock, aleph-client/Cargo.toml, aleph-client/src/session.rs, benches/payout-stakers/Cargo.lock, bin/cliain/Cargo.lock, bin/cliain/Cargo.toml, bin/cliain/src/validators.rs, bin/node/src/chain_spec.rs, bin/runtime/src/lib.rs, e2e-tests/Cargo.lock, e2e-tests/src/rewards.rs, e2e-tests/src/test/electing_validators.rs, e2e-tests/src/test/era_validators.rs, e2e-tests/src/test/rewards.rs, e2e-tests/src/test/staking.rs, e2e-tests/src/test/validators_change.rs, e2e-tests/src/test/validators_rotate.rs, flooder/Cargo.lock, pallets/elections/Cargo.toml, pallets/elections/src/impls.rs, pallets/elections/src/lib.rs, pallets/elections/src/migrations/v2_to_v3.rs, pallets/elections/src/mock.rs, pallets/elections/src/tests.rs, primitives/Cargo.toml, primitives/src/lib.rs
This PR introduces two changes:
- we enable setting non-reserved seats for genesis build as well
- we initialize all the (reasonable) storage items in genesis build 
- I have bumped `spec_version`
=> A0-1175: Full genesis init for pallet elections

bin/node/src/cli.rs
Makes this:
```
$ target/release/aleph-node --version
aleph-node 0.7.0-fe1e38535e3
```
possible.
=> A0-1211: Add --version flag to aleph-node

contracts/game_token/lib.rs, contracts/scripts/deploy.sh
Implements https://cardinal-cryptography.atlassian.net/browse/A0-1259
=> A0-1259: Add metadata to PSP22 contracts

aleph-client/Cargo.lock, aleph-client/Cargo.toml, aleph-client/src/fee.rs, aleph-client/src/lib.rs, aleph-client/src/multisig.rs, aleph-client/src/session.rs, aleph-client/src/staking.rs, aleph-client/src/vesting.rs
Applies [the trait ADR](https://www.notion.so/cardinalcryptography/Basic-traits-derivation-and-field-access-for-public-structs-0aa22c4887024547b613db5754e0664a) to public types in aleph-client.
=> A0-1285: Implement common traits in aleph-client

aleph-client/Cargo.lock, benches/payout-stakers/Cargo.lock, bin/cliain/Cargo.lock, e2e-tests/Cargo.lock, flooder/Cargo.lock, scripts/update_substrate_git_branch.sh
This PR improves a bit `scripts/update_substrate_git_branch.sh` so that:
- it adheres to the recent bash ADR
- supports branches containing slash
- works for dependency defined as both `https://github.com/Cardinal-Cryptography/substrate` and `https://github.com/Cardinal-Cryptography/substrate.git` (recently we added 4 dependencies without `.git` suffix)
Additionally, some recent PRs didn't update some Cargo.locks, so I'm attaching new versions as well.
=> Improve script for updating substrate branch. Update Cargo.locks

.github/actions/restore-cache/action.yml
Changes the timeout for restore cache from the default of 1 hour to 10 minutes. It seems the action sometimes hangs during download and the way they solved it is with this timeout. 1 hour seems like much too much for the size of caches we generate (the biggest one is 1-2GB).
- Only changes github action config.
=> Reduce restore cache timeout

.github/actions/restore-cache/action.yml, .github/workflows/build-node-and-runtime.yml, .github/workflows/build-send-postsync-hook-runtime-image.yml, .github/workflows/check-excluded-packages.yml, .github/workflows/deploy-feature-envs.yaml, .github/workflows/deploy-mainnet.yml, .github/workflows/deploy-testnet.yml, .github/workflows/deploy-to-devnet.yml, .github/workflows/e2e-tests-main-devnet.yml, .github/workflows/nightly-pipeline.yaml, .github/workflows/push-foundation-repo.yml, .github/workflows/unit_tests.yml
In GitHub workflows, `ubuntu-latest` means `ubuntu-20.04` which is a bit confusing. That's for starters. 
In the future, GH might decide to change `ubuntu-latest` to `22.04`. Hence, it's safer to replace the `runs-on` value to `ubuntu-20.04` everywhere for visibility.
Documentation on the workers: https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources
=> A0-1382: Replace ubuntu-latest with ubuntu-20.04 in all the workflows

.github/actions/get-branch/action.yaml, .github/workflows/deploy-feature-envs.yaml
* Adds missing `env.` when getting value of environment value (fixes broken Deploy Feature Environment workflow)
* Makes `get-branch` action work with not only pull requests (the `github.head_ref` variable is available only for pull request event, in other cases `github.ref` should be used)
=> A0-1262: Fix invalid variable in deploy-feature-env workflow

.dockerignore, bin/cliain/.dockerignore, bin/cliain/Dockerfile, contracts/marketplace/lib.rs, contracts/scripts/clean.sh, contracts/scripts/deploy.sh
Script that terminates and removes all game contracts from chain
=> A0-1352: Add clean script

finality-aleph/src/crypto.rs
Minor additions to crypto abstractions which will be used by the validator network.
=> A0-1406: Add necessary crypto abstractions for validator network

contracts/scripts/deploy.sh
Changes to the deploy script that bring back the token names in their metadata
=> Fix deploy script

.github/workflows/build-and-push-cliain.yaml, bin/cliain/Dockerfile
Adds a github workflow that builds the cliain docker image and pushes it to ECR registry. 
In addition to that, few lines have been added to the Dockerfile from `benjamin` branch that add libssl 1.1.
=> A0-1449: Add workflow for building and pushing cliain docker image

finality-aleph/src/validator_network/handshake.rs, finality-aleph/src/validator_network/heartbeat.rs, finality-aleph/src/validator_network/mod.rs, finality-aleph/src/validator_network/protocols.rs
Note that the handshake is essentially a mock, there is a separate task for implementing it.
Add protocols for communication within the validator network, including a rudimentary handshake and a way to check the network stays alive.
=> A0-1408: Network protocols

.github/workflows/deploy-feature-envs.yaml
Two tweaks to deploy-feature-envs workflow:
* do not use fork-off when creating a chain
* remove DEPLOYED-CONTRACTS label
These changes are added to resolve conflict on the `benjamin` branch which are causing the workflow not running on the pull request
=> A0-1416: Tweak deploy-feature-envs workflow to not use forkoff

finality-aleph/src/network/manager/connections.rs, finality-aleph/src/network/manager/service.rs, finality-aleph/src/network/manager/session.rs, finality-aleph/src/network/mod.rs, finality-aleph/src/network/service.rs
Remove the requirement that `PeerId` is `Copy`. It's not strictly needed and we will soon be using ones that are not.
????
?!?
=> PeerId is no longer Copy

finality-aleph/src/network/mock.rs, finality-aleph/src/testing/mocks/mod.rs, finality-aleph/src/testing/mocks/validator_network.rs
This PR introduces mock implementation of validator network. This is the first PR in series of integrating validator network with aleph node.
- Mock implementation
=> A0-1410: add mock implementation of validator network

.github/scripts/run_smartnet.sh, contracts/scripts/deploy.sh, docker/smartnet-compose.yml
- fixes token names
- use docker networking and skip evil host mode
=> use docker network

.github/workflows/e2e-tests-contracts.yml, contracts/README.md, contracts/access_control/roles.rs, contracts/button/Cargo.lock, contracts/button/Cargo.toml, contracts/button/lib.rs, contracts/env/dev, contracts/game_token/Cargo.lock, contracts/game_token/Cargo.toml, contracts/game_token/lib.rs, contracts/marketplace/Cargo.lock, contracts/marketplace/Cargo.toml, contracts/marketplace/lib.rs, contracts/scripts/clean.sh, contracts/scripts/deploy.sh, contracts/scripts/test.sh, contracts/simple_dex/Cargo.toml, contracts/ticket_token/Cargo.lock, contracts/ticket_token/Cargo.toml, contracts/ticket_token/lib.rs, contracts/wrapped_azero/Cargo.lock, contracts/wrapped_azero/Cargo.toml, contracts/wrapped_azero/lib.rs
Turns on Mintable and Burnable extensions of PSP22 standard for game_token contracts. Reward tokens are now minted directly to user's account when `press` is called and burned from their account when spent on the marketplace.
=> A0-1236: Minting and burning reward tokens

contracts/button/errors.rs, contracts/button/lib.rs
Current round number is now kept by the contract, requested by the design team
=> Add round number

bin/cliain/src/keys.rs, bin/cliain/src/main.rs
Cliain: moving away from using `SignedConnection` when it is not needed (RPC calls).
=> Cliain: Move from SignedConnection to Connection in RPC calls

finality-aleph/src/justification/compatibility.rs, finality-aleph/src/network/manager/compatibility.rs
This removes `as` casting from compatibility code in `VersionedJustification` and `VersionedAuthentication`.
- Bug fix
=> A0-1478: Cleanup compatibility code

aleph-client/Cargo.lock, aleph-client/Cargo.toml, aleph-client/src/contract/mod.rs, aleph-client/src/contract/util.rs, aleph-client/src/lib.rs, e2e-tests/Cargo.lock
Adds utility code helpful for interacting with deployed contracts. See the end of this description for a usage example. I'm using the currently forbidden `pub mod` in this PR, please ignore for now, I'll make sure to either change that or argue for a change in the accepted practices before merging.
I went with a simplistic method of setting `MAX_GAS` and `MAX_READ_GAS`. Perhaps that's good enough for tests, but not good enough for merging into the client proper? Maybe it would be enough for now to set those in the contract constructor instead of having them constant?
- I have added tests - in a way - the code is not tested directly, but will be used in e2e-tests. However, that's still on a branch, so not part of this PR.
- I …
=> A0-1140: Add utils for contracts to aleph-client

aleph-client/Cargo.lock, aleph-client/Cargo.toml, aleph-client/src/contract/event.rs, aleph-client/src/contract/mod.rs, aleph-client/src/contract/util.rs, aleph-client/src/lib.rs, benches/payout-stakers/Cargo.lock, bin/cliain/Cargo.lock, e2e-tests/Cargo.lock, flooder/Cargo.lock
Adds utilities to `aleph_client` that allow for listening to events from multiple contracts.
This is part 2 of #665, so I'm targeting that branch, until that one gets merged, but I think you can already look at it and comment.
=> A0-1140: Contract event utils

bin/cliain/Dockerfile
Adding certificates to cliain docker image. This enables connecting with wss endpoints.
- Bug fix (?) (non-breaking change which fixes an issue)
=> Add certificats to cliain docker image

contracts/scripts/clean.sh, contracts/scripts/deploy.sh
- use new cliain command to check if contract even exists (avoids script hanging forever)
- log addresses at the end of deployment, because reasons
=> check if exists before removing

.github/actions/run-e2e-test/action.yml, .github/scripts/run_e2e_test.sh, .github/workflows/e2e-tests-main-devnet.yml, aleph-client/src/lib.rs, aleph-client/src/session.rs, aleph-client/src/version_upgrade.rs, e2e-tests/docker_entrypoint.sh, e2e-tests/src/cases.rs, e2e-tests/src/config.rs, e2e-tests/src/test/electing_validators.rs, e2e-tests/src/test/mod.rs, e2e-tests/src/test/version_upgrade.rs
Simple e2e-test for interaction with the new message-compatibility feature. It sets version-upgrade, awaits it, and verify if finalization is ok. WARNING: dummy/fake implementation of version message-compatibiliy should pass this test as well. Next there will be `negative` test verifying if an upgrade, where not enough nodes decides to switch version, will fail.
new e2e-test
=> simple e2e-test for message_compatibility and version upgrade

.github/workflows/contracts-e2e-tests-and-deploy.yaml
push has a limitation to `benjamin` branch only
=> Change contracts workflow to deploy only on push

Cargo.lock, bin/runtime/Cargo.toml, bin/runtime/src/chain_extension/snarcos-extension/lib.rs, bin/runtime/src/lib.rs, pallets/snarcos/Cargo.toml, pallets/snarcos/src/lib.rs, pallets/snarcos/src/systems.rs
This PR introduces Marlin system to `pallet_snarcos`.
Notes:
- `PairingEngine` config argument was removed (we use only one BLS curve across codebase and abstracting this at this moment just doesn't make sense)
- we have to implement `VerifyingSystem` for every system separately, because `ark_marlin::Marlin` doesn't implement `ark_snark::SNARK` (or more generally, there is no common snarkish trait for Groth16, Gm17 and Marlin)
=> Support Marlin system

contracts/access_control/traits.rs
=> just to trigger the deployment

.github/workflows/contracts-e2e-tests-and-deploy.yaml
=> edit condition

finality-aleph/src/validator_network/manager/direction.rs, finality-aleph/src/validator_network/manager/mod.rs, finality-aleph/src/validator_network/protocols/mod.rs, finality-aleph/src/validator_network/protocols/v1/mod.rs
Not used for now, that'll be in the next PR. This is PR 2/3. For more context still see #709 .
=> A0-1455: Add future protocol and decision process for connection direction

contracts/scripts/deploy.sh, contracts/simple_dex/lib.rs
* Adds `simple_dex` to `deploy.sh`
* Exposes `out_given_in` as a contract call, will be needed for frontend and e2e tests.
=> A0-1140: Deploy simple dex

finality-aleph/src/validator_network/manager/legacy.rs, finality-aleph/src/validator_network/manager/mod.rs, finality-aleph/src/validator_network/outgoing.rs, finality-aleph/src/validator_network/protocols/mod.rs, finality-aleph/src/validator_network/protocols/negotiation.rs, finality-aleph/src/validator_network/service.rs
Finally, this actually turns two-way connections on.
=> A0-1455: Enable two-way connections

finality-aleph/src/network/mock.rs, finality-aleph/src/network/mod.rs, finality-aleph/src/network/service.rs, finality-aleph/src/substrate_network.rs
Remove all the implementations that were necessary when we used the substrate network for inter-validator communication, but now are superfluous.
=> A0-1574: Remove unnecessary implementations in the substrate network

.github/workflows/check-excluded-packages.yml, Cargo.toml, contracts/access_control/lib.rs, contracts/button/lib.rs, contracts/game_token/lib.rs, contracts/marketplace/lib.rs, contracts/simple_dex/Cargo.lock, contracts/simple_dex/lib.rs, contracts/ticket_token/lib.rs, contracts/wrapped_azero/lib.rs
... so that they will be checked on CI.
I noticed that we only have `/contracts` listed as an excluded package. Running cargo commands in that directory makes them execute against `aleph-node` which is pointless. I listed all of the contracts explicitly and added `cargo test`, because we were not running unit tests for excluded packages either. I also fixed all the clippy issues in contracts.
=> List all contracts in excluded packages

finality-aleph/src/network/manager/discovery.rs, finality-aleph/src/network/manager/service.rs
We always send at most one discovery message at a time in many places, so make that official by making them a `Option` instead of `Vec`.
=> A0-1586: At most one discovery message

.github/workflows/contracts-e2e-tests-and-deploy.yaml, contracts/scripts/clean.sh, contracts/scripts/deploy.sh, contracts/wrapped_azero/lib.rs
- deploy wAzero to feature env
- fix deployment script
=> Deploy wazero

contracts/simple_dex/lib.rs, e2e-tests/src/test/button_game/contracts.rs, e2e-tests/src/test/button_game/mod.rs
Refactored out_given_in to be a pure query call
=> check liquidity in swaps only

contracts/blender/src/contract.rs
We introduce two new messages for:
- reading merkle path from specified leaf index
- checking whether a nullifier has been already used
=> Reading data from contract

finality-aleph/src/network/io.rs, finality-aleph/src/network/manager/compatibility.rs, finality-aleph/src/network/manager/discovery.rs, finality-aleph/src/network/manager/mod.rs, finality-aleph/src/network/manager/service.rs, finality-aleph/src/network/mock.rs, finality-aleph/src/network/mod.rs, finality-aleph/src/network/service.rs
Another refactor to make incoming changes to multiaddresses less painful. This one removes some abstraction layers that are no longer useful and somewhat decouples `network` from `network::manager` – we should probably decouple them more, but that's better left for another task.
=> A0-1591: Remove unnecessary abstraction layers in network

contracts/blender/src/contract.rs, pallets/snarcos/src/lib.rs
Remove `#[modifiers(only_owner)]` from `register_new_tokens` so that anyone can do it.
=> Remove `only_owner` access modifier from `register_new_tokens`

aleph-client/src/contract/mod.rs, contracts/scripts/deploy.sh, contracts/scripts/test.sh, e2e-tests/src/cases.rs, e2e-tests/src/config.rs, e2e-tests/src/test/button_game/contracts.rs, e2e-tests/src/test/button_game/helpers.rs, e2e-tests/src/test/button_game/mod.rs, e2e-tests/src/test/mod.rs
Added an e2e scenario for wrapped_azero.
=> A0-1140: e2e tests for wrapped_azero

finality-aleph/src/network/manager/compatibility.rs, finality-aleph/src/network/manager/connections.rs, finality-aleph/src/network/manager/discovery.rs, finality-aleph/src/network/manager/session.rs, finality-aleph/src/network/mock.rs, finality-aleph/src/network/service.rs, finality-aleph/src/testing/mocks/validator_network.rs, finality-aleph/src/testing/network.rs, finality-aleph/src/validator_network/manager/direction.rs, finality-aleph/src/validator_network/manager/legacy.rs, finality-aleph/src/validator_network/manager/mod.rs, finality-aleph/src/validator_network/mock.rs, finality-aleph/src/validator_network/protocols/handshake.rs, finality-aleph/src/validator_network/protocols/v0/mod.rs, finality-aleph/src/validator_network/protocols/v1/mod.rs
Now we only have one `MockMultiaddress`, which should make changes to `Multiaddress` be less cursed.
=> A0-1584: Unify MockMultiaddress

docker/Dockerfile.network_tests, docker/docker-compose.network_test.yml, docker/docker-compose.network_tests.yml, scripts/catchup_version_upgrade_test.sh, scripts/common.sh, scripts/run_consensus_network_delay.sh
simple bash script for simulating network delay (default is 500ms on each node). 500ms is enough on my machine to create a lot of confusion between nodes. Try setting `NETWORK_DELAY` env variable for your needs.
NOTICE: you might experience problems with docker due to `cap_add` flag in compose configuration. Use sudo or configure docker to allow using it (I am using rootless docker for it https://docs.docker.com/engine/security/rootless/). There is also a chance, that network device on your docker container is named differently (eth0 instead of eth1).
=> network delay

.github/workflows/e2e-tests-main-devnet.yml, Cargo.lock, bin/node/Cargo.toml, bin/node/src/aleph_cli.rs, bin/node/src/service.rs
Produce fewer blocks when finalization does not happen, configurable using a flag.
=> A0-1635: Limit nonfinalized block production

.github/workflows/e2e-tests-main-devnet.yml, Cargo.lock, bin/node/Cargo.toml, bin/node/src/aleph_cli.rs, bin/node/src/service.rs
* Limit nonfinalized block production
* Better saturation handling
* Add log when delaying block production
* Disable two tests that were operating under outdated assumptions
* Disable one more test
Cherry-pick from the main branch.
=> A0-1635: Limit nonfinalized block production (#769)

.github/workflows/e2e-tests-main-devnet.yml, Cargo.lock, bin/node/Cargo.toml, bin/node/src/aleph_cli.rs, bin/node/src/service.rs, bin/runtime/Cargo.toml, finality-aleph/Cargo.toml, finality-aleph/src/justification/handler.rs, finality-aleph/src/justification/mod.rs, finality-aleph/src/justification/requester.rs, finality-aleph/src/lib.rs, finality-aleph/src/nodes/mod.rs, finality-aleph/src/nodes/nonvalidator_node.rs, finality-aleph/src/nodes/validator_node.rs, finality-aleph/src/testing/justification.rs, finality-aleph/src/testing/mocks/backend.rs, finality-aleph/src/testing/mocks/justification_handler_config.rs, finality-aleph/src/testing/mocks/mod.rs
Following commands has been done:
```
git checkout release-8
git checkout -b port-8-X-Testnet-to-Mainnet
git merge release-8-mainnet # to pick up revert SCs change, resolved conflicts only in locks and toml files 
nvim bin/node/Cargo.toml # bump version to 0.8.2+mainnet
git commit -am "..."
git push -u origin HEAD
```
=> Port aleph-node 8.2 testnet to mainnet branch

Cargo.lock, bin/runtime/Cargo.toml, bin/runtime/src/lib.rs
This change is required as part of adding nomination pools to aleph-runtime. 
See https://github.com/paritytech/polkadot/pull/5924/files for more reference.
=> Added pending_rewards call to nomination pool api to our runtime

Cargo.lock, bin/runtime/Cargo.toml, bin/runtime/src/lib.rs
This is a slightly modified port of https://github.com/Cardinal-Cryptography/aleph-node/pull/778 to Testnet 8.X brach
Runtime `spec_version` is 44 which might sound controversial, but we need to use the first free number that is not used. This ie because spec_version needs to identify uniquely aleph-runtime, just in case of wrongly updated runtime on Tesnet or Mainnet.
=> Added pending_rewards API call to Testnet 8.X branch

bin/node/src/aleph_cli.rs, bin/node/src/main.rs
Add experimental_pruning flag for a testing purpose
=> Experimental pruning flag

bin/runtime/src/lib.rs
Part of runtime API responsible for pallet contracts calls has been removed by accident during the previous substrate update. This PR brings it back. Also, one pallet contracts constant is changed, following the change in substrate.
=> Bring back pallet contracts API to runtime

finality-aleph/src/network/io.rs, finality-aleph/src/network/manager/service.rs, finality-aleph/src/network/mock.rs, finality-aleph/src/network/mod.rs, finality-aleph/src/network/service.rs, finality-aleph/src/nodes/validator_node.rs, finality-aleph/src/testing/network.rs
* Moved Validator Network to ConnectionManagerIO
* Simplified tests in Network Service. They are no longer dependent on VersionedAuthentication
- Refactor/SImplification of code
- I have not added any tests, but they are not necessary
=> A0-1592: make connection manager operate of validator network directly

finality-aleph/src/network/mock.rs, finality-aleph/src/network/mod.rs, finality-aleph/src/network/service.rs, finality-aleph/src/substrate_network.rs
https://cardinal-cryptography.atlassian.net/browse/A0-1664
=> A0-1664 Stop exposing sync connected events from substrate network

bin/node/src/commands.rs, bin/runtime/src/lib.rs
base-path in PurgeBackup was clashing with base-path in the PurgeChain cmd causing shenanigans
=> fix clashing args in purge-chain cmd

e2e-tests/README.md, e2e-tests/docker_entrypoint.sh, e2e-tests/src/config.rs, scripts/run_e2e.sh
Takes all parts of the e2e config from the environment instead of using clap. When using `cargo test` to run the tests, this seems more natural. 
=> A0-1503: Take e2e config from env

finality-aleph/src/network/io.rs, finality-aleph/src/network/manager/compatibility.rs, finality-aleph/src/network/manager/discovery.rs, finality-aleph/src/network/manager/mod.rs, finality-aleph/src/network/manager/service.rs, finality-aleph/src/network/manager/session.rs, finality-aleph/src/network/mock.rs, finality-aleph/src/network/mod.rs, finality-aleph/src/tcp_network.rs, finality-aleph/src/testing/mocks/validator_network.rs, finality-aleph/src/testing/network.rs, finality-aleph/src/validator_network/manager/direction.rs, finality-aleph/src/validator_network/manager/legacy.rs, finality-aleph/src/validator_network/manager/mod.rs, finality-aleph/src/validator_network/mod.rs, finality-aleph/src/validator_network/outgoing.rs, finality-aleph/src/validator_network/service.rs
Makes the addressing information (formerly known as multiaddress) match the thing we are now using better and also just have a nicer interface. Unfortunately lots of changes were needed to make that happen.
Refactor.
=> A0-1575: Addressing information refactor

.github/workflows/build-node-and-runtime.yml
Implemented as suggested on the following GitHub Community discussion:
https://github.com/orgs/community/discussions/26726#discussioncomment-3253116
=> Add a condition for S3 steps to run only when AWS secrets are present

finality-aleph/src/validator_network/outgoing.rs
https://cardinal-cryptography.atlassian.net/browse/A0-1667
Currently the `TcpDialer` depends on OS timeouts, which are probably too long. We should wrap the `connect` call with a `timeout`.
=> A0-1667 Add timeouts to the dialer

finality-aleph/src/network/manager/service.rs
`to_retry` was kept before, to retry session start in case we did not know our own identity. Now we know it from the start and the only way session start can fail is if we changed session handler type. In this case we do not want to retry session start.
=> A0-1663: remove unnecessary session start retries in connection manager

Cargo.lock, bin/runtime/Cargo.toml, bin/runtime/src/lib.rs
- use `AllPalletsWithSystem::whitelisted_storage_keys`
- drop `extern crate`
=> Benchmark configuration cleanup

finality-aleph/src/lib.rs, finality-aleph/src/network/gossip/mock.rs, finality-aleph/src/network/gossip/mod.rs, finality-aleph/src/network/gossip/service.rs, finality-aleph/src/network/io.rs, finality-aleph/src/network/manager/service.rs, finality-aleph/src/network/mock.rs, finality-aleph/src/network/mod.rs, finality-aleph/src/network/substrate.rs, finality-aleph/src/nodes/validator_node.rs, finality-aleph/src/testing/network.rs
First part of the mentioned refactor, make the gossip network we had into a proper module. This is probably part 1/4 or something like that.
Refactor.
=> A0-1576: Make the gossip network into a module

finality-aleph/src/abft/current.rs, finality-aleph/src/abft/legacy.rs, finality-aleph/src/abft/network.rs, finality-aleph/src/aggregation/mod.rs, finality-aleph/src/data_io/data_store.rs, finality-aleph/src/lib.rs, finality-aleph/src/network/data/component.rs, finality-aleph/src/network/data/mod.rs, finality-aleph/src/network/data/split.rs, finality-aleph/src/network/mod.rs, finality-aleph/src/network/session.rs, finality-aleph/src/party/manager/aggregator.rs, finality-aleph/src/party/manager/data_store.rs, finality-aleph/src/party/manager/mod.rs, finality-aleph/src/testing/data_store.rs, finality-aleph/src/testing/network.rs
Another refactor of network, part 2/4(?).
Refactor.
=> A0-1576: Move data network into its own module

bin/cliain/Cargo.lock, bin/cliain/Cargo.toml, bin/cliain/src/commands.rs, bin/cliain/src/lib.rs, bin/cliain/src/main.rs, bin/cliain/src/snark_relations.rs, bin/cliain/src/snark_relations/io.rs, bin/cliain/src/snark_relations/mod.rs, bin/cliain/src/snark_relations/parsing.rs, bin/cliain/src/snark_relations/relations.rs, bin/cliain/src/snark_relations/systems.rs, relations/src/lib.rs
This PR moves the whole functionality of `house-snark` tool to `cliain`. Moreover, we add another command for off-chain proof verification.
=> A0-1696: `cliain` - support Liminal (2/2)

.github/scripts/run_smartnet.sh, .github/workflows/contracts-e2e-tests-and-deploy.yaml, contracts/scripts/deploy.sh, contracts/simple_dex/lib.rs, docker/smartnet-compose.yml, e2e-tests/src/test/button_game/contracts.rs, e2e-tests/src/test/button_game/mod.rs
- Add a query
- whitelist all possible pairs exchange contract deployment
=> Dex whitelist

docker/docker_entrypoint.sh
We forgot to add log target to docker entrypoint
=> Add clique network log target to docker entrypoint

finality-aleph/src/party/manager/mod.rs
Add some logs, since @DamianStraszak requested them.
=> Add logging about ABFT version

finality-aleph/src/network/gossip/mod.rs, finality-aleph/src/network/gossip/service.rs, finality-aleph/src/network/session/service.rs, finality-aleph/src/network/substrate.rs, finality-aleph/src/testing/network.rs
Make the gossip network return the peer id of the source of received data and add two, currently unused, methods to the interface – they will be used by block sync.
=> A0-1761: Enhance gossip network interface

finality-aleph/src/abft/current.rs, finality-aleph/src/abft/legacy.rs, finality-aleph/src/lib.rs, finality-aleph/src/party/manager/mod.rs, pallets/aleph/src/lib.rs, scripts/run_nodes.sh
Compatibility didn't work, because apparently no one checked?
=> Fixing broken compatibility

bin/node/src/service.rs, finality-aleph/src/lib.rs, finality-aleph/src/network/gossip/mod.rs, finality-aleph/src/network/gossip/service.rs, finality-aleph/src/network/mod.rs, finality-aleph/src/network/substrate.rs, finality-aleph/src/nodes/validator_node.rs, finality-aleph/src/testing/network.rs
This makes us follow the protocol naming convention outlined in https://github.com/paritytech/substrate/issues/7746. It also adds the block sync protocol, although currently unused – I wanted to make sure the abstraction will work with that.
=> A0-1491: Change protocol naming convention and add block sync protocol

relations/Cargo.lock, relations/Cargo.toml, relations/src/environment.rs, relations/src/lib.rs, relations/src/linear.rs, relations/src/merkle_tree/relation.rs, relations/src/merkle_tree/tree.rs, relations/src/relation.rs, relations/src/serialization.rs, relations/src/shielder/deposit.rs, relations/src/shielder/note.rs, relations/src/shielder/tangle.rs, relations/src/shielder/types.rs, relations/src/shielder/withdraw.rs, relations/src/utils.rs, relations/src/xor.rs
Enable using `relations` crate in `no-std` environment (like contract).
These two commands should succeed now:
```sh
cargo build
cargo build --no-default-features
```
=> Relations crate: `no_std`

finality-aleph/src/sync/mod.rs, finality-aleph/src/sync/substrate/mod.rs, finality-aleph/src/sync/substrate/state_notifier.rs, finality-aleph/src/sync/substrate/status_notifier.rs
Add substrate chain state notifier. Will be used for awaiting for next import/justification notification from substrate.
- New feature (not yet used)
=> A0-1822: add substrate chain status notifier

.github/workflows/contracts-e2e-tests-and-deploy.yaml
Calling workflow in the `indexer` repository has been replaced with `kubectl` commands. 
We explicitly restart indexer databases when deploying contracts (if addresses.json has changed then they are going to be wipe out). We do not do that when a new version of indexer is released (in the `indexer` repo). Hence, it is more meaningful to have it here (same as it is for `the-button`). 
Once this is merged, `kubectl` commands will be removed from `indexer`'s workflow.
=> A0-1459: Replace triggering workflow from indexer repo with kubectl cmds

aleph-client/Cargo.lock, aleph-client/Cargo.toml, aleph-client/src/connections.rs, aleph-client/src/lib.rs, bin/cliain/Cargo.lock
Adhere to the ADR (https://www.notion.so/cardinalcryptography/Module-based-access-in-our-codebase-2f0f0d6421c841ed889858b971850cb6). Moreover, enables downcasting connections outside (e.g. in `traffic-maker`)
=> Remove `pub(crate)` from `aleph-client`

bin/runtime/src/chain_extension/mod.rs, bin/runtime/src/chain_extension/tests/mod.rs, pallets/snarcos/src/lib.rs, pallets/snarcos/src/systems.rs, pallets/snarcos/src/tests/suite.rs
This PR introduces error enum for the verification process in pallet `snarcos`. It covers possible errors from `verify(..)` methods in `Groth16`, `GM17` and `Marlin` implementations from `arkworks`, i.e. 
- `SynthesisError` (for the former two) - here we have only two variants: `MalformedVerifyingKey` and `UnexpectedError`. The first one is just extraction of its counterpart in `SynthesisError`. The second one covers all other variants - they are dedicated for constraint synthesis or proof generation phases.
- `ark_marlin::Error<ark_poly_commit::Error>` (for the latter one) - here we unpack the `ark_marlin::Error` enum to either `AHPError` or `PolynomialCommitmentError`. In case `IndexTooLarge` happened, we fall back to `UnexpectedError` (this should never happen during verification …
=> A0-1540: Verification error

aleph-client/Cargo.lock, aleph-client/Cargo.toml, aleph-client/src/connections.rs, aleph-client/src/lib.rs, aleph-client/src/pallets/aleph.rs, aleph-client/src/pallets/balances.rs, aleph-client/src/pallets/contract.rs, aleph-client/src/pallets/elections.rs, aleph-client/src/pallets/multisig.rs, aleph-client/src/pallets/session.rs, aleph-client/src/pallets/staking.rs, aleph-client/src/pallets/system.rs, aleph-client/src/pallets/treasury.rs, aleph-client/src/pallets/utility.rs, aleph-client/src/pallets/vesting.rs, aleph-client/src/utility.rs, benches/payout-stakers/Cargo.lock, bin/cliain/Cargo.lock, bin/cliain/src/contracts.rs, e2e-tests/Cargo.lock, e2e-tests/src/test/fee.rs, flooder/Cargo.lock
This PR introduces two things:
- now all methods like `send_tx` return `TxInfo`, which currently is a simple struct containing `TxHash` and `BlockHash`
- there's a new method `get_tx_events` that returns `ExtrinsicEvents` struct
There's also an example of usage in e2e test (fee).
Supporting contract events (i.e. merging new utility with decoding) will be done in another, non-breaking 
Reasoning for `ExtrinsicEvents`:
- it is a `subxt`'s struct that already exposes handy API for filtering/extracting events; so it is ready to use so we don't have to provide our own, similar implementations
- `ExtrinsicEvents` has `pub(crate)` constructor, which is used in two places in `subxt`: `TxInBlock::fetch_events` and `Extrinsic::events`. The former one is kinda out of external usage, so we have to …
=> `aleph-client`: Get tx events

aleph-client/Cargo.lock, aleph-client/Cargo.toml, aleph-client/src/connections.rs, aleph-client/src/contract/event.rs, aleph-client/src/contract/mod.rs, aleph-client/src/lib.rs, benches/payout-stakers/Cargo.lock, bin/cliain/Cargo.lock, e2e-tests/Cargo.lock, e2e-tests/src/test/adder.rs, flooder/Cargo.lock
This PR introduces `get_contract_events` call which, similarly to `get_tx_events`, fetches all events that were emitted by a contract call and decodes them using metadata. This covers part of cases, when one had to use subscribing mechanism. 
One e2e test has been adapted to the new API.
=> `aleph-client`: Fetch contract events

finality-aleph/src/sync/mock/backend.rs, finality-aleph/src/sync/mock/mod.rs, finality-aleph/src/sync/mock/status_notifier.rs, finality-aleph/src/sync/mock/verifier.rs
=> A0-1824: add sync required mocks

.github/workflows/deploy-feature-envs.yaml
All feature env docker images should now use the public aleph-node repository, instead of the private one.
=> A0-1855: In FE, replace private feature-env-aleph-node repo with public aleph-node

bin/node/src/main.rs, bin/node/src/service.rs, finality-aleph/src/nodes/nonvalidator_node.rs, finality-aleph/src/nodes/validator_node.rs, finality-aleph/src/session_map.rs, finality-aleph/src/sync/substrate/verification/cache.rs
This PR add compatibility for running Aleph Node with pruning turned on. For now it stays as an experimental feature and because of that whenever using it, appropriate warning will be logged.
To use pruning one needs to provide `--experimental-pruning` parameter. When providing it, `--state-pruning` and `--blocks-pruning` can be set to possible values:
* `archive` - Keep all blocks/states
* `archive-canonical` - Keep only finalized blocks/states
* `number` -  Keep the last `number` of finalized blocks/states
For now `archive-canonical` setting does not work for state pruning. 
Default values are
* `--state-pruning=archive`
* `--blocks-pruning=archive-canonical`
Using experimental pruning should result in warning similar to:
```
WARN main aleph_node: Experimental_pruning was turned on. …
```
=> A0-1304: add state pruning compatibility

bin/runtime/src/lib.rs
PR 2/... for fixing Testnet migrations.
This was rather simple, just use the original migration (that does nothing apart from bumping `StorageVersion`)
See below log for test result
[try-runtime.log](https://github.com/Cardinal-Cryptography/aleph-node/files/10545903/try-runtime.log)
```
2023-01-31 11:41:25.426  INFO                 main runtime::multisig: [0] ✍️ Number of calls to refund and delete: 0    
```
Temporarily target branch is different as the original PR is not merged yet
=> A0-1910 Added migration for a multisig

bin/runtime/src/lib.rs, bin/runtime/src/migrations/custom_scheduler_migration.rs, bin/runtime/src/migrations/mod.rs
PR 3/... for fixing Testetn migrations. This time custom Scheduler migration to `StorageVersion` 3 with some asserts that the `Agendas` map is empty. There's no such original migration that can be used here.
[try-runtime.log](https://github.com/Cardinal-Cryptography/aleph-node/files/10546463/try-runtime.log)
```
2023-01-31 13:48:20.596  INFO main remote-ext: downloaded data for module Scheduler (count: 1 / prefix: 3db7a24cfdc9de785974746c14a99df9).    
...
2023-01-31 13:48:23.864  INFO                 main runtime::scheduler::migration: Migrated 0 agendas, bumped StorageVersion to V3    
```
=> A0-1910 Added migration for a Scheduler

relations/src/lib.rs, relations/src/shielder/circuit_utils.rs, relations/src/shielder/deposit.rs, relations/src/shielder/deposit_and_merge.rs, relations/src/shielder/mod.rs, relations/src/shielder/note.rs, relations/src/shielder/tangle.rs, relations/src/shielder/types.rs, relations/src/shielder/withdraw.rs
This PR fixes two things:
- tangling
- merkle path checking
The root problem was with in the tangling implementation. Two things here.
1. Tangling was really vulnerable to `0` in its input - once there were sufficiently many zero entries, the result was zero as well.
1. We were working on `ByteVar` (`Uint8<CircuitField>`) type, which is completely improper for arithmetic in a circuit. Although it doesn't expose calculation API (like `+` or `*`), it is not idiot-proof. We can still retrieve its underlying `u8` value with `.value()` method. **However, any operation on these values, doesn't have any impact on the circuit itself**. Unfortunately, this problem was hidden by the former point and thus we couldn't learn that something is no yes.
Similar bug was also present in the Merkle path …
=> A0-1916: Proper tangling and path verification

relations/src/shielder/circuit_utils.rs, relations/src/shielder/tangle.rs
When using `relations` as dependency of a `no_std` project (measuring performance of SNARKs in the browser), the following compilation errors were emitted (among others):
```sh
error[E0433]: failed to resolve: use of undeclared crate or module `std`
--> /home/mateusz/aleph/aleph-node/relations/src/shielder/tangle.rs:29:5
|
29 | use std::ops::Add;
|     ^^^ use of undeclared crate or module `std`
error[E0433]: failed to resolve: use of undeclared crate or module `std`
--> /home/mateusz/aleph/aleph-node/relations/src/shielder/circuit_utils.rs:4:5
|
4 | use std::ops::Index;
|     ^^^ use of undeclared crate or module `std`
```
switching to proper no std variants fixes the problem.
=> Use no_std variants in relations crate.

relations/src/proc_macro/src/code_generation.rs, relations/src/proc_macro/src/generation_utils.rs, relations/src/proc_macro/src/intermediate_representation.rs
1. Allows for no public inputs in a relation
2. We use `quote_spanned` instead of `quote` which might help a bit with compilation errors
Unblocks #907
=> A0-1951: Some macro fixes

.github/workflows/e2e-tests-main-devnet.yml, local-tests/run_nodes.py, local-tests/test_catch_up.py, local-tests/test_multiple_restarts.py
Test for nodes with pruning turned on.
Two new tests are added.
* catch up with state pruning 90 (short session is on)
* multiple restarts with state pruning 2048 (no short session)
Removed archive argument from tests (it does not need to be passed in normal usage).
Catch up tests waits for 90 finalized blocks, to check if pruning works.
Multiple restarts test waits for 256 finalized blocks, as default pruning setting for substrate is 256.
=> A0-1923: add e2e tests for pruning

.github/scripts/run_e2e_test.sh, .github/workflows/e2e-tests-main-devnet.yml
Fixes the wrong version on cargo-contract being installed on CI.
=> Fix a specific cargo-contract version on CI

bin/node/src/main.rs, bin/runtime/src/lib.rs
Increase total memory to 256MB, decrease call stack to 16 and enforce heap pages limit at cli.
- I have bumped `spec_version`
=> Enforce heap pages

Cargo.lock, aleph-client/Cargo.lock, aleph-client/Cargo.toml, aleph-client/src/aleph_zero.rs, benches/payout-stakers/Cargo.lock, benches/payout-stakers/Cargo.toml, bin/cliain/Cargo.lock, bin/cliain/Cargo.toml, bin/node/Cargo.toml, bin/runtime/Cargo.toml, bin/runtime/src/lib.rs, e2e-tests/Cargo.lock, e2e-tests/Cargo.toml, finality-aleph/Cargo.toml, finality-aleph/src/session_map.rs, flooder/Cargo.lock, flooder/Cargo.toml, fork-off/Cargo.lock, fork-off/Cargo.toml, pallets/aleph/Cargo.toml, pallets/elections/Cargo.toml, pallets/elections/src/impls.rs, pallets/support/Cargo.toml, primitives/Cargo.toml, scripts/synthetic-network/synthetic-link/Cargo.lock
=> update to v0.9.38

bin/runtime/src/lib.rs
Changes the storage fee for contracts to a lower value.
- I have not bumped `spec_version`, because there is no point in doing it on main anymore when we do that on release branches.
=> Make contract storage cheaper 

bin/node/src/main.rs, docker/docker_entrypoint.sh, scripts/run_nodes.sh
Now there is no need to pass `--state-pruning archive` as this is always overwritten. Without it it is possible to run docker image with experimental pruning
=> A0-1306: add posibility for experimental pruning in docker_entrypoint.sh

.github/scripts/run_smartnet.sh, .github/workflows/contracts-e2e-tests-and-deploy.yaml
I have a strong _deja-vu_ feeling of having edited this couple times already :)
=> only one workflow running ever

.github/workflows/build-and-push-cliain.yaml, .github/workflows/e2e-tests-main-devnet.yml, Cargo.lock, aleph-client/src/aleph_zero.rs, aleph-client/src/lib.rs, aleph-client/src/pallets/mod.rs, bin/node/Cargo.toml, bin/runtime/Cargo.toml, bin/runtime/src/lib.rs, bin/runtime/src/migrations/custom_staking_migrations.rs, bin/runtime/src/migrations/mod.rs, e2e-tests/Cargo.lock, e2e-tests/src/test/mod.rs
* bumping `aleph-node` version,
* removing pallet contracts from runtime (note this is Release 9 and _not_ 10; as per https://alephzero.org/blog/aleph-zero-testnet-update-ink-smart-contracts-storage-fees/)
* migrations for pallet staking - just setting storage version to V12
* migrations for nomination pools to V3. Note that on the current Mainnet (8.4), there is no storage version set for nomination pools, but real storage version on chain is V2.
- Testing done:  [try-runtime.log](https://github.com/Cardinal-Cryptography/aleph-node/files/10895707/try-runtime.log)
=> Preparation for Mainnet 9.0 release

.github/workflows/skip-check-excluded-packages.yml, .github/workflows/skip-e2e-tests-main-devnet.yml, .github/workflows/skip-unit_tests.yml, .github/workflows/skip-yaml-lint.yml
In repository settings, we require certain statuses to be reported as succeeded.  These come from our workflows.  However, some of our workflows have `paths` configured.  Thus, they're not getting triggered and we end up in a situation where PR is stuck with a required status of Pending.  
As a solution, suggested by GitHub, we shall add additional workflows doing nothing but returning exit code of 0, with the same name, with `paths-ignored` set to `paths` from the original workflows (so it's invertion).
=> Add skip-workflows for required checks that have to succeed

contracts/scripts/test.sh
It should now work with nodes started with `.github/scripts/run_consensus.sh` out of the box, as described in the comment in the file.
=> Dockerize contracts/scripts/test.sh

.github/workflows/e2e-tests-main-devnet.yml, aleph-client/Cargo.lock, aleph-client/Cargo.toml, bin/cliain/Cargo.lock, bin/cliain/Cargo.toml, bin/cliain/src/contracts.rs, contracts/access_control/Cargo.lock, contracts/access_control/Cargo.toml, contracts/adder/Cargo.toml, contracts/button/Cargo.lock, contracts/button/Cargo.toml, contracts/button/lib.rs, contracts/game_token/Cargo.lock, contracts/game_token/Cargo.toml, contracts/marketplace/Cargo.lock, contracts/marketplace/Cargo.toml, contracts/marketplace/lib.rs, contracts/simple_dex/Cargo.lock, contracts/simple_dex/Cargo.toml, contracts/simple_dex/lib.rs, contracts/ticket_token/Cargo.lock, contracts/ticket_token/Cargo.toml, contracts/wrapped_azero/Cargo.lock, contracts/wrapped_azero/Cargo.toml
Updates all ink dependencies to ink4 stables.
The only exception being `contract-transcode` which is now set to custom branch in my repository. The reason why we can't use `contract-transcode = "2.0.2"` is the incompatibility between `sp-core` in that crate and `sp-core` in our branch substrate deps on `aleph-v0.9.38` branch (wasmtime deps differ - 6.0.0. vs 1.0.X) that causes linking errors during compilation. There's a [PR opened](https://github.com/paritytech/cargo-contract/pull/1010) that removes `sp-*` dependencies from `contract-transcode` but we have to wait until it's merged (and `contract-transcode` released) to ditch the custom fork.
=> [A0-2073] Update contracts to =4.0.1 ink.

.github/actions/get-branch/action.yaml, .github/workflows/build-send-postsync-hook-runtime-image.yml, .github/workflows/check-excluded-packages.yml, .github/workflows/e2e-tests-main-devnet.yml
https://cardinal-cryptography.atlassian.net/browse/A0-2096
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
Replacing soon-to-be deprecated `set-output` with `GITHUB_OUTPUT`.
=> Use `GITHUB_OUTPUT` instead of `set-output` in github workflows

e2e-tests/src/test/button_game/mod.rs
This should make the contract tests less flaky. The main improvement is making the time to wait with the second press dependent on how long it took to press the first time - on CI this time can vary a lot, I've seen even ~20s between a `Reset` and a `ButtonPressed`.
=> Improve flaky contract tests

finality-aleph/src/lib.rs, finality-aleph/src/nodes/mod.rs, finality-aleph/src/nodes/nonvalidator_node.rs, finality-aleph/src/nodes/validator_node.rs, finality-aleph/src/party/impls.rs, finality-aleph/src/party/mocks.rs, finality-aleph/src/party/mod.rs, finality-aleph/src/party/traits.rs, finality-aleph/src/session.rs, finality-aleph/src/session_map.rs, finality-aleph/src/sync/handler.rs, finality-aleph/src/sync/substrate/verification/cache.rs, finality-aleph/src/testing/mocks/session_info.rs
Previously session info was either taken from implementations of `SessionInfo` trait, or functions that were inside this trait. Now the functions are private, and session info is taken from `SessionInfo` struct. 
`SessionBoundries` struct and `AuthorityProvider` trait will be refactored in another PR to not be generic over `B: Block`
- Refactor
=> A0-1876: refactor session info

.github/workflows/nightly-pipeline.yaml
Steps with `cargo` fail because of sccache not present.  To get it fixed, let's just get them running on our runners. 
A sample failed run:
https://github.com/Cardinal-Cryptography/aleph-node/actions/runs/4399876971/jobs/7704710711 
could not execute process `sccache rustc
=> Change nightly-pipeline steps with 'cargo' to use 'self-hosted' runner

.github/actions/destroy-feature-environment/action.yml, .github/workflows/build-send-postsync-hook-runtime-image.yml, .github/workflows/deploy-feature-envs.yaml, .github/workflows/deploy-mainnet.yml, .github/workflows/deploy-testnet.yml, .github/workflows/deploy-to-devnet.yml
This PR updates EndBug/add-and-commit action from version 5.1.0 to 9.1.1, as suggested by Dependabot on https://github.com/Cardinal-Cryptography/aleph-node/pull/980.
It's quite a bump so changelog has been checked and there are breaking changes in version 7.0.0: https://github.com/EndBug/add-and-commit/releases/tag/v7.0.0 
A major breaking change is the token input that has been removed.  That token will be now taken from the previously used `actions/checkout@v3` action.  Thus, if a repository `aleph-apps` is checked out in `aleph-apps` directory, our `add-and-commit` action can be used on that directory without passing the token.
New version has been tested on some temporary branches:  
* the following workflow has been created on a temporary branch: …
=> A0-2102: Bump EndBug/add-and-commit GH action version from 5.1.0 to 9.1.1

Cargo.lock, pallets/baby-liminal/Cargo.toml, poseidon/Cargo.toml
This reverts commit a286bdeb749504fa0da6519f5f275d2bbc618c3c.
Cannot actually update that until https://github.com/arkworks-rs/gm17/pull/16 is merged.
=> Revert "Bump ark-r1cs-std from 0.3.1 to 0.4.0 (#1005)"

.github/workflows/yaml-validate.yml
New version checks for calls to invalid variables like `${{ something }}` (only `${{ false }}` and `${{ true }}` are allowed).
=> A0-2112: Bump gh workflows validator from 0.1.0 to 0.2.0

.github/dependabot.yml
* Dependabot should raise PRs only on Sunday to not interfere with ppl work
* Dpendabot should not update PRs automatically. Especially on Mondays it auto bump PRs when someone merges to `main`, this is waste of our custom runners time 
=> Make dependabot to work on Sundays and do not update PRs automatically

Cargo.lock, bin/cliain/Cargo.lock, poseidon/Cargo.toml, poseidon/src/circuit.rs, poseidon/src/generate_parameters.rs, poseidon/src/hash.rs, poseidon/src/parameters.rs, relations/Cargo.lock
Change `poseidon` dependencies from git-based to crates.io.
=> Update poseidon dependencies

finality-aleph/src/nodes/nonvalidator_node.rs, finality-aleph/src/nodes/validator_node.rs, finality-aleph/src/session_map.rs, finality-aleph/src/sync/substrate/verification/cache.rs, finality-aleph/src/sync/substrate/verification/mod.rs
Refactor `AuthorityProvider` and `FinalityNotificator` not to be generic over `B: Block`. In result also `SessiomMapUpdater` no longer is generic over `B: Block`
Refactor
=> A0-2098: refactor AuthorityProvider, FinalityNotificator and SessionMapUpdater

default.nix, nix/nix-build.sh, nix/versions.nix
bumped version of rust-toolchain in nix/versions.nix. Previous version was responsible for failing the docker-based build procedure.
https://github.com/Cardinal-Cryptography/aleph-node/issues/1052
hot-fix
```bash
sudo docker build -t aleph-build -f nix/Dockerfile.build .
sudo docker run -ti --volume=$(pwd):/node/build aleph-build
```
Result should be stored at `$(project_dir)/result/`.
=> bumped rust to `nightly-2022-10-30` in nix/versions.nix

.github/workflows/_build-test-node-and-e2e-client-image.yml, .github/workflows/_check-runtime-determimism.yml, .github/workflows/deploy-feature-envs.yaml, .github/workflows/on-main-or-release-branch-commit.yml, .github/workflows/on-pull-request-commit.yml
_With v2 and v3, when an artifact is specified by the name input, there is no longer an extra directory that is created if the path input is not provided. All the contents are downloaded to the current working directory._
We update from v2 to v3 so all these should be fine.  I have reviewed all entries.  Note that, few entries are left with v2 because they are updated within another PR for nightly-pipeline.  I do not want to get any merge conflicts.
=> A0-2175: Bump version of download-artifact version from 2 to 3

.github/workflows/_check-excluded-packages.yml
We are using our own fork of `cargo-nono` with updated dependencies.
=> A0-2134: Use our fork of nono

.github/actions/get-ref-properties/action.yml, .github/workflows/deploy-to-mainnet.yml, .github/workflows/deploy-to-testnet.yml, .github/workflows/nightly-pipeline.yaml
* Use `get-ref-properties` in mainnet and testnet workflows 
=> A0-2206: Use get-ref-properties in deploy to mainnet and testnet workflows

contracts/button/lib.rs, e2e-tests/src/test/button_game/mod.rs
This should fix the most common cause of flakiness for these tests, that is when the two presses we compare occur at roughly equal intervals, giving equal scores instead of one or the other being bigger. It also fixes two other issues:
1. For `the_pressiah_cometh` it's the order of the presses that matters, not the times.
2. When resetting the button, there might be extra tickets in the button from other tests, this is now taken into account.
=> A0-2187: Improve button e2e tests

finality-aleph/src/sync/substrate/translator.rs
Basically remove `Error::AlreadyJustified`, as it’s not an error.
The duplicate justification should simply be handled (ignored) by the `Forest`.
=> A0-2267: Translator should not fail on already existing justification

finality-aleph/src/sync/forest/mod.rs, finality-aleph/src/sync/handler.rs, finality-aleph/src/sync/mock/backend.rs, finality-aleph/src/sync/mock/mod.rs, finality-aleph/src/sync/mod.rs, finality-aleph/src/sync/service.rs, finality-aleph/src/sync/substrate/mod.rs, finality-aleph/src/sync/substrate/status_notifier.rs, finality-aleph/src/sync/substrate/translator.rs
Some leftover changes in the `sync` module needed after we found some problems during testing and figured out which parts of the code weren't actually used (thanks compiler). Some more detailed changes:
* simplified the logic of "highest_justified" in forest
* better detection and handling of genesis blocks
* more requirements in some traits that turn out to be necessary in practice
* more logs
* more patient stall detection
* additional user justifications (a workaround needed until we have our own block sync)
=> A0-2273: Various remaining improvements to sync

.github/actions/build-featurenet-chainspec/action.yml, .github/actions/create-featurenet/action.yml, .github/actions/delete-featurenet/action.yml, .github/actions/get-ref-properties/action.yml, .github/workflows/_build-and-push-pull-request-image-to-featurenets.yml, .github/workflows/create-featurenet.yml, .github/workflows/deploy-feature-envs.yml, .github/workflows/on-pull-request-featurenet-labels.yml
Changes:
- everything apart from argocd apps and s3 buckets is now renamed from `feature env` to `featurenet` to make it consistent with other -nets and ADR about environments
- instead of `deploy` and `destroy` verbs, we have `create` and `delete`
- both creating (with updating which essentially almost the same) and deleting are now extracted to actions
- building chainspec is extracted to a separate action as well
- previously there was some inconsistency between s3 bucket name and argocd app name that led to featurenet not working in some cases - this is now fixed
- workflow name has been changed from `deploy-feature-envs` to `on-pull-request-featurenet-labels`
- label names are changed to the ones agreed in the naming convention ADR
- `branch-name-for-argo` output of …
=> A0-2207: Re-factor featurenet workflows

aleph-client/Cargo.toml, aleph-client/src/contract/mod.rs, bin/cliain/Cargo.lock, e2e-tests/Cargo.lock, e2e-tests/src/test/adder.rs
`aleph-client` shouldn't submit a contract call after dry-run failure.
=> A0-2287: Don't submit call after dry-run failure

bin/runtime/src/lib.rs
It should not be possible to send tx from the zero address, This is possible on AZERO because of   https://substrate.stackexchange.com/questions/982/why-does-the-all-0-public-key-have-a-known-private-key-in-sr25519-and-ed25519
This PR adds a signed extension that rejects such transactions.
=> A0-2357: Add the CheckNonZeroSender extension.

aleph-client/Cargo.lock, aleph-client/Cargo.toml, aleph-client/src/lib.rs, aleph-client/src/pallets/treasury.rs, bin/cliain/Cargo.lock, e2e-tests/Cargo.lock
We restore dependency on `primitives` in `aleph-client`, rollbacking some of the changes from #1130.
I've added full export for `primitives` as well, so that all types and constants are visible further, but if someone is against star-export, I'm open to change it.
- Rollback
=> A0-2424: Restore dependency on primitives

finality-aleph/src/data_io/chain_info.rs, finality-aleph/src/data_io/data_interpreter.rs, finality-aleph/src/data_io/data_provider.rs, finality-aleph/src/data_io/data_store.rs, finality-aleph/src/data_io/proposal.rs
Replaces last uses of `NumberFor` (in the `data_io` module) with `BlockNumber`. 
Refactor
=> A0-2442: Remove last traces of `NumberFor`

bin/node/src/aleph_node_rpc.rs, bin/node/src/rpc.rs, bin/node/src/service.rs
Aleph Node Rpc does not need to be dependent on `B: Block`. This replaces and is heavily based on #1102, which got sufficiently obsoleted by other changes that it was simpler to write it from scratch.
Refactor
=> A0-2240: Refactor aleph node RPC

.github/workflows/_update-node-image-infra.yml
Cherry-pick of 66d20a2a (https://github.com/Cardinal-Cryptography/aleph-node/pull/1168).
=> A0-1816: Fix Testnet and Mainnet deployments to reflect GitHub environments (#1168) - cherry pick on Release 11

.github/workflows/on-main-or-release-branch-commit.yml, .github/workflows/on-release-branch-commit.yml
* always notify dev-onduty slack channel when there is a push to a release branch and build finishes, as opposed to a current behavior in which only failures are reported. On main branch though, logic remains the same to not spam dev-onduty channel per every commit to main.
* fix workflow that compares workflows among `main` and release branches to exclude e2e workflow from comparison
=> A0-2516: Always notify dev-onduty slack channel when there is a push to a release branch and build finishes

finality-aleph/src/import.rs
If a block comes from major sync we pretend that it actually came from normal sync when importing it.
=> A0-2517: Treat blocks from major sync the same as others

finality-aleph/src/import.rs
* Treat blocks from major sync the same as others
Cherry picked from the release branch.
=> A0-2517: Treat blocks from major sync the same as others (#1192)

finality-aleph/src/import.rs, finality-aleph/src/nodes.rs, finality-aleph/src/sync/service.rs, finality-aleph/src/sync/substrate/chain_status.rs, finality-aleph/src/sync/substrate/status_notifier.rs
Now reports more blocks if it missed them. Also slows down major sync on purpose to make this actually work reasonably.
=> A0-2517: Other major sync solution

Cargo.lock, Cargo.toml, aleph-client/Cargo.lock, bin/cliain/Cargo.lock, e2e-tests/Cargo.lock, poseidon/Cargo.lock, poseidon/Cargo.toml
Poseidon is no longer used in node and thus is not needed in the workspace.
=> A0-2494: Exclude poseidon from workspace

e2e-tests/Cargo.lock, pallets/elections/src/impls.rs
We should be using `Pcg32` everywhere.
=> A0-2584: Use Pcg32 in all pallets

finality-aleph/src/abft/common.rs, finality-aleph/src/abft/current.rs, finality-aleph/src/abft/legacy.rs, scripts/run_nodes.sh
Note that the cherrypick for A0-2571 has already been done in https://github.com/Cardinal-Cryptography/aleph-node/pull/1221 
This is only :
- cleaning up dead code that was the main reason for this bug to appear
- adding a sanity check that will save us from a similar mistake in the future
=> A0-2571: Sanity check for minimum session duration.

aleph-client/src/pallets/aleph.rs, bin/finalizer/Cargo.lock, bin/node/src/aleph_node_rpc.rs, e2e-tests/Cargo.lock
When an RPC arg is `Vec<u8>` it is incorrectly decoded by PolkadotJS UI.
We should use `sp_core::Bytes` as every Substrate RPC endpoint (see e.g. `queryFeeDetails`).
No. Thus I changed the justification encoding part in `aleph_client`, on which `finalizer` and `cliain` depend on. 
Locally tested:
1. `./scripts/run_nodes.sh`
1. `cargo run -- set-emergency-finalizer --finalizer-seed //Alice` in `cliain`
1. wait for a session/two
1. kill two nodes
1. in `finalizer`: `cargo run --release try-finalize --how-many 10`
1. in `cliain`: `cargo run --release -- --node ws://127.0.0.1:9944 finalize --hash 0x0525531b89b949f999d5822b37b55837a323854205cc3780e8c9695a9d796ff4 --block 61  --finalizer-seed //Alice`
1. in UI (to be published):
=> A0-2609: RPC: use `sp_core::Bytes` instead of `Vec<u8>`

.github/workflows/on-pull-request-commit.yml
Surprisingly GitHub treats skipped jobs status as success, despite those skipped jobs are Required Checks. With the introduction of Merge Queues, this has a danger to sneak in a change that fails one of e2e tests. See all compiled info in this [answer](https://github.com/orgs/community/discussions/46757#discussioncomment-5831752)
* Tested this change in testing repo https://github.com/gen64/repo-for-testing/pull/28/files
=> A0-2541: Manually check dependat job statuses in check e2e job completion

.github/actions/create-featurenet/action.yml, .github/workflows/_build-liminal-node.yml, .github/workflows/_build-production-node-and-e2e-client-image.yml, .github/workflows/_build-production-node-and-runtime.yml, .github/workflows/_build-test-node-and-e2e-client-image.yml, .github/workflows/_build-test-node-and-runtime.yml, .github/workflows/_check-excluded-packages.yml, .github/workflows/_check-runtime-determimism.yml, .github/workflows/_create-featurenet.yml, .github/workflows/_delete-featurenet.yml, .github/workflows/_unit-tests-and-static-checks.yml, .github/workflows/build-and-push-cliain.yml, .github/workflows/build-docs.yml, .github/workflows/build-send-postsync-hook-runtime-image.yml, .github/workflows/contracts-deploy.yml, .github/workflows/on-main-branch-commit-run-button-e2e.yml, .github/workflows/updatenet-create.yml, .github/workflows/updatenet-delete.yml, .github/workflows/updatenet-update.yml
Change labels for `runs-on` in the workflows from `self-hosted` to `self-hosted, Linux, X64, large` to be more selective.  We are planning to introduce `small` runners as well.
=> A0-2629: Add 'large' label to self-hosted runners in workflows

finality-aleph/src/sync/service.rs
We expect verification of justifications to sometimes fail, even if everything is going well. In practice this is most pronounced when synchronizing old blocks, but in general it shouldn't be an error. This PR treats verification errors separately for the purposes of logging.
=> A0-2624: Lower log levels of verification failures

finality-aleph/src/party/manager/mod.rs
The node panicked when syncing old, incompatible sessions for which it still had keys stored. This is a hack that works around the problem, a proper fix probably requires `NodeSessionManager` to be able to return errors, preferably including marking which should be fatal.
=> A0-2641: Hacky way of surviving syncing with old keys

bin/node/src/aleph_node_rpc.rs
We rename RPC endpoint from `chain_getBlockAuthor` to `alephNode_getBlockAuthor`. This is because polkadotJS library doesn't support extending `chain` (in general: any default) RPC method section.
I have also made use of `namespace` attribute of `rpc` macro to clean the code a bit.
In future we can easily add an alias `chain_getBlockAuthor`, but for now it seems to be unnecessary (consulted with Damian).
=> A0-2325: Rename RPC endpoint

Cargo.lock, pallets/elections/src/lib.rs
This is the first PR introducing `try-state` hook to our pallets. Hopefully, more to come.
`try-state` is a similar concept to `try-runtime`. Basically, we can put all (storage) invariant checks into a hook and trigger them from anywhere we need. By default, they can be called from most of `try-runtime` commands, like `follow-chain`. More info: https://forum.polkadot.network/t/testing-complex-frame-pallets-discussion-tools/356#try-runtime-follow-chain-trystate-4 
I have broken some of the checks in `ensure_validators_are_ok` function and then:
```shell
$ cargo build --release --features try-runtime
$ ./scripts/run_nodes.sh -b false
$ ./target/release/aleph-node try-runtime --runtime existing --chain /tmp/chainspec.json follow-chain --uri ws://localhost:9944 --keep-connection
```
**Note**: …
=> A0-2671: Add try-state hook to the elections pallet

aleph-client/Cargo.lock, aleph-client/Cargo.toml, aleph-client/src/pallets/committee_management.rs, bin/cliain/Cargo.lock, bin/runtime/src/lib.rs, e2e-tests/Cargo.lock, pallets/committee-management/src/impls.rs, primitives/src/lib.rs
After recent misunderstanding, we decided to rename `session_committee` runtime API to `predict_session_committee`. Also, the documentation of both runtime API endpoint and the pallet implementation were added/updated.
=> A0-2680: Rename `session_committee` runtime API

default.nix, nix/Dockerfile.build, nix/nix-build.sh, nix/rocksdb.nix, nix/versions.nix
Changes in rust toolchain configuration (renamed rust-toolchain file) and weird behavior of `cargo` while building with `--locked` and `--offline` flags, i.e. writing new files inside of `CARGO_HOME` was causing failures of the nix based build procedure described in our `BUILD.md` document. This PR fixes these issues.
How to test it?
```
docker build -t aleph-build -f nix/Dockerfile.build . && docker run -ti --volume=$(pwd):/node/build aleph-build
```
After this, results (aleph-node and runtime binaries) should be stored in the `result` folder.
=> A0-2692: fix for nix

scripts/synthetic-network/build_synthetic-network.sh, scripts/synthetic-network/run_consensus_synthetic-network.sh
Fixes a bug within the synthetic-network e2e-test for aleph-node - referenced too old docker image.
Details:
- dirty-hack (docker tag...) for the no longer supported node:12.20.2 docker base image
- fixed `git submodule` update procedure for synthetic-network
How to test if synthetic-network is ok?
1. Build docker image for `aleph-node:latest`: `docker build -t aleph-node:latest`.
2. Call the synthetic-network build+run script: `./scripts/synthetic-network/run_consensus_synthetic-network.sh`.
3. Open your webrowser (tested on chromium) at [http://localhost:3000/control.html](http://localhost:3000/control.html) and move some of the sliders.
4. Try to observe results of your actions from point 3.: `docker logs Node0` (e.g. set bit-rate to …
=> A0-2346: fix for the high-latency e2e-test

finality-aleph/src/sync/data.rs, finality-aleph/src/sync/forest/mod.rs, finality-aleph/src/sync/handler.rs, finality-aleph/src/sync/mod.rs, finality-aleph/src/sync/service.rs
Fixing the flawed handling of incoming responses in the sync.
Further separating `Service` and `Handler` logic.
=> A0-2732: Fix handling of incoming responses

.github/actions/create-featurenet/action.yml, .github/actions/delete-featurenet/action.yml, .github/workflows/_build-and-push-pull-request-image-to-featurenets.yml, .github/workflows/_store-test-node-and-runtime.yml, .github/workflows/create-featurenet.yml, .github/workflows/on-pull-request-commit.yml, .github/workflows/on-pull-request-label.yml, .github/workflows/updatenet-create.yml, .github/workflows/updatenet-delete.yml, .github/workflows/updatenet-update.yml, e2e-tests/README.md
* Feature nets should be started from scratch, chainspec generated from node PR version, binary PR test version (short session)
* Small refactor of create and destroy feature net actions
* minor bugifx for e2e completion check in PR pipeline so that workflow does not error in case it is cancelled either by dev or by concurrency (ie pushing another commit to PR)
* remove trigger:create-hotfix-featurenet as it is not needed anymore
* added manual workflow dispatch possibility to create feature net
* Added expiration to feature nets
* Changed placement of test binaries to different bucket
Companion PRs:
* https://github.com/Cardinal-Cryptography/aleph-apps/pull/504/
* https://github.com/Cardinal-Cryptography/docker-featurenet-helper/pull/6
- Bug …
=> A0-2712: Featurenets works now on short session.

finality-aleph/src/sync/service.rs
Should make nodes send fewer block sync broadcasts without impacting sync speed.
=> Increase block sync broadcast cooldowns

.github/workflows/build-and-push-cliain.yml
This work is required for update net send runtime hook. Also, we need to trigger it in release branches as well, as we'l use those SHAs as target SHA of update net.
=> A0-2798: add cliain to s3

.github/workflows/_check-excluded-packages.yml, Cargo.lock, bin/node/Cargo.toml, bin/runtime/Cargo.toml, bin/runtime/src/lib.rs
Bumping the `transaction_version` to fix the ledger app.
=> A0-000: Bump transaction_version on release-11 to fix the ledger app

finality-aleph/src/aggregation/mod.rs, finality-aleph/src/metrics.rs, finality-aleph/src/network/gossip/service.rs, finality-aleph/src/nodes.rs, finality-aleph/src/sync/service.rs, finality-aleph/src/testing/network.rs
Port metrics from the release-11 branch and include new ones.
- Breaking change - breaking as part of the grafana dashboard will stop working if we do not update
=> A0-2814: port metrics from release-11

README.md
Since we are no longer running unit/e2e tests on merge to the `main` branch (apart from button-related, but this is temporary afaik), we should get rid of invalid links from `README.md` (and thus repo's main page).
=> A0-2942: Remove dead statuses from README

bin/runtime/src/lib.rs
Remove migrations that were introduced in `r-11.3` release.
=> A0-1846: Removed migrations from release-11 branch

.github/workflows/build-send-postsync-hook-runtime-image.yml
Removes `setup-protoc` action call that install protoc because the workflow runs on our github runner that already has protoc installed (also, in a different version).
The change does not break anything.
=> A0-2968: Remove setup-protoc step

.github/workflows/_check-excluded-packages.yml
Removes `cargo-dylint` installation from `check-excluded-packages` step.
=> A0-2988: Remove cargo-dylint installation step.

finality-aleph/src/sync/forest/mod.rs, finality-aleph/src/sync/forest/vertex.rs, finality-aleph/src/sync/handler/mod.rs
`sync::Handler` should not drop request responses containing already imported blocks. This PR changes the import strategy to simply skip old/imported blocks.
=> A0-2978: Accept more responses in sync Handler

bin/node/src/cli.rs, bin/node/src/commands.rs, bin/node/src/main.rs
Removed a sub-command of the purge-chain command that was deleting files of the alephbft backup.
After this change alephbft's backup can be removed only by manually deleting its root folder inside `--base-path`.
=> A0-2846: removed purge-alephbft-backup from the purge-backup command

.github/workflows/_check-vars-and-secrets.yml, .github/workflows/on-pull-request-commit.yml
Even though input as a boolean, its value in condition is cast to string.
=> A0-2998: Put 'true' in double quote in one the conditions to check if that helps

finality-aleph/src/sync/handler/mod.rs, finality-aleph/src/sync/mock/backend.rs
Handler now remembers that it should attempt reacquiring information about imported blocks that were too new.
=> A0-2982: Synchronize missing imports

contracts/scripts/clean.sh
Cargo-contract 3.0.0 is not 100% compatible with our pallet-contracts, so we need to use this older version to terminate contracts and remove code. Incidentally, I removed the cliain image from this script, so we only use 2 images instead of 3 different ones (also, it wasn't quite working anyway).
Should fix CI for button.
=> A0-3053: Fix contracts/scripts/clean.sh

.github/workflows/nightly-normal-session-e2e-tests.yml, .github/workflows/nightly-short-session-e2e-tests.yml, local-tests/test_major_sync.py
* bugfix for defect introduced in https://github.com/Cardinal-Cryptography/aleph-node/pull/1356 that e2e client is not build for one nightly pipeline workflow
* increase timeout from 5 to 10 minutes for sync catchup test
- Bug fix (non-breaking change which fixes an issue
=> A0-2902: Fix for nightly pipeline tests

finality-aleph/src/metrics.rs, finality-aleph/src/nodes.rs, finality-aleph/src/sync/metrics.rs, finality-aleph/src/sync/mod.rs, finality-aleph/src/sync/service.rs
Factor out the sync metrics from the centralized metrics, plus some changes to how they are organized. Since the metric names were not uniform anyway I changed them – this means there will need to be a companion PR on the Grafana side.
- I haven't made neccessary updates to the Infrastructure, but I will
=> A0-3059: Factor out sync metrics

.github/actions/run-e2e-test/action.yml, .github/workflows/_run-button-e2e-tests.yml, aleph-client/src/contract/mod.rs, e2e-tests/src/test/button_game/helpers.rs, e2e-tests/src/test/button_game/mod.rs
I made the tests run on a single node (I think some of the issues, notably the timeouts were related to this) and added some logging around the spots I think can still be flaky to get more info later. This might not solve everything, but I think it's an improvement.
=> A0-3053: Add logging to e2e button tests

aleph-client/Cargo.lock, aleph-client/Cargo.toml, aleph-client/src/pallets/mod.rs, aleph-client/src/pallets/timestamp.rs, benches/payout-stakers/Cargo.lock, bin/cliain/Cargo.lock, bin/finalizer/Cargo.lock, e2e-tests/Cargo.lock, e2e-tests/src/test/era_payout.rs, e2e-tests/src/test/finality_version.rs, e2e-tests/src/test/finalization.rs, flooder/Cargo.lock
Changes in e2e-tests and aleph-client only.
* Improved finality version change test [fixes A0-2972] - now it schedules change in (current_session+1) for (current_session+3) instead of in the 1st session for 4th session - it requires one session less and should pass even when ran after 2nd session.
* More checks and better error for era payout test [partially fixes A0-2973] - previously a problem could occur, where one validator was not producing blocks, and because of that session durations were longer than expected. Added block timestamp check to detect such a situation, and report better error message int that case.
* Add logging for finalization test [to make further investigation on A0-2974 easier]
The actual problem in failing e2e-tests is that the chain might sometimes launch …
=> A0-2935: Investigate flaky e2e tests

.github/actions/create-featurenet/action.yml, .github/actions/delete-featurenet/action.yml, .github/actions/wait-for-finalized-heads/action.yml, .github/workflows/_delete-featurenet.yml, .github/workflows/create-featurenet.yml, .github/workflows/nightly-short-session-e2e-tests.yml, .github/workflows/updatenet-create.yml, .github/workflows/updatenet-delete.yml, .github/workflows/updatenet-update.yml
This is done to unify things a little bit and not copy aleph-node-validator manifests but use the already-existing kustomize base (with an overlay on top of it)
Among few things the biggest bug that was introduced was appending Run ID to the name of featurenet which caused plenty of infrastructure problems (no sense to list them all here).
Appending Run ID is now optional for featurenet actions
Allows specific number of statefulset's replicas (meaning how many aleph nodes are meant to be started).  It's added both to `create` and `update`, hence it is possible to scale up and down existing featurenets.
It is an important fix.  Featurenets are broken anyway.
=> A0-2735: Change featurenets to use kustomize

.github/actions/create-featurenet/action.yml, .github/workflows/updatenet-create.yml
Introduces `name` input to UpdateNet Create workflow so that an updatenet can be named, eg. `fe-updnet-mynet`.  It is optional.  Hence, when no name is provided, run ID will be used, eg. `fe-updnet-1234567` (and this is how it works right now).
=> A0-3198: Add name input to updatenets

.github/workflows/updatenet-create.yml
Updatenet workflows create GH Deployment/Environment with invalid name.  I have forgotten to change its name whilst introducing optional "name" input.
Nothing major, it's just the name of env in the GH Environments in aleph-node that appears now, is just wrong.
=> A0-3193: Fix invalid deployment name

scripts/run_checks_on_excluded_packages.sh
https://github.com/727-Ventures/openbrush-contracts is not available atm, and this is breaking contract crates checks. Hance this is breaking our CI we need to disable them for now. 
See https://medium.com/brushfam/brushfam-is-leaving-polkadot-story-unfold-4fa5c38716dc for background
=> A0-3210: disable contract crates check in check excluded packages 

.github/workflows/_check-code-formatting.yml, Cargo.lock, pallets/aleph/Cargo.toml, pallets/aleph/README.md, pallets/aleph/src/lib.rs, pallets/committee-management/Cargo.toml, pallets/committee-management/README.md, pallets/committee-management/src/lib.rs, pallets/committee-management/src/manager.rs, pallets/elections/Cargo.toml, pallets/elections/README.md, pallets/elections/src/lib.rs, scripts/run_checks_on_excluded_packages.sh
https://github.com/paritytech/substrate/pull/13452 adds the possibility to include readme.md (markdown) docs into pallet metadata. This is not yet supported in our current metadata, yet it is a preparation in case metadata V15 lands on our chain. 
Also, this PR slightly reduces docs duplication by extracting our pallet file docs to README.md. That should be beneficial to a reader who browse pallet code in GH.
- run `cargo doc` for our pallets
=> A0-3132: Add pallets documentation to metadata

.github/actions/store-node-and-runtime/action.yml, .github/workflows/_build-production-node-and-runtime.yml, .github/workflows/_build-test-node-and-runtime.yml, .github/workflows/_check-runtime-determimism.yml, .github/workflows/nightly-normal-session-e2e-tests.yml, .github/workflows/nightly-short-session-e2e-tests.yml, default.nix, local-tests/test_major_sync.py
Currently, we produce compact wasm in the workflows, but we should use compact.compressed to follow Polkadot approach, as well as to decrease amount of bytes sent in the network during runtime upgrade.
This PR also removes not not-needed job which uploaded procution runtime to S3. While this file was not overwritten, it is not good practice to deploy runtime from non-push-to-main job.
=> A0-2021: Use compact compressed runtime in workflows

local-tests/chainrunner/node.py, local-tests/rolling_update.ipynb, local-tests/run_nodes.py, local-tests/test_catch_up.py, local-tests/test_force_reorg.py, local-tests/test_major_sync.py, local-tests/test_multiple_restarts.py
We forgot to update python framework with recent changes that removed WS_PORT. Hence, the long session nightly test failed.
=> A0-3112: Update python framework with RPC port changes

aleph-client/Cargo.toml, aleph-client/src/contract/mod.rs, e2e-tests/Cargo.lock
Passes the trasmitted value to dry-run in aleph-client/contracts, which fixes gas estimation in cases where gas usage is dependent on the value.
=> A0-3236: Fix dry-running when value is nonzero

Cargo.lock, bin/node/src/service.rs, finality-aleph/src/lib.rs, finality-aleph/src/nodes.rs, finality-aleph/src/sync/forest/mod.rs, finality-aleph/src/sync/handler/mod.rs, finality-aleph/src/sync/mod.rs, finality-aleph/src/sync/service.rs, finality-aleph/src/sync_oracle.rs
Make Aura use the information from our sync to decide on block production (whether we are in "major sync").
Some of the choices here might be controversial, so I would welcome opinions about them. <_<
=> A0-3037: Sync information for Aura

Cargo.lock, bin/node/Cargo.toml, bin/runtime/Cargo.toml, bin/runtime/src/lib.rs
This change
* bumps `spec_version` and `tx_version` - latter since quite a lot pallet API changed 
* bumps node and runtime version to `0.12.0`
* enable contract migrations
=> A0-3249: Prepare release-12 RC commit

Cargo.lock, aleph-client/Cargo.lock, baby-liminal-extension/Cargo.lock, benches/payout-stakers/Cargo.lock, bin/cliain/Cargo.lock, bin/finalizer/Cargo.lock, contracts/access_control/Cargo.lock, contracts/adder/Cargo.lock, contracts/button/Cargo.lock, contracts/game_token/Cargo.lock, contracts/marketplace/Cargo.lock, contracts/poseidon_host_bench/Cargo.lock, contracts/shared_traits/Cargo.lock, contracts/simple_dex/Cargo.lock, contracts/ticket_token/Cargo.lock, contracts/wrapped_azero/Cargo.lock, e2e-tests/Cargo.lock, flooder/Cargo.lock, fork-off/Cargo.lock, pallets/baby-liminal/Cargo.lock, poseidon/Cargo.lock, relations/ark/Cargo.lock, relations/ark/src/proc_macro/Cargo.lock, relations/jf/Cargo.lock, scripts/synthetic-network/synthetic-link/Cargo.lock
This is bump of our substrate fork's `aleph-v1.0.0` branch to commit https://github.com/Cardinal-Cryptography/substrate/commit/357a82e70f10aedd2e9a87e32462cfec08663be2 that contains fix for pallet contracts v12 migration.
To generate this PR I've just run 
```
scripts/update_substrate_git_branch.sh aleph-v1.0.0
```
The changes we want to review most are in main `Cargo.lock` file that matters from building `aleph-node` binary. 
=> A0-3270: Update all Cargo.locks to pick up bumped aleph-v1.0.0 branch

finality-aleph/src/sync/forest/mod.rs, finality-aleph/src/sync/forest/vertex.rs
We should have limited vertex size, to not run out of memory if new people keep sending us sync messages.
=> A0-3281: Limit vertex size

.github/actions/run-e2e-test/action.yml, .github/workflows/_check-vars-and-secrets.yml, .github/workflows/_run-e2e-tests.yml, .github/workflows/nightly-e2e-logic-tests.yml, .github/workflows/nightly-fe-e2e-tests.yml, .github/workflows/nightly-normal-session-e2e-tests.yml, .github/workflows/on-pull-request-commit.yml
* Move all e2e tests except finalization to the nightly pipeline. This shortens the PR pipeline by about 6 minutes. Now most culprit is runtime determinism check. 
* The finalization e2e test must stay in PR pipeline as it is an important smoke test. 
* all nightly pipelines can be triggered on demand, in which case there won't be a slack notification sent
* redirect slack notifications to different channel
- Breaking change to repo check settings. Before merge I'll remove  e2e test suite completion check and add e2e finalization check.
See sample new wokrflow run https://github.com/Cardinal-Cryptography/aleph-node/actions/runs/6478879803
=> A0-2714: Nightly pipeline notifications and A0-3212: Move rest of e2e tests to nightly pipeline

.github/workflows/_check-code-formatting.yml, .github/workflows/_check-production-node-and-runtime.yml, .github/workflows/_unit-tests-and-static-checks.yml, .github/workflows/nightly-check-runtime-determinism.yml, .github/workflows/nightly-checkruntime-determinism.yml, .github/workflows/nightly-e2e-logic-tests.yml, .github/workflows/nightly-integration-tests.yml, .github/workflows/nightly-normal-session-e2e-tests.yml, .github/workflows/nightly-short-session-e2e-tests.yml, .github/workflows/on-pull-request-commit.yml
* Moved check runtime determinism to nightly. Motivation is that we don't need to check it that often, and it burns computation power. It is enough to check it every 24 hours in nightly.
* In PR pipeline, just check the production binary instead of compiling it. This is because we do not use production binary in this pipeline, just we want to know whether it compiles. Especially it's hard for linking time as it's 70% of compilation time (due to LTO). Hence I moved actual build to nightly as well.
* Move clique network tests to nightly. This is because they are long-running integration tests 
* Now the outlier is check excluded packages, but we'll deal with it in the next PRs.
* Split `clippy` and `cargo test` into two paraller jobs
* There's one required check pending in this PR but this …
=> A0-3298: Move clique network tests to nightly

bin/runtime/src/lib.rs, primitives/src/lib.rs
Add runtime api for getting owner of aleph key.
=> A0-3363: Runtime api for aleph key owner

.github/workflows/nightly-integration-tests.yml
Pipelines
* Nightly pipeline check runtime determinism
* Nightly pipeline integration tests
are spawned in one minute from each other, so in practice, it means in parallel, which is a bug.
See https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule
=> A0-3380: Fixed schedule so all nightly workflows are run within one hour distance.

.github/actions/build-and-push-dockerhub-image/action.yml
Fixes action for pushing image to dockerhub.  It doesn't properly push the "latest" tag.  The `docker tag` command used in the step has invalid source image.
=> A0-3398: Change docker tag to use inputs.target-image as source

aleph-client/Cargo.lock, aleph-client/Cargo.toml, bin/cliain/Cargo.lock, bin/cliain/Cargo.toml
Updates ink-releated dependencies in `aleph-client`. There were no changes in the API or in the code, purely dependency bump. This update is necessary to align `aleph-client` with `ink-wrapper` which works with `ink` and `aleph-client` as a backend.
The versions of dependencies used are going to be the last compatible with ink4
- Dependency versions update.
- I have bumped aleph-client version
- I have bumped cliain verison
=> A0-3430: Update ink deps to latest ink4-compatible releases

.github/actions/build-and-push-dockerhub-image/action.yml
Backport of fix https://github.com/Cardinal-Cryptography/aleph-node/commit/36bdfbde92f0a4b6a65372d223581273b8c2fe73 
=> A0-3398: Change docker tag to use inputs.target-image as source (#1458)

finality-aleph/src/sync/handler/mod.rs, finality-aleph/src/sync/service.rs
There was a race making finalization sometimes stop if it fell too far behind the head of the imported chain, this works around that problem. It also slows down some requests, to lower the amount of log spamming during major sync (still spammy tho).
=> A0-3422: Fix major sync finalization problems

Cargo.lock, bin/node/Cargo.toml, bin/runtime/Cargo.toml, finality-aleph/src/sync/forest/mod.rs, finality-aleph/src/sync/handler/mod.rs
Make sync handler understand having too many nonfinalized blocks on startup instead of panicking.
=> A0-3422: Deal with too many nonfinalized blocks on startup

nix/versions.nix
nix build scripts should use rust-1.70.
=> A0-2133: bump rust version for nix

.github/workflows/_build-production-node-and-e2e-client-image.yml, scripts/common.sh, scripts/synthetic-network/build_synthetic-network.sh
Calling scripts/build_synthetic_network.sh from within nightly-pipeline was failling due to missing TERM env variable.
=> A0-3466: FIX calling scripts/build_synthetic_network.sh failed due to missing TERM

.github/actions/get-docker-image-names/action.yml, .github/workflows/_build-and-push-pull-request-image-to-featurenets.yml, .github/workflows/_build-liminal-node.yml, .github/workflows/_check-excluded-packages.yml, .github/workflows/_check-runtime-determimism.yml, .github/workflows/_check-vars-and-secrets.yml, .github/workflows/_update-node-image-infra.yml, .github/workflows/build-and-push-cliain.yml, .github/workflows/deploy-to-devnet.yml, .github/workflows/deploy-to-mainnet.yml, .github/workflows/deploy-to-testnet.yml, .github/workflows/featurenet-create-from-branch.yml, .github/workflows/nightly-fe-e2e-tests.yml, .github/workflows/on-main-branch-commit-push-liminal-node-to-ecr.yml, .github/workflows/on-main-or-release-branch-commit.yml, .github/workflows/on-pull-request-close.yml, .github/workflows/on-pull-request-label.yml, .github/workflows/on-push-release-tag.yml, .github/workflows/on-release-branch-commit.yml, .github/workflows/on-release.yml, .github/workflows/push-foundation-repo.yml
Removes unnecessary double quotes in the workflow files.  Also, tidies up some variable names and make use of `${{ env.VAR }}` everywhere, for the consistency and security.
Please review carefully.  We cannot break deployment workflows.
=> A0-3310: Tidy up double quotes

finality-aleph/src/data_io/data_store.rs, finality-aleph/src/data_io/legacy/data_store.rs, finality-aleph/src/party/manager/mod.rs, finality-aleph/src/sync/data.rs, finality-aleph/src/sync/forest/mod.rs, finality-aleph/src/sync/forest/vertex.rs, finality-aleph/src/sync/handler/mod.rs, finality-aleph/src/sync/handler/request_handler.rs, finality-aleph/src/sync/mod.rs, finality-aleph/src/sync/service.rs, finality-aleph/src/sync/tasks.rs, finality-aleph/src/testing/data_store.rs
Introduce verifiable requests. For backwards compatibility reasons they cannot be fully enforced yet, that will require a separate update.
=> A0-3307: Introduce verifiable requests

.github/actions/run-e2e-test/action.yml, .github/scripts/run_consensus.sh, .github/scripts/run_e2e_test.sh, .github/workflows/_run-e2e-tests.yml, .github/workflows/on-pull-request-commit.yml, docker/common.yml, e2e-tests/Cargo.lock
* Enable RUST_LOG=debug in e2e.
* dump all logs from docker-compose and archive them in a tarball, but only for failed e2e
* Upload this tarball to GH artifacts
Considerations:
Log growth is around 200 MB per node per 1 hour so given that some nightly tests run 1 hour and there are max 10 nodes, we have 2GB per test, which is affordable as GH runners have a quota of 14 GB, and our self-hosted runners have at least that much. Also, compressed logs should be around 100 MBs max, so for the case of GH artifacts quota, we should be good. For public repos, we don’t pay anything for this quota anyway.
There's some trickery when calling e2e client docker, as there's no way to enforce timeout on step level in  GH composite actions, so I needed to do a workaround to apply custom timeout mechanism …
=> A0-3499: Archive logs in case of e2e failure

aleph-client/Cargo.lock, bin/cliain/Cargo.lock, bin/runtime/src/lib.rs, pallets/baby-liminal/src/benchmarking/suite.rs
After recent substrate bump, some imports broke in the pallet benchmarking module. This PR fixes it.
TODO: To be tested on the nightly pipeline
=> A0-3507: Fix imports in benchmarking

.github/workflows/deploy-to-devnet.yml
We should run deploy-to-devnet.yml workflow in aleph-node as frequently as possible, but not on every commit to main so as to have at least a few hours of this environment stability. The reason we want this is that some devs use dev.azero.dev which has Devnet as the default chain connected to, so humans can spot some errors before the release with more probability. 
Remark: Devnet will be deprecated in 2024 when features are rolled out, yet behavior would be similiar: there would be a long running feturenet updated every 24 hours from aleph-node main etc; till now then I'll change Devnet to be deployed every night from aleph-node main
=> A0-3520: Run deploy to devnet daily at Midnight

finality-aleph/src/lib.rs, finality-aleph/src/network/session/mod.rs, finality-aleph/src/network/substrate.rs, finality-aleph/src/sync/data.rs, finality-aleph/src/sync/mod.rs
Sync messages can be bigger, so increased the constant for them. Also moved some code around to lower the likelyhood of making this code in the future.
I also found some old compatibility code while going through this, so I removed in on the way, it's definitely not needed any more.
=> A0-3550: Better constants for libp2p message sizes

finality-aleph/src/sync/forest/mod.rs, finality-aleph/src/sync/handler/mod.rs
This should have been the case already, but we missed it. Also added a unit test for this and some slightly better logs.
=> A0-3562: Mark ancestors of justifications as required

pallets/baby-liminal/src/lib.rs, pallets/baby-liminal/src/weights.rs
Although we don't have benchmarks for jellyfish verifier (and thus the pallet charges 0 weight for verification), we should enrich `WeightInfo` trait with `verify` method that returns for now `0` and use it in both pallet and the extension.
=> A0-3518: Move `verify` weighting to the proper place

bin/node/src/service.rs, finality-aleph/src/block/substrate/mod.rs, finality-aleph/src/data_io/data_provider.rs, finality-aleph/src/data_io/legacy/data_provider.rs, finality-aleph/src/finalization.rs, finality-aleph/src/import.rs, finality-aleph/src/lib.rs, finality-aleph/src/metrics/all_block.rs, finality-aleph/src/metrics/mod.rs, finality-aleph/src/metrics/timing.rs, finality-aleph/src/party/manager/aggregator.rs, finality-aleph/src/party/manager/mod.rs
Introduce `AllBlockMetrics` which is a wrapper for different types of block metrics.
Currently it only wraps `TimingBlockMetrics` but in future it will contain some other metrics.
Adjustments made to `TimingBlockMetrics`:
* from `report_block` and `report_block_if_not_present` created a single function of semantics equal to `report_block_if_not_present`, but named `report_block`.
* Changed signature of `report_block(hash, timestamp, checkpoint)` to `report_block(hash, checkpoint)` - the timestamp can be inferred inside the function
* Parameterized the struct with newly added `trait Clock` - there were some tests which checked behavior of `TimingBlockMetrics` when manipulating the times of newly appearing reports. After removing `timestamp` from `report_block` signature we needed to …
=> A0-3015: Introduce AllBlockMetrics wrapper

.github/workflows/on-push-release-tag.yml
This simple check prevents releases in which node version is not updated. It works on `r-*` tag push, and just compares part of the pushed tag with appropriate part of `package.version` field from `bin/node/Cargo.toml`.
Tested on my fork. Examples:
1. Version in `bin/node/Cargo.toml` is `0.100.9`. Someone pushes tag `r-100.10-rc1`. Check [fails](https://github.com/Marcin-Radecki/aleph-node/actions/runs/7057092013)
2. Version in `bin/node/Cargo.toml` is `0.100.10`. Someone pushes `r-100.10-rc2`. Check [suceeds](https://github.com/Marcin-Radecki/aleph-node/actions/runs/7057097280)
3. Version in `bin/node/Cargo.toml` is `0.100.10`. Someone pushes `r-100.10`. Check …
=> A0-2823: Create checks for aleph-node tag version

Cargo.lock, bin/node/Cargo.toml, bin/node/src/aleph_cli.rs, bin/node/src/main.rs, bin/node/src/pruning_config.rs
Removes `rocksdb` as the db back-end when one wants to use database pruning. Pruning when `rocksdb` is used works differently than when we use `paritydb`, i.e. some pruning state is stored in-memory instead of being db-backed. In our tests, rocksdb-pruning was pretty unstable - sometimes it works, sometimes it allocates whole available memory and crashes. In case of `paritydb` we haven't observed such problems. It also renames `--experimental-pruning` cli option to `enable-pruning`.
=> A0-3554: remove pruning option for rocksdb

baby-liminal-extension/Cargo.lock, baby-liminal-extension/src/args.rs, baby-liminal-extension/src/backend/executor.rs, baby-liminal-extension/src/backend/mod.rs, baby-liminal-extension/src/backend/tests.rs, baby-liminal-extension/src/backend/tests/arguments.rs, baby-liminal-extension/src/backend/tests/environment.rs, baby-liminal-extension/src/backend/tests/executor.rs, baby-liminal-extension/src/extension_ids.rs, baby-liminal-extension/src/frontend.rs, baby-liminal-extension/src/lib.rs, baby-liminal-extension/src/status_codes.rs, baby-liminal-extension/test_contract/lib.rs
As a part of redefining liminal pallet, we remove all key-related operations from the chain extension.
Next steps:
- bring verification to CE
- purge pallet
=> A0-3618: Leave only proof verification in the chain extension

contracts/adder/deploy.sh
This PR reverts regression introduced in https://github.com/Cardinal-Cryptography/aleph-node/commit/03af3c3e20ea1618e4fc3b6b81216060cd991ae4#diff-3a41020016879ea871e02f455267f8a057fbdde94bdfb5e3ba8e4cad2a2f2943L16
* https://github.com/Cardinal-Cryptography/aleph-node/actions/runs/7191635945
=> A0-3627: Reverted ink-dev to 1.0.0

baby-liminal-extension/Cargo.lock, baby-liminal-extension/Cargo.toml, baby-liminal-extension/src/args.rs, baby-liminal-extension/src/backend/mod.rs, baby-liminal-extension/src/extension_ids.rs, baby-liminal-extension/src/frontend.rs, baby-liminal-extension/test_contract/Cargo.lock, baby-liminal-extension/test_contract/Cargo.toml, baby-liminal-extension/test_contract/lib.rs
We bump ink version to 5.0.0-rc for the chain extension (and its frontend test). Apart from keeping up with the development process, we gain a bit better extension function identification.
=> A0-3704: Migrate extension to ink5

bin/node/src/service.rs, finality-aleph/src/lib.rs, finality-aleph/src/nodes.rs, finality-aleph/src/sync/service.rs
Sync previously had 2 sources of justifications. Now it has only one. The channel for justification creation is done by newly introduced `ChannelProvider<T>` which can output many senders, or can be consumed to output the receiver.
=> A0-2149: Single justification source for sync

.github/workflows/featurenet-create.yml, .github/workflows/featurenet-update.yml, .github/workflows/nightly-fe-e2e-tests.yml, .github/workflows/nightly-update-net-tests.yml
This PR adds the possibility to spawn FE with a custom sudo account id. 
1. [Run with default parameters, Alice is sudo](https://github.com/Cardinal-Cryptography/aleph-node/actions/runs/7258857766) 
2. [Run with custom sudo account id, `5EyDzpeMZqrLsCoUMn6fPVYvGiScMfuA3LPAodQecvSmnLmK` is sudo](https://github.com/Cardinal-Cryptography/aleph-node/actions/runs/7258896842)
https://github.com/Cardinal-Cryptography/github-actions/pull/36
https://github.com/Cardinal-Cryptography/featurenet-template/pull/19
=> A0-3737: Support for dynamic sudo in FE bootstrap

pallets/aleph/src/lib.rs, pallets/aleph/src/tests.rs
The order of aleph authorities returned from `get_authorities_for_next_session` was not matching the order kept in `NextFinalityCommittee`. Due to conversion of `NextFinalityCommittee` into `BTree` we were losing the order initially created by shuffling the validators list in `pallets::committee_management::impls::shuffle_order_for_session`. Instead, the `next_committee_authorities` inferred its ordering according to `next_authorities` argument passed to `get_authorities_for_next_session` which had a different ordering (most likely matching the order of the **producers** list given in `pallets::committee_management::impls::shuffle_order_for_session`).
For a fix, instead converting `NextFinalityCommittee` to `BTreeSet`, convert `next_authorities` to `BTreeMap` and obtain the authority ids …
=> A0-3782: Fix order of aleph authorities

baby-liminal-extension/Cargo.lock, scripts/run_nodes.sh
Just a minor change to `./scripts/run_nodes.sh` allowing for launching local liminal chain (with `./scripts/run_nodes.sh --liminal`).
=> A0-3852: Add config parameter to `run_nodes.sh` for liminal build

docker/docker_entrypoint.sh
Added a PRUNING_ENABLED flag to docker_entrypoint.sh. It allows to enable database pruning mode of aleph-node. Note that setting it to true also switches the db backend to paritydb (aleph-node command line params validation switches it).
=> A0-1306: PRUNING_ENABLED flag for docker_entrypoint.sh

bin/runtime/src/lib.rs
THIS IS A RUNTIME-ONLY CHANGE.
Increases the maximum code len for a contract from 128 KB to 256 KB. The reason this is safe is that the constant 72 that we have in our integrity test changed:
- first 72 -> 68 (which we didn't mirror in our repo, but it's here https://github.com/paritytech/polkadot-sdk/blob/06fa111f58b0172c9f4ba7c209c8b6945787faeb/substrate/frame/contracts/src/lib.rs#L439 ) this was a result of changing gas metering
- then 68 -> 32 -- this is a result of updating wasmi to v0.30 which reduces the amount of memory each instruction requires. In slack I include a message from a Pallet Contract Developer which clarifies this further.
- Increased maximum length of a contract from 128KB to 256 KB.
=> A0-3861:  Increase MaxCodeLen for contracts.

.github/workflows/on-release.yml
Add SHA256 checksum to all artifacts uploaded in a GH release.
Tested on my fork:
* [Workflow run](https://github.com/Marcin-Radecki/aleph-node/actions/runs/7567662908/job/20607272006) - with some parts of it commented out to make it work on fork
* published release: https://github.com/Marcin-Radecki/aleph-node/releases/tag/test-tag-40
=> A0-3642: Generate release artifacts checksum

scripts/accounts-invariants/pallet-balances-maintenance.py
Script for maintenance operations on AlephNode chain with regard to pallet balances.
It has the following functionality: 
* workaround for bug https://github.com/paritytech/polkadot-sdk/pull/2700/files, that make sure all 
accounts have at least ED as their free balance,
* programmatic support for sending Balances.UpgradeAccounts ext for all accounts,
* checking pallet balances and account reference counters invariants.
By default, it connects to an AlephZero Testnet and performs sanity checks only ie not changing state of the chain at all.
Accounts that do not satisfy those checks are written to `accounts-with-failed-invariants.json file`.
1) Base functionality (only check invariants …
=> A0-3894: A0-3891 A0-3892 Added pallet-balances-maintenance.py

bin/node/src/service.rs, finality-aleph/src/party/mod.rs, finality-aleph/src/sync/handler/mod.rs, finality-aleph/src/sync_oracle.rs
Our `SyncOracle` now returns an `AtomicBool` denoting if we're in major sync.
=> A0-3751: Make our `SyncOracle` compatible with `SyncingService`

finality-aleph/src/base_protocol/handler.rs, finality-aleph/src/base_protocol/mod.rs, finality-aleph/src/base_protocol/service.rs, finality-aleph/src/lib.rs
Adds an outline of the new base protocol, replacement for `SyncingEngine`. Does not have the protocol, but does some of the other things we will need.
I think some of the imports will have to be changed during the next substrate updates, because the definitions are now in different crates, but oh well.
=> A0-3899: Our base protocol outline

.github/dependabot.yml
Based on [https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#groups), we can enable the following:
* `commit-message.prefix` set to some branch created for general Jira item for dependabot updates. This will be helpful also for audit purposes, as Jira will link all such PRs automatically
* `groups` : make one PR for version updates and another PR for github actions update. We can then change the interval to Daily for version updates (leave Weekly for actions updates), as there will be only one PR raised so costs from CI will be similar to 5 PRs raised per week. Each day, the following …
=> A0-3838: Updates to dependabot file

finality-aleph/src/base_protocol/handler.rs, finality-aleph/src/base_protocol/service.rs
Add logic for handshake and peer slot constraints verification. The verification part checks the genesis hash contained in the handshake, and checks if we can connect the peer according to the specified constraints. Added logic for peer sets management and counting the peers of a particular role and direction (full inbound, full outbound, light).
The logic of accepting peers depending on their role and available spots has been rewritten to be more readable and should preserve the previous logic of `SyncingEngine`. The peer slot rules are:
* reserved nodes (those who have been specified during construction of `Handler` as `reserved_nodes`) can freely connect and disconnect with no constraints.
* there are separate bounds on the number of **inbound** and **outbound** full nodes.
* there is …
=> A0-3900: Sync handshake logic

bin/runtime/src/lib.rs
This configures the Call Runtime functionality in Pallet Contracts. From now on the contracts will be able to call the Staking and the Nomination Pools pallet as if they were signed origins.
- New feature
=> A0-3970: Configure Call Filter for Call Runtime in Smart Contracts

Cargo.lock, bin/node/Cargo.toml, bin/runtime/Cargo.toml, bin/runtime/src/lib.rs
* bump `spec_version` and `transaction_version`
* bump runtime and node version
Current `spec_version` and `transaction_version`  on Testnet in Mainet is the same and as follows: `68` and `17`.
=> A0-4009: Bump node and runtime spec_version and tx version in release-13 branch

Cargo.lock, bin/node/Cargo.toml, bin/runtime/Cargo.toml
After `release-13` was cut off, `main` is now 14 dev version.
=> A0-4009: Bumped node and runtime version on main for 14 dev version

docker/docker_entrypoint.sh
Added a PRUNING_ENABLED flag to docker_entrypoint.sh. It allows to enable database pruning mode of aleph-node. Note that setting it to true also switches the db backend to paritydb (aleph-node command line params validation switches it).
=> A0-1306: cherry-pick 52cc6b6a to release-13

docker/docker_entrypoint.sh
As per https://github.com/paritytech/substrate/pull/14387, `--execution` flag is already deprecated (from AlephNode 12.X version). 
This PR clears out warning raised when `aleph-node` starts
```
CLI parameter `--execution` has no effect anymore and will be removed in the future!
```
=> A0-3219: Remove deprecated --execution flag from docker_entrypoint.sh

.github/scripts/get_top_block.py, .github/scripts/test_db_sync.sh, .github/scripts/test_testnet_db_sync.sh, .github/workflows/weekly-sync-from-snapshot-testnet-pruned.yml, .github/workflows/weekly-sync-from-snapshot-testnet.yml
Add two weekly tests for syncing the DB from a snapshot. One downloads the pruned ParityDB snapshot and synces to testnet on Tuesday, and another does the same with a non-pruned one on Wednesday.
Automated tests.
=> A0-2699: Weekly sync from snapshot tests

pallets/feature-control/src/lib.rs, pallets/vk-storage/src/lib.rs
Complying with https://github.com/paritytech/polkadot-sdk/issues/323 in two pallets (out of five). The other (`aleph`, `committee_management` and `elections`) contain vectors, but they are sudo-controlled, so we should be kinda safe (although we might want to come up with some size bounds there at some point).
=> A0-4053: Remove without-storage-info macro where possible

Cargo.lock, baby-liminal-extension/Cargo.lock, baby-liminal-extension/Cargo.toml, baby-liminal-extension/src/backend/executor.rs, baby-liminal-extension/src/backend/mod.rs, baby-liminal-extension/src/backend/tests.rs, bin/runtime/src/lib.rs
We are using `feature-control` pallet to ensure that nobody can access on-chain verifier related code, unless this feature is enabled.
E2E tests will be added after this and #1614 are merged, so that we don't have to tackle with `liminal` compilation feature in e2e-test launching setup.
=> A0-4055: hide on-chain verifier also behind runtime checks

scripts/accounts-invariants/pallet-balances-maintenance.py
Script attaches to given WS URL and 
* queries all `System.Account` keys which have `providers` counter set to 2 (from single block state),
* transforms above `AccountInfo` data in a way only `providers` counter is modifies and set to 1
* performs `System.setStorage` with list of key-value tuples (storage_key, storage_value)
* checks that from the original state there were no events emitted that concerns double providers accounts,
* at the end makes sure there are no double providers account anymore.
=> A0-3728: script for fixing double providers counter

Cargo.lock, finality-aleph/Cargo.toml, finality-aleph/src/runtime_api.rs
An implementation of direct storage access to support backwards-compatible runtime API.
* Added `read_storage_map` which reads the element of a runtime storage map directly
* Improved error handling
* Added test which checks that `read_storage_map` and `read_storage_value` work assuming appropriate storage key naming convention (map element is under appropriately digested version of `pallet + map_name + key`, storage value similarly at `pallet + storage_value_name`).
=> A0-3589: Direct storage read functions

finality-aleph/src/data_io/data_provider.rs, finality-aleph/src/data_io/legacy/data_provider.rs
Sleep with retires when expecting Some data (still theoretically not ideal, but practically it sleeps 15s in the worst case before failing, when practically 5ms should be sufficient) .
Change in tests pipeline
=> A0-4060: Fix spurious fails of data provider tests

.github/actions/run-e2e-test/action.yml, .github/workflows/nightly-normal-session-e2e-tests.yml
It looks like all tests run by `run_e2e_test.sh` were using only the default value for its `TIMEOUT_MINUTES` variable.
It can be verified by investigating past runs of the nighly-pipeline: compare its logs (i.e. `2024-02-21T22:27:03.4202170Z Running test, logs will be shown when tests finishes or after 20m timeout.`) with values used in action's declaration.
=> A0-4096: FIX timeouts for run_e2e_test action

aleph-client/Cargo.lock, aleph-client/Cargo.toml, aleph-client/src/pallets/feature_control.rs, aleph-client/src/pallets/mod.rs, aleph-client/src/pallets/vk_storage.rs, bin/cliain/Cargo.lock, e2e-tests/Cargo.lock
Recently we added the feature control and vk storage pallet - in order to test them in e2e tests, we need its API covered by aleph-client.
=> A0-4099: New pallets API in aleph-client

finality-aleph/src/block/substrate/verification/cache.rs
In rare situations a block created in the same slot but different session was falsely marked as an equivocation, this PR fixes the problem.
=> A0-4100: [HOTFIX] Equivocations have to happen in the same session

bin/runtime/src/lib.rs
Polkadot has 50, and there are no practical implications to not increase it. In AlephNode 13 version, there are only two reasons for holds (`CodeUploadDeposit` and `StorageDeposit`), but in the future, there can be more, as more and more pallets are going to use holds and deprecate locks. Also, now we have `MaxLocks` == 50.
* make sure constant returned from wallet is 50
* run adder e2e test: https://github.com/Cardinal-Cryptography/aleph-node/actions/runs/8062988259
=> A0-4112: Increase MaxHolds to 50

Cargo.lock, Cargo.toml, bin/node/Cargo.toml, bin/runtime/Cargo.toml, bin/runtime/src/lib.rs, pallets/operations/Cargo.toml, pallets/operations/LICENSE, pallets/operations/README.md, pallets/operations/src/impls.rs, pallets/operations/src/lib.rs, pallets/operations/src/tests/mod.rs, pallets/operations/src/tests/setup.rs, pallets/operations/src/tests/suite.rs, pallets/operations/src/traits.rs, scripts/run_nodes.sh
An account can have an underflow of a `consumers` counter. 
Account categories that are impacted by this issue depend on a chain runtime,
but specifically for AlephNode runtime are as follows:
* `consumers`  == 0, `reserved`  > 0
* `consumers`  == 1, `balances.Locks` contain an entry with `id`  == `vesting`
* `consumers`  == 2, `balances.Locks` contain an entry with `id`  == `staking`
* `consumers`  == 3, `balances.Locks` contain entries with `id`  == `staking`
and account id is in `session.nextKeys`
This PR adds `pallet-operations` with a single extrinsic `fix_accounts_consumers_underflow` that checks if the account falls into one of the above categories, and increases its `consumers` counter in such scenario.
- Bug fix (non-breaking change …
=> A0-4020: Pallet operations. 

.github/scripts/test_testnet_db_sync.sh
Increase the timeout before we attempt to connect to a node in sync from snapshot tests.
=> A0-4164: Increase node startup timeout for sync tests

Cargo.toml
When working with the `aleph-node` repo (e.g. `./scripts/run_nodes.sh`) one gets:
```
warning: virtual workspace defaulting to `resolver = "1"` despite one or more workspace members being on edition 2021 which implies `resolver = "2"`
note: to keep the current resolver, specify `workspace.resolver = "1"` in the workspace root's manifest
note: to use the edition 2021 resolver, specify `workspace.resolver = "2"` in the workspace root's manifest
note: for more details see https://doc.rust-lang.org/cargo/reference/resolver.html#resolver-versions
```
Fixed it by specifying resolver version in the main `Cargo.toml`.
=> A0-4173: Workspace resolver

Cargo.lock, bin/node/Cargo.toml, bin/runtime/Cargo.toml, bin/runtime/src/lib.rs, pallets/operations/Cargo.toml, pallets/operations/src/impls.rs, pallets/operations/src/lib.rs, pallets/operations/src/tests/setup.rs, pallets/operations/src/tests/suite.rs, pallets/operations/src/traits.rs
`operations.fix_accounts_consumers_underflow` does not take into account controller != stash scenario, in which case `consumers` should not be incremented on stash account, but on the controller account.
=> A0-4020: fix for fix accounts consumers underflow

.github/workflows/nightly-fe-e2e-tests.yml
When an ECR image exists, this workflow is a no-op and silently skips e2e test run. This is because GHA skips a job when any parent job is skipped.
Unfortunately, there is no way to test this as the scenario in which bug occurs is when there's already an image on ECR, ie when e.g. running this workflow from `main`. So I've just run workflow from this PR https://github.com/Cardinal-Cryptography/aleph-node/actions/runs/8292896136, and if its okay then we can merge this PR and re-run from main to see if it helped.
=> A0-4172: Fix for FE e2e nightly

.github/dependabot.yml
Ignore aleph-bft-rmc and aleph-bft-types in dependabot. This is equivalent to running those commands on a PR:
```
https://github.com/dependabot ignore aleph-bft-types
https://github.com/dependabot ignore aleph-bft-rmc
```
=> A0-4174: Ignore aleph-bft-rmc and aleph-bft-types

bin/runtime/src/lib.rs, primitives/src/lib.rs
This PR moves some types from `aleph-runtime` to `primitives`. Also, it cleans up and documents most of the types and consts in `primitives`. I used https://github.com/Cardinal-Cryptography/polkadot-sdk/blob/aleph-v1.4.0/polkadot/node/service/src/lib.rs as a baseline for types, their order in the file and comments.
What can't be extracted though is `Block` type and its dependees. This is because, in `primitives` it uses `OpaqueExtrinsic`, and in runtime non-opaque one, so there are different types.
This is PR 1/2 of incorporating [`fake_runtime_api.rs`](https://github.com/Cardinal-Cryptography/polkadot-sdk/blob/aleph-v1.4.0/polkadot/node/service/src/fake_runtime_api.rs) into `aleph-node`.
=> A0-4216: Does not depend on actual runtime API in aleph-node: const and types refactor

Cargo.lock, bin/node/Cargo.toml, bin/node/src/aleph_cli.rs, bin/node/src/chain_spec.rs, bin/node/src/commands.rs, bin/node/src/lib.rs, bin/node/src/main.rs, bin/node/src/rpc.rs, bin/node/src/service.rs, bin/runtime/src/lib.rs, finality-aleph/Cargo.toml, finality-aleph/src/testing/mocks/client.rs, primitives/Cargo.toml, primitives/src/fake_runtime_api.rs, primitives/src/lib.rs
tl;dr 
Goal of this PR is to have only chainspec generation as only `aleph-runtime` dependency in `aleph-node`.
In aleph-node, we depend on aleph-runtimes RuntimeAPI type. This is not required, as per https://github.com/Cardinal-Cryptography/polkadot-sdk/commit/e53d15aa20e77eb35ccb590bb7ef940d3eca7dbb :
> These runtime api implementations are only used to make the compiler
think that we have implemented all required runtime apis. They will notbe called as we switch the executor to WasmExecutor. In the nearfuture we will not require these fake implementations anymore afterSubstrate has shifted away from this compile time requirement.This brings us the advantage that the polkadot-service doesn't need todepend on the runtimes for getting the RuntimeApi   also removes around 1min of build …
=> A0-4216: Does not depend on actual runtime API in aleph-node

.github/workflows/nightly-check-node-features-build.yml
This PR adds a simple `cargo check` command for `try-runtime` and `runtime-benchmarks` builds. Although it takes < 10 minutes, it is enough to build it in nightly or on demand only. 
https://github.com/Cardinal-Cryptography/aleph-node/actions/runs/8599951172/job/23563916878
=> A0-4233: Nightly workflow for feature-gated builds

Cargo.lock, bin/runtime/Cargo.toml, bin/runtime/src/lib.rs
In `polkadot-sdk` 1.4.0, `pallet-contracts` depends on `xcm-builder` package. [It failed to build with `runtime-benchmarks` feature](https://github.com/Cardinal-Cryptography/aleph-node/actions/runs/8605918122/job/23583222670). Fix is to enable `runtime-benchmarks` for `pallet-contracts` in our runtime. Also, this PR enables other `runtime-benchmark` features for various pallets our runtime uses.
https://github.com/Cardinal-Cryptography/aleph-node/actions/runs/8611531265
=> A0-3921: Fix runtime-benchmarks build

.github/workflows/nightly-check-node-features-build.yml, BUILD.md, bin/node/Cargo.toml, bin/node/src/executor.rs, bin/node/src/lib.rs, bin/node/src/service.rs
Hide implementation of `NativeExecutionDispatch` for the `ExecutorDispatch` behind `local-debugging`. `NativeExecutionDispatch` is needed for debugging locally, as well as for `runtime-benchmarks`. Pehaps it's not needed for `try-runtime`, but it's subject to the next PRs.
https://github.com/Cardinal-Cryptography/aleph-node/actions/runs/8628234269
https://github.com/Cardinal-Cryptography/aleph-node/actions/runs/8615033603
=> A0-4208: Hide NativeExecutionDispatch behind feature flags

.github/workflows/weekly-featurenets-short-session-full-sha.yml, .github/workflows/weekly-featurenets-short-session-tag.yml
We should be using more recent `aleph-node` images on our CI.
=> A0-3848: Update weekly nightly start FE tests to more recent aleph-node

Cargo.lock, aleph-client/Cargo.lock, benches/payout-stakers/Cargo.lock, bin/cliain/Cargo.lock, bin/finalizer/Cargo.lock, contracts/adder/Cargo.lock, e2e-tests/Cargo.lock, flooder/Cargo.lock
See https://github.com/Cardinal-Cryptography/polkadot-sdk/pull/6
I run `cargo update` on `main` to get the above incorporated`.
It turns out this saves almost 2x build time - from 18 minutes to 10 minutes.
=> A0-4264:  resolve cyclic polkadot-sdk dependency

finality-aleph/src/sync/data.rs, finality-aleph/src/sync/handler/mod.rs, finality-aleph/src/sync/handler/request_handler.rs, finality-aleph/src/sync/tasks.rs
We no longer need the id-only requests, nor support for v2 messages. Complete removal of id-only request logic will happen in a follow-up PR.
=> A0-3575: Update block sync message versions

aleph-client/Cargo.lock, aleph-client/Cargo.toml, aleph-client/src/contract/event.rs, aleph-client/src/contract/mod.rs, aleph-client/src/pallets/contract.rs, e2e-tests/Cargo.lock, e2e-tests/src/test/adder.rs, e2e-tests/src/test/button_game/contracts.rs
Manual cherry-pick of https://github.com/Cardinal-Cryptography/aleph-node/pull/1679. E2e test run: https://github.com/Cardinal-Cryptography/aleph-node/actions/runs/8847540121, in particular containing cherry-picked tests of adder contract, which test the new functionality.
Client versioning is non-obvious, bumped one minor version and hope it'd avoid conflicts.
=> A0-4251: Cherry pick

finality-aleph/src/sync/handler/mod.rs, finality-aleph/src/sync/handler/request_handler.rs
When a block comes as a response to a request, we first process its header, similarly as we would get this header in a response. 
Additionally, next to making the `forest.importable(header.id)` check in `handle_header` which checks if forest would accept the corresponding block, we also allow for imports in a sequence. This means that if in the same response processing we imported the parent of the block, then we can also import the block, no matter what `forest.importable(...)` has returned.
=> A0-2980: Fix sync handler rejecting proper blocks.

bin/chain-bootstrapper/Dockerfile
=> A0-4268: Add curl to chain-bootstrapper docker image

finality-aleph/src/metrics/chain_state.rs
Changing buckets, because I set them incorectly previously. For slo, we want to measure reorgs of length >= 1, >= 2, >= 3, >= 5 and >= 10. In Prometheus, buckets are [0; x] for some values of x, so to count e.g. reorgs of length >= 5 we have to subtract those <= 4 from all the reorgs.
Hence, I decreased all bucket values by 1.
=> A0-3010: Fix reorg metrics buckets

finality-aleph/src/sync/forest/mod.rs, finality-aleph/src/sync/handler/mod.rs
Now any header with a number higher than the local favourite block can trigger a chain extension request. This makes the new sync keep up with blocks much better.
=> L1-220: Request chain extension more liberally

.github/actions/store-node-and-runtime/action.yml, .github/workflows/_unit-tests-and-static-checks.yml, .github/workflows/_update-node-image-infra.yml, .github/workflows/nightly-integration-tests.yml
See https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/ for more info.
=> A0-2999: Update all actions to run on node20

finality-aleph/src/sync/handler/mod.rs
Add test for handling a response with a wrong header in the middle, and checking if handler initiates the `ChainExtensionRequest` upon receiving state with various headers.
- tests
=> L1-122: More handler tests

.github/scripts/run_consensus.sh, .github/workflows/on-pull-request-commit.yml, e2e-tests/Cargo.lock, scripts/run_local_e2e_pipeline.sh, scripts/synthetic-network/README.md, scripts/synthetic-network/run_script_for_synthetic-network.sh
* Migrate to docker compose from docker-compose, as the former works both on ubuntu 20 and 22.
* Add a token transfer test to the PR pipeline. It is important to see if the chain's basic functionality works. It is currently expected to fail, as it does on `main`.
* fix some logging in `run_conensus.sh`
- bug fix
=> A0-4306: Migrate to docker compose from docker-compose

.github/workflows/on-pull-request-commit.yml
The change https://github.com/Cardinal-Cryptography/aleph-node/commit/a0faac51f21f46a90bc1e4000c6ca9211616dd87 had a bug that ran the `PR check title` job also on the `merge_group` trigger. It should run only on a PR. 
It fixes https://github.com/Cardinal-Cryptography/aleph-node/actions/runs/9188416432/job/25268221144
=> L1-55 Run check pr title only on pull request

.github/actions/run-e2e-test/action.yml, .github/scripts/run_e2e_test.sh, .github/workflows/_run-e2e-tests.yml
Recently, on main, there have been spurious nightly e2e logic test failures. While the exact root cause is unknown, they happen when the brand new chain is not yet up to speed with finalization. The scope of this task is to wait for finalization to spin off before starting an e2e case.
Currently, there’s an optional check called follow-up-finalization-check that is run after some e2e tests. It’s very cheap regarding time consumed, so we can always run before and after each e2e test. That fulfills the requirements of this task. Note that some e2e expects finalization to break after they run. 
When testing this PR, a bug in the previous change was accidentally found, causing 2 e2e cases to not run. A safeguard was added to prevent such situations in the future.
Please delete options that …
=> L1-258: Make all e2e tests run on a chain with up to speed finalization

scripts/accounts-invariants/chain_operations.py, scripts/accounts-invariants/pallet-balances-maintenance.py, scripts/accounts-invariants/total_issuance.py, scripts/accounts-invariants/utils.py
Implemented an algorithm that finds the first block hash that positively contributed to a total issuance imbalance. A positive contribution to the total issuance imbalance in block B is a situation in which the total issuance imbalance increases in block B. Total issuance imbalance is a difference between aggregated sum of total bolance over all accounts and balances.total_issuance storage value. There might be a difference in some value X in block B, and some value Y in the parent(B), and X > Y. 
There might be many such blocks in the chain [start_block_hash; end_block_hash], and this method returns the first one.
The method uses a bisection algorithm. It computes mid-range block hash by computing
```
mid_block_number = floor((end_block_number - start_block_number) / 2)
```
Then, …
=> L1-218: Implemented finding the first block which contributed to total issuance imbalance

Cargo.lock, bin/runtime/src/lib.rs, pallets/operations/Cargo.toml, pallets/operations/src/impls.rs, pallets/operations/src/lib.rs, pallets/operations/src/tests/data/transfer_return_code.wat, pallets/operations/src/tests/setup.rs, pallets/operations/src/tests/suite.rs, pallets/operations/src/traits.rs
This PR extends and makes final logic changes for pallet operations. Now, it works in general mode, which calculates the expected `consumers` counter, compares it to the current one, and decreases or increases it when necessary. There are two main additions to pallet logic:
* It is now aware of whether an account is a contract one - in such cases it needs +1 `consumers`
* from `polkadot-sdk 1.4.0`, balance locks do not contribute to the `consumers` counter anymore. Hence, that logic was removed from pallet operations. 
https://github.com/Cardinal-Cryptography/aleph-node/pull/1760
=> L1-66: Pallet operations latest changes

Cargo.lock, finality-aleph/src/session_map.rs
Recently failed there: https://github.com/Cardinal-Cryptography/aleph-node/actions/runs/9736643972/job/26867555923.
Reason:
```
---- session_map::tests::prunes_old_sessions stdout ----
thread 'session_map::tests::prunes_old_sessions' panicked at finality-aleph/src/session_map.rs:776:13:
assertion `left == right` failed: Session 0 should be pruned
```
Replaced some delays with `handle.await.unwrap()` and `sender` drop, as such a drop will cause `SessionMapUpdater` to finish.
- Bug fix (non-breaking change which fixes an issue) [non-prod code]
=> L1-271: Improve flaky session map test

.github/workflows/sync-from-snapshot-testnet.yml
Increase the test timeout by 30 minutes bc it started failing recently (eg. [here](https://github.com/Cardinal-Cryptography/aleph-node/commit/0757e1b6d8ea5f884fd8448755dbc2904385c4ea/checks) and [there](https://github.com/Cardinal-Cryptography/aleph-node/commit/246fd3f475b09a72f574f6c0934367209bd6dec6/checks)).
=> A0-4265: Inc testnet sync from snapshot timeout by 30m

.github/workflows/sync-from-snapshot-testnet-paritydb-pruned.yml, .github/workflows/sync-from-snapshot-testnet-paritydb.yml
Test `Sync from snapshot, Testnet, RocksDB` got an increase of timeout recently from `360` to `390` minutes.
Increase timeouts of the remaining two sync from snapshot test by the same percentage (`390/360=8.(3)%`).
`Sync from snapshot, Testnet, ParityDB non-pruned`: `240 -> 260`
`Sync from snapshot, Testnet, ParityDB pruned`: `60 -> 65`
* I have made neccessary updates to the Infrastructure
=> A0-4265: Inc testnet sync from snapshot remaining timeouts

Cargo.lock, bin/chain-bootstrapper/Cargo.toml, bin/chain-bootstrapper/src/chain_spec/builder.rs, bin/chain-bootstrapper/src/chain_spec/cli.rs, bin/chain-bootstrapper/src/chain_spec/commands.rs
This PR fixes following issues:
* it makes sure `--authorities-accounts-ids` is a subset of `--account-ids`
* `--accounts-ids` should have at least one account
* initial endowment is not in `u64` range when `--accounts-ids` == `--authorities-accounts-ids` == `--sudo account`. This should have been fixed in `polkadot 1.6.0`, but investigation why not is not in the scope of this task. 
=> L1-273: chain-bootstrapper cmd line fixes

.github/workflows/sync-from-snapshot-testnet.yml
Lat run was a genuine timeout.
=> L1-279: Increase timout for Testnet RocksDB snapshotter test

Cargo.lock, bin/chain-bootstrapper/src/chain_spec/builder.rs
Run `cargo update`  that, apart from third-party packages, bumps `polkadot-sdk` so that it incorporates this change
https://github.com/Cardinal-Cryptography/polkadot-sdk/pull/11
It's a bugfix for an issue introduced in line https://github.com/Cardinal-Cryptography/aleph-node/commit/e44450f8da37bec94604fb30613ef8a7519b703f#diff-fb8fcd5264d8437aa73d76721b545892cbc19c721573f0c962193264b764c4e8L69 that caused some reward calculation 
that caused some e2e to fail.
Also, this bumps the `synthetic-network` submodule to the latest commit, no reason it stays behind
- bug fix
* https://github.com/Cardinal-Cryptography/aleph-node/actions/runs/10110067781 - PASSED
=> L1-287: Run cargo update

.github/workflows/sync-from-snapshot-mainnet-paritydb-pruned.yml, .github/workflows/sync-from-snapshot-mainnet-paritydb.yml, .github/workflows/sync-from-snapshot-mainnet.yml, .github/workflows/sync-from-snapshot-testnet-paritydb-pruned.yml, .github/workflows/sync-from-snapshot-testnet-paritydb.yml, .github/workflows/sync-from-snapshot-testnet.yml
Increase the timeouts again, this time to significantly larger values to prevent not meaningful test failures.
=> A0-4265: Increase all sync from snapshot tests timeouts

docker/Dockerfile.synthetic_network.build, scripts/synthetic-network/build_synthetic-network.sh
Added a custom version of the Dockerfile from the repo of the synthetic-network tool that uses a more specific version of the rust compiler. Also removed an ad-hoc fix for node-js images used by the original Dockerfile.
=> L1-278: Fix synthetic-network repo compilation

.github/scripts/test_db_sync.sh
Alters test_db_sync.sh script to kill aleph-node process once things are tested. It seems that cleaning github runner workspace, which is a next step that executes bunch of `rm -rf` commands, is failing because aleph-node running in the background keeps creating new files in the directories that are meant to be removed (hence, the `rm -rf` commands fail with `Directory not empty`).
=> A0-4324: Alter test_db_sync.sh to kill aleph-node after tests

bin/runtime/src/lib.rs
=> L1-292: `era_payout` unit tests

benches/payout-stakers/README.md, benches/payout-stakers/src/main.rs, bin/chain-bootstrapper/src/chain_spec/builder.rs, scripts/run_nodes.sh
This PR updates `payout_stakers` create so it runs with latest `main`, and how to run it against `r-13.4` release. Ultimately, this test should end up in nightly CI. 
=> L1-315: Updated payout_stakers bench with latest main

.github/workflows/_check-runtime-metadata.yml, Cargo.lock, bin/node/src/aleph_cli.rs, bin/node/src/service.rs, clique/src/rate_limiting.rs, docker/docker_entrypoint.sh, finality-aleph/Cargo.toml, finality-aleph/src/lib.rs, finality-aleph/src/network/build/base.rs, finality-aleph/src/network/build/mod.rs, finality-aleph/src/network/build/transport.rs, finality-aleph/src/network/mod.rs, finality-aleph/src/network/substrate.rs, finality-aleph/src/nodes.rs, nix/versions.nix, rate-limiter/Cargo.toml, rate-limiter/src/lib.rs, rate-limiter/src/rate_limiter.rs, rate-limiter/src/token_bucket.rs
Implementation of a shared-bandwidth rate-limiter for both substrate-based and alephbft networks.
In a next PR I will introduce a new e2e-test that should help to verify these changes.
=> A0-4318: rate-limiter for all

Cargo.lock, bin/chain-bootstrapper/src/chain_spec/commands.rs, bin/node/Cargo.toml, bin/node/src/aleph_node_rpc.rs, bin/node/src/cli.rs, bin/node/src/executor.rs, bin/node/src/lib.rs, bin/node/src/main.rs, bin/runtime/src/lib.rs, finality-aleph/src/abft/current/mod.rs, finality-aleph/src/abft/legacy/mod.rs, finality-aleph/src/abft/traits.rs, finality-aleph/src/block/mock/backend.rs, finality-aleph/src/block/mod.rs, finality-aleph/src/block/substrate/chain_status.rs, finality-aleph/src/crypto.rs, finality-aleph/src/network/mock.rs, finality-aleph/src/network/tcp.rs, pallets/aleph/src/lib.rs, pallets/elections/src/mock.rs, pallets/elections/src/tests.rs, rust-toolchain.toml
Mostly bumps the toolchain, but this also resulted in the detection and removal of some unused code. This PR also removes support for the `try-runtime` subcommand from the node binary – it was deprecated and we are using the external tool already anyway.
Toolchain bump and cleanup.
=> A0-4341: Bump rust toolchain to 1.79

Cargo.lock, Cargo.toml, finality-aleph/Cargo.toml, finality-aleph/src/abft/crypto.rs, finality-aleph/src/abft/current/mod.rs, finality-aleph/src/abft/current/traits.rs, finality-aleph/src/abft/legacy/mod.rs, finality-aleph/src/abft/legacy/traits.rs, finality-aleph/src/abft/mod.rs, finality-aleph/src/abft/network.rs, finality-aleph/src/abft/types.rs
Updates ABFT to 0.39. Starts using the extended finalization handler, but in a trivial way, the actual scoring will happen in a separate PR.
Note that this shouldn't break the pipelines that connect to test/mainnet (like #1842 did), even though it technically makes `main` incompatible, since the incompatibility is limited to validation. However I might be wrong, so keep that in mind.
=> A0-4574: Update ABFT after release 14

.github/workflows/on-push-release-tag.yml, Cargo.lock, bin/node/Cargo.toml
Since [we changed](https://github.com/Cardinal-Cryptography/aleph-node/commit/a0faac51f21f46a90bc1e4000c6ca9211616dd87) versioning scheme, we need to adapt check in workflow on tag push. Previously [it worked](https://github.com/Cardinal-Cryptography/aleph-node/actions/runs/11235658890/job/31234074222) since `version` in node's `Cargo.toml` was `0.X.Y`, now it is `X.Y.Z`.  Now it [does not](https://github.com/Cardinal-Cryptography/aleph-node/actions/runs/12140381720/job/33850050691), which this PR fixes.
=> L1-55 Fixed on push tag workflow

.github/workflows/on-push-release-tag.yml
Since [we changed](https://github.com/Cardinal-Cryptography/aleph-node/commit/a0faac51f21f46a90bc1e4000c6ca9211616dd87) versioning scheme, we need to adapt check in workflow on tag push. Previously [it worked](https://github.com/Cardinal-Cryptography/aleph-node/actions/runs/11235658890/job/31234074222) since `version` in node's `Cargo.toml` was `0.X.Y`, now it is `X.Y.Z`.  Now it [does not](https://github.com/Cardinal-Cryptography/aleph-node/actions/runs/12140381720/job/33850050691), which this PR fixes.
=> L1-55: Fixed on push tag workflow

.github/workflows/nightly-check-node-features-build.yml
Fix for https://github.com/Cardinal-Cryptography/aleph-node/actions/runs/12147201626/job/33872892632
After change https://github.com/Cardinal-Cryptography/aleph-node/commit/9c2036b80165ca15fda513011bdd901f65869e0c we don't support `try-runtime` feature anymore. 
=> Try-runtime is not supported in aleph-node anymore.

Cargo.lock, aleph-client/src/aleph_zero.rs, bin/fake-runtime-api/src/lib.rs, bin/runtime/src/lib.rs, finality-aleph/src/abft/mod.rs, pallets/aleph-runtime-api/src/lib.rs, pallets/aleph/Cargo.toml, pallets/aleph/src/lib.rs, primitives/src/lib.rs
Adds runtime api for the client side to store abft performance scores on chain. It's implemented using unsigned transactions since finality committee is considerably smaller than block production committee.
=> A0-4343: Implement runtime api for storing abft scores on chain.

finality-aleph/src/abft/current/mod.rs, finality-aleph/src/abft/current/performance/mod.rs, finality-aleph/src/abft/current/performance/service.rs, finality-aleph/src/abft/current/traits.rs, finality-aleph/src/abft/mod.rs, finality-aleph/src/party/manager/authority.rs, finality-aleph/src/party/manager/mod.rs, finality-aleph/src/party/manager/task.rs
Adds a service that will be handling the batches returned from ABFT to create scores. This is only the boilerplate code needed for that, the actual logic of creating the scores will be in a separate PR.
=> A0-4579: Add ABFT scoring service, currently doing nothing

aggregator/src/aggregator.rs, aggregator/src/lib.rs, finality-aleph/src/aggregation/mod.rs, finality-aleph/src/party/manager/aggregator.rs
Makes the aggregator more generic and prepares for gathering multisignatures under hashes of ABFT performance reports. Not yet connected to anything, so technically doesn't change any behaviour.
=> A0-4342: Support for multiple kinds of hashes in aggregator

bin/node/src/service.rs
Fix for regression introduced in https://github.com/Cardinal-Cryptography/aleph-node/commit/1d65f62de7e090d07b0e6f2b2261c3edaa9583a1#diff-787215c6ec15e1ecc63e5d3628fc9cce8a083c8c658f7ce2312ff0c5b0265d5eR219.
There would be a companion PR in `main` as well.
Run locally command:
```
curl  -H "Content-Type: application/json" -d '{"id":1, "jsonrpc":"2.0", "method": "alephNode_unstable_validatorNetworkInfo", "params": []}' http://localhost:9944/
{"jsonrpc":"2.0","result":{"5GBNeWRhZc2jXu7D55rBimKYDk8PGk8itRYFTPfC8RJLKG5o":{"session":0,"network_level_address":"127.0.0.1:30344","validator_network_peer_id":"5FyuCn5rKTJdYDPTbT1Xhr8VjqYWYskNrudefpk4VQSpkQse"},"5DiDShBWa1fQx6gLzpf3SFBhMinCoyvHM1BWjPNsmXS …
```
=> A0-0000: Fix for gathering validator network data

bin/node/src/aleph_cli.rs, bin/node/src/service.rs
"Cherry-pick" of https://github.com/Cardinal-Cryptography/aleph-node/commit/a9935749cf2c92e32f712e959e5b567a8a88980b . It's fine to rename param as this change will be released in the next major release.
Run locally command:
```
curl  -H "Content-Type: application/json" -d '{"id":1, "jsonrpc":"2.0", "method": "alephNode_unstable_validatorNetworkInfo", "params": []}' http://localhost:9944/
{"jsonrpc":"2.0","result":{"5F4H97f7nQovyrbiq4ZetaaviNwThSVcFobcA5aGab6167dK":{"session":11,"network_level_address":"127.0.0.1:30346","validator_network_peer_id":"5G8NVxeEmShiyafdkTSEoGXXqh8beqWFiaZrMWUcaHm3Pnuf …
```
=> A0-0000: Rename flag no_collection_of_extra_debugging_data to collect_validator_network_data.

finality-aleph/src/abft/current/mod.rs, finality-aleph/src/abft/current/performance/mod.rs, finality-aleph/src/abft/current/performance/service.rs, finality-aleph/src/abft/mod.rs, finality-aleph/src/nodes.rs, finality-aleph/src/party/manager/aggregator.rs, finality-aleph/src/party/manager/mod.rs, finality-aleph/src/runtime_api.rs, primitives/src/lib.rs, scripts/run_nodes.sh
Send performance scores to the aggregator for gathering multisignatures under them and then submits them on chain. This should finish the ABFT performance project on the node side, modulo testing.
=> A0-4346: Gather signatures and actually submit scores to chain

bin/runtime/src/lib.rs
Also, this PR sets proper `spec-version` - should be 15.0.0 as last cut off release branch is `release-14`.
=> A0-4583: Make NonTransfer filter out identity pallet

finality-aleph/src/sync/service.rs
We don't need to send additional requests when in major sync, and when we do then the helpful nodes receiving them overwhelm us with data. It's a bug that's a bit hard to trigger, but quite annoying when it happens. This PR stops that behaviour without impacting major sync times. I tested that major sync speed when far from the chain head is unaffected (some earlier attempts _did_ affect it, even if only a little), but was unable to check that this actually solves the issue it's designed to solve, nor that it doesn't cause some problems when the node is in session – that is _very_ unlikely imo, but crucial, so has to be tested before full release.
=> A0-4596: Avoid sending task requests when in major sync

.github/actions/sync-from-snapshot/action.yml, .github/workflows/sync-from-snapshot-mainnet-paritydb-pruned.yml, .github/workflows/sync-from-snapshot-mainnet-paritydb.yml, .github/workflows/sync-from-snapshot-mainnet.yml, .github/workflows/sync-from-snapshot-testnet-paritydb-pruned.yml, .github/workflows/sync-from-snapshot-testnet-paritydb.yml, .github/workflows/sync-from-snapshot-testnet.yml
1. Adds support for overriding snapshot date. If this date is not given, current day is assumed (current behaviour).
2. Move workflow run time to +1 day.
=> A0-4610: Added support for overriding snapshot say

.github/workflows/featurenet-create.yml, .github/workflows/nightly-update-test-testnet-main.yml, .github/workflows/weekly-featurenets-short-session-full-sha.yml, .github/workflows/weekly-featurenets-short-session-tag.yml
Minor fixes to featurenets after recent Mainnet 14 release.
https://github.com/Cardinal-Cryptography/aleph-node/actions/runs/13176739999/job/36778388597
=> A0-0000: Fix finality version in updatenet test

Cargo.lock, bin/node/Cargo.toml, bin/runtime/Cargo.toml, bin/runtime/src/lib.rs
* Setting node and runtime crate version
* `spec_version` is already set to correct number
* `transaction_version` does not need to be bumped
* Enabling migration
=> A0-4615: Release 15 preparations

bin/runtime/src/lib.rs
On Mainnet and Testnet it is 18
=> Revert transaction_version to 18

.github/scripts/test_db_sync.sh, .github/workflows/sync-from-snapshot-mainnet-rocksdb-pruned.yml, .github/workflows/sync-from-snapshot-testnet-rocksdb-pruned.yml
* Remove ParityDB snapshotter test
* Add RocksDB Pruned snapshotter test
=> A0-4546: Extend github-based tests for pruning with pruned rocksdb snapshot

.github/scripts/test_db_sync.sh, .github/workflows/sync-from-snapshot-mainnet-paritydb-pruned.yml, .github/workflows/sync-from-snapshot-mainnet-rocksdb-pruned.yml, .github/workflows/sync-from-snapshot-testnet-paritydb-pruned.yml, .github/workflows/sync-from-snapshot-testnet-rocksdb-pruned.yml
Revert "A0-4546: Extend github-based tests for pruning with pruned rocksdb snapshot (#1948)"
This reverts commit 81c377d0e0fc866ccf7c71e10a2b18170f03e571.
Removed Parity non-pruned workflows for Testnet and Mainnet. Added RocksDB Pruned workflows for Mainnet and Testnet.
Run manually ParityDB Pruned for Mainnet and Testnet, which were not triggered for 2025-02-22 day.
* https://github.com/Cardinal-Cryptography/aleph-node/actions/runs/13493135548
* https://github.com/Cardinal-Cryptography/aleph-node/actions/runs/13493135540
=> A0-0000: Fix once again snapshot workflows

finality-aleph/src/sync/forest/mod.rs, finality-aleph/src/sync/forest/vertex.rs, finality-aleph/src/sync/handler/mod.rs, finality-aleph/src/sync/service.rs, finality-aleph/src/sync/tasks.rs
By optimistically assuming that a block that we started importing will get imported, we treat it as already imported for purposes of sending requests. This should limit both the amount of received blocks, as well as the amount of blocks in the import queue, both of which were slowing sync down.
=> A0-4616: Don't request blocks you started iimporting

finality-aleph/src/sync/forest/mod.rs, finality-aleph/src/sync/forest/vertex.rs, finality-aleph/src/sync/handler/mod.rs, finality-aleph/src/sync/service.rs, finality-aleph/src/sync/tasks.rs
By optimistically assuming that a block that we started importing will get imported, we treat it as already imported for purposes of sending requests. This should limit both the amount of received blocks, as well as the amount of blocks in the import queue, both of which were slowing sync down.
=> A0-4616: Don't request blocks you started iimporting (#1950)

.github/workflows/_build-aleph-e2e-client.yml, .github/workflows/_build-and-push-cliain.yml
As per PR title - for some reason automatic toolchain download stopped working. 
=> Introduce relative directories when installing Rust in e2e-tests and cliain build

.github/workflows/deploy-to-mainnet.yml
This is a bugfix for a regression introduced in https://github.com/Cardinal-Cryptography/aleph-node/commit/74c888e981cabe265d5352a771ccbeeccc1b9cbb
=> A0-0000: Forgot to pass ref

finality-aleph/src/sync/forest/mod.rs, finality-aleph/src/sync/handler/mod.rs
Our sync tried importing everything that was required. This was not a major issue before 15.1, since at worst the import failed and whatever, but with optimistic imports we gotta be relatively confident that the import will actually work.
=> A0-0000: Don't import unimportable blocks

.github/workflows/nightly-update-test-mainnet-testnet.yml
With Mainnet v15 release, `chain-bootstrapper` supports only `legacy` or `current`. 
Run https://github.com/Cardinal-Cryptography/aleph-node/actions/runs/14078538853
=> A0-4612: Fix update net test deploy from Testnet to Mainnet

.github/workflows/_run-e2e-tests.yml, e2e-tests/src/test/performance.rs
The way `one_validator_is_dead` is written now, it's disabling both AURA and Aleph keys. Since default production ban config threshold is 3, sometimes we kicked disabled node from the committee which then resulted in perfect score, hence test failed. This PR fixes that by extending production ban config threshold so that kick does not happen.
There's tiny bug in the test which does not influence test run - it printed out wrong account id to std out. Also, I decreased waiting time here and there so both performance tests should run faster now (around 3 minutes).
* https://github.com/Cardinal-Cryptography/aleph-node/actions/runs/14104180901
=> A0-0000 Fixed performance e2e flakiness

.github/actions/store-artifacts-in-s3/action.yml, .github/workflows/on-main-or-release-branch-commit.yml, .github/workflows/on-release.yml
What needs to be done?
* In push to main workflow, we should store as well chain-bootstrapper binary
* In release changed workflow, we should attach production chain bootstrapper
Why?
* For us devs doing release preparation tests - now for 14 release I need to build it manually which is error-prone
* Community transparency   - generating runtime is now decoupled from aleph-node
Also, `profile` input was removed from store artifacts action, since it was not used with `test` anywhere. 
* https://github.com/Cardinal-Cryptography/aleph-node/actions/runs/14106515515 PASS
=> A0-4614: attach chain bootstrapper to release

.github/actions/sync-from-snapshot/action.yml, .github/scripts/test_db_sync.sh
This change update snapshot URLs to new ones, as well as remove "mark snapshot as latest" feature from tests,
=> A0-0000: Update Snapshot URLs
